### ISSUE TITLE
Running runtest.bat in IntelliJ

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#1]
Hi, I'm at A-TextUiTesting after level-4 of the iP. I encounter this error when running the "runtest.bat" file:
```
java.lang.UnsupportedClassVersionError: Duke has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
```
I'm using Windows. At first, this error occurs also when I run "runtest.bat" directly (double-click), so I downloaded and installed the Oracle OpenJDK 11.0.13 and added the path to the system environment variables. Now it works properly when I double-click to run it, but I need to compare the actual and expected outputs manually. However, the error still appears when I run it in IntelliJ, and it fails to produce the actual output, despite that I have changed both the JDK home path in File > Project Structure and the Boot Java Runtime (see the figure) to Oracle OpenJDK 11.0.13. I have also recompiled the Duke project.
<img width="350" alt="Screenshot 2022-01-15 205618" src="https://user-images.githubusercontent.com/67496158/149622731-c32845eb-1eac-4afe-9fe4-24065dee51da.png">
Any help is appreciated. Thanks.

**Comment by damithc** [comment]
The very first post in the forum 🍾 :-)
@zihaowrez also mention how exactly you are running that .bat file in Intellij. Using Intellij's Terminal window?

**Comment by zihaowrez** [comment]
I run it directly by clicking the green triangle:
<img width="563" alt="Screenshot 2022-01-15 211651" src="https://user-images.githubusercontent.com/67496158/149623189-e800d8a4-2ddf-4b92-9ded-370163772aca.png">
I'm not sure how to run it using IntelliJ's Terminal window. The first line gives an error:
<img width="314" alt="Screenshot 2022-01-15 212220" src="https://user-images.githubusercontent.com/67496158/149623281-9e055eda-5544-4bb6-9420-ea64f6ef0afa.png">

**Comment by zhongfu** [comment]
just checking, have you restarted IntelliJ (or maybe rebooted your entire computer) after updating your system env vars? i'm not too familiar with Windows, but there's a chance that IntelliJ is still using the old $PATH or something

perhaps try adding `echo %PATH%` and `java -version` to runtest.bat, and running runtest.bat to see if what you get is what you're expecting

**Comment by zihaowrez** [comment]
Rebooting worked... Thank you😂

**Comment by damithc** [comment]
Thanks for the help @zhongfu
