### ISSUE TITLE
Do we still have to commit A-Enums if we don't use them?

### ISSUE THREAD

**Issue by ryantanlien** [nus-cs2103-AY2122S2/forum#10]
Question is in the title.

**Comment by domlimm** [comment]
I don't think so! According to that level

**Comment by damithc** [comment]
> I don't think so! According to that level

Yup. The increment `A-Enums` is optional (i.e., do only _if applicable_ to your code).

![image](https://user-images.githubusercontent.com/1673303/150246710-796e365a-edbd-4089-b9e6-5aaeb57f974c.png)

That said, it might be useful to discuss/share how Enums was used by others, in case anyone found a way to apply it in the project.

**Comment by yl-ang** [comment]
Not sure if this is recommended but I used enums to define error strings and grouped them together.  This makes my program more organized in handling errors and easier for me to change my error strings (By looking up the enum and modifying the relevant error string).

https://stackoverflow.com/questions/446663/best-way-to-define-error-codes-strings-in-java

**Comment by sbhbenjamin** [comment]
Another possibility is using enum to store the valid commands (i.e. list, todo, deadline, etc.). This allows for enums to be used as a validation tool, to check if the incoming input is a valid command based on the aforementioned fields.

**Comment by s7manth** [comment]
One interesting approach I found was to incorporate enums was to use validation functions inside of it. 

There would be a public enum with all the input command types. The input strings would be validated inside an enum, and the subsequent logic can be run when the pattern of the input string matches with a particular command type. 

Sort of like how it was demonstrated [here](https://stackoverflow.com/a/2457104).

**Comment by Yukun99** [comment]
Alternatively you can just try implementing a certain feature using enums even if it doesn't require it, just so that you can practice.

**Comment by ryantanlien** [comment]
> One interesting approach I found was to incorporate enums was to use validation functions inside of it.
> 
> There would be a public enum with all the input command types. The input strings would be validated inside an enum, and the subsequent logic can be run when the pattern of the input string matches with a particular command type.
> 
> Sort of like how it was demonstrated [here](https://stackoverflow.com/a/2457104).

I think this was the method that I eventually used, as using the enums this way helps with refactorability in later iterations. Especially if the number of input command grows, behavior and exception handling can be tied to the Command enum. Thanks everyone for your help!. I will now be closing this thread.
