### ISSUE TITLE
Question Regarding Stashing

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#100]
I understand that `git stash` allows us save our current uncommitted changes of current branch A, so that we can check out another branch B, and come back to restore these uncommitted changes at branch A.

My question is then, if I realized that I already made a lot of uncommitted changes on branch A that is supposed to be done on branch B, how do I "move" these uncommitted changes to branch B? Can I `git stash` on branch A, then create a new branch B and checkout branch B, then restore the stash on branch B?

Below is an example for clarity

![image](https://user-images.githubusercontent.com/71639142/152394207-6a88ca90-95a1-4c10-bcce-d80b19f4ceeb.png)

I am currently on `master` branch and already made some uncommitted changes that were supposed to be on `branch-Level-10` branch (which I forgot to create). Is it possible to stash the changes, create `branch-Level-10`, and restore the stash changes on the newly created branch?

I am not so concerned about iP for because I can still make the grader track my work as long as I have the tag and branches. I am more concerned about the case during tP, in the case where I forgot to create a new feature branch but already made a lot of changes. I wouldn't want to commit to `master` branch directly in the case of tP.

**Comment by takufunkai** [comment]
You can just simply create the branch you forgot to create without doing any stashing. Your changes will automatically be added to the newly created branch. Try running `git checkout -b branch-Level-10` on master, then run `git status`. You should see you are on bLevel-10 with the changes you wanted to shift over. 

Your stash method works as well, especially if you want to move these changes to an existing branch (that might share a different history from your current branch).

**Comment by damithc** [comment]
@bingsen0806 A gentle reminder to close this issue if the problem has been resolved.
If not resolved yet, please post a comment explaining which part of the problem/question remains unresolved.
