### ISSUE TITLE
How to configure Intellij to always end file with newline

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#101]
Hi all, I was trying to get rid of the Checkstyle error `File does not end with a newline.`
I tried to configure Intellij reformat settings to add newline automatically, but couldn't find how to do it.
So I manually pressed enter at end of the files, but am still trying to figure it out.
It would be nice if anyone can help me out!

**Comment by domlimm** [comment]
Hello @B1LLP4RK ! [This](https://stackoverflow.com/questions/997021/how-to-get-rid-of-checkstyle-message-file-does-not-end-with-a-newline) might help!

You'll need to edit your `config/checkstyle/checkstyle.xml` file.

**Comment by damithc** [comment]
It's actually better if this rule is followed, as doing so also helps with Git. Note how SoureTree too complains if there is no new line at the end of a file
![image](https://user-images.githubusercontent.com/1673303/152494838-b7320187-67ec-44d6-9786-1aa9a4515c64.png)

More info https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by Spyobird** [comment]
File -> Settings -> Editor -> General -> On Save -> Ensure every saved file ends with a line break

**Comment by B1LLP4RK** [comment]
@Spyobird  Thank you so so so much!
