### ISSUE TITLE
GUI "Hello world" showing random text

### ISSUE THREAD

**Issue by brandonrhan** [nus-cs2103-AY2122S2/forum#105]
Hi, I am seeing random text when I run GUI "Hellow world". I am seeing this error message as well.

<img width="115" alt="Screen Shot 2022-02-05 at 10 55 41 AM" src="https://user-images.githubusercontent.com/92209052/152626424-65af96cd-2eef-4be7-a48b-e25f02b91efb.png">
<img width="1920" alt="Screen Shot 2022-02-05 at 10 54 26 AM" src="https://user-images.githubusercontent.com/92209052/152626430-659a2cb8-d511-4ab1-bcda-cde98201ce25.png">

I have looked at #35 and the previous issue and change my java version. The current set up is below
<img width="900" alt="Screen Shot 2022-02-05 at 10 55 02 AM" src="https://user-images.githubusercontent.com/92209052/152626483-9156caed-b3a5-4628-bf78-b9fb50272ff5.png">
<img width="577" alt="Screen Shot 2022-02-05 at 10 58 07 AM" src="https://user-images.githubusercontent.com/92209052/152626485-45f43820-e3e5-4f54-8986-4e461e3aa236.png">

But I am still seeing random texts. Can someone help me with this?

**Comment by damithc** [comment]
@brandonrhan confirmed you downloaded the `JDK FX` version (note the 'FX'), as given in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language ?

**Comment by brandonrhan** [comment]
> @brandonrhan confirmed you downloaded the `JDK FX` version (note the 'FX'), as given in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language ?

Hi prof I have changed my JDK version to be the one exactly the same given on the website, but this time I can not see any output and I received this error message.

Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: 'boolean com.sun.glass.ui.mac.MacApplication._isNormalTaskbarApp()'
	at javafx.graphics/com.sun.glass.ui.mac.MacApplication._isNormalTaskbarApp(Native Method)
	at javafx.graphics/com.sun.glass.ui.mac.MacApplication.isNormalTaskbarApp(MacApplication.java:379)
	at javafx.graphics/com.sun.glass.ui.mac.MacApplication.lambda$runLoop$3(MacApplication.java:88)

**Comment by damithc** [comment]
> Hi prof I have changed my JDK version to be the one exactly the same given on the website

Best to remove other JDK versions as well.

Also use the check specified in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language to confirm AB3 works correctly with your JDK.

**Comment by brandonrhan** [comment]
> > Hi prof I have changed my JDK version to be the one exactly the same given on the website
> 
> Best to remove other JDK versions as well.
> 
> Also use the check specified in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language to confirm AB3 works correctly with your JDK.

Prof I have solved the problem, the problem is because of I have downloaded javafx-sdk-11 but I copy the "javafx-sdk-11.0.2" from the website to the VM option. I have removed all other JDk versions and my AB3 works well. Thank you very much for you help. Really appreciate that!!
