### ISSUE TITLE
Error when trying to set up JavaFX

### ISSUE THREAD

**Issue by snoidetx** [nus-cs2103-AY2122S2/forum#107]
Hi,

I am trying to follow this [tutorial](https://se-education.org/guides/tutorials/javaFx.html) to work on my GUI. At first I tried to set up JavaFX using Gradle following the instructions and get the following error when I ran my programme:

`JavaFX runtime components are missing, and are required to run this application`

Then I saw this [post](https://github.com/nus-cs2103-AY2021S1/forum/issues/128) and tried to follow the instructions under "if you are not using Gradle". The error changed into:

`Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found`

Anyone has any idea on this?

**Comment by damithc** [comment]
@snoidetx Recommended to use gradle. The 'if not using gradle' option is meant for students of another module.

**Comment by snoidetx** [comment]
> @snoidetx Recommended to use gradle. The 'if not using gradle' option is meant for students of another module.

@damithc Sorry prof but gradle gives me the first error above...

**Comment by damithc** [comment]
> > @snoidetx Recommended to use gradle. The 'if not using gradle' option is meant for students of another module.
> 
> @damithc Sorry prof but gradle gives me the first error above...

Let's wait to see if anyone else in the class knows how to fix that problem. In the meantime, you can ensure you are using the correct Java version as given [here  ](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language) (especially if you are using a Mac) and you haven't miss any steps in the tutorial.

**Comment by snoidetx** [comment]
> > > @snoidetx Recommended to use gradle. The 'if not using gradle' option is meant for students of another module.
> > 
> > 
> > @damithc Sorry prof but gradle gives me the first error above...
> 
> Let's wait to see if anyone else in the class knows how to fix that problem. In the meantime, you can ensure you are using the correct Java version as given [here ](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language) (especially if you are using a Mac) and you haven't miss any steps in the tutorial.

Okay prof! If in the meantime I manage to fix it by myself I will update here as well!

**Comment by snoidetx** [comment]
@damithc I have followed your instruction and reinstalled my Java. It works now. I guess that is because previously although I also downloaded Java from Azul, I did not see the small arrow pointing at the `JDK FX`.

If anyone else also experiences this issue, I believe that it could probably be caused by this problem as well.
