### ISSUE TITLE
Not pushing to GitHub with GitHub account

### ISSUE THREAD

**Issue by vishandi** [nus-cs2103-AY2122S2/forum#108]
Hi! 

I've been using SourceTree since the beginning of iP, but I only realised now that all of the pushes that I did through SourceTree is not connected to my GitHub account. Hence, in my repo commit history, the commits is shown to be pushed by a non-GitHub account (no hyperlink to the committer). 

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/77654963/152632831-e2dbc716-8f99-4a2a-bd99-7ea6f7d2d6d2.png">

As shown above, the merging is done by my account as I do it via GitHub, but the push is done by some user named "Vishandi Rudy Keneta", which is my full name. I am wondering whether this is allowed or should I do anything about it, as all this time I didn't realise this problem because my progress is shown both in the [iP progress dashboard](https://nus-cs2103-ay2122s2.github.io/dashboards//contents/ip-progress.html) and in the [iP reposense](https://nus-cs2103-ay2122s2.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt&since=2022-01-14).

**Comment by damithc** [comment]
Should be fine @vishandi As iP is done by only one person, we assume all commits are from you anyway.

**Comment by vishandi** [comment]
Alright! Thank you very much Prof!
