### ISSUE TITLE
A-TextUiTesting:  'javac' is not recognized

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2103-AY2122S2/forum#11]
Hi guys, I was doing the A-TextUiTesting section and whenever I try to run runtest.bat, I get the message below. 
```
cmd.exe /c runtest.bat
********** BUILD FAILURE **********
'javac' is not recognized as an internal or external command,
operable program or batch file.

Process finished with exit code 1
```
Originally my runtest.bat file was completely unchanged so I went ahead and replaced lines 10 and 18 with the following statements respectively:

```
javac  -cp C:\2103T\iP\src\main\java -Xlint:none -d C:\Users\kashi\.jdks\corretto-11.0.13\bin C:\2103T\iP\src\main\java\*.java
java -classpath C:\Users\kashi\.jdks\corretto-11.0.13\bin Duke < input.txt > ACTUAL.TXT
```

There was still no change in the message. I'm not a 100% confident if those paths are what they require either so some guidance would be appreciated:) I also did do a quick google search and followed the steps on this link: https://www.java67.com/2015/07/javac-is-not-recognized-as-internal-or-external-command-program-batch-file.html#ixzz5WjtBMio9 but it didn't seem to work either:/

Does anyone have any idea what I could be messing up or overlooking? I'm a Windows user. Thanks!!

**Comment by zhongfu** [comment]
Try adding `C:\Users\kashi\.jdks\corretto-11.0.13\bin` [into your $PATH](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)#:~:text=To%20add%20a%20path%20to%20the%20PATH%20environment%20variable&text=In%20the%20System%20dialog%20box,to%20Path%20and%20select%20it.). You might have to reopen your IDE (or cmd, or explorer.exe) or reboot your computer for the changes to take effect

Or, maybe replace `javac` with `C:\Users\kashi\.jdks\corretto-11.0.13\bin\javac`

**Comment by kxshxsh** [comment]
> Try adding `C:\Users\kashi\.jdks\corretto-11.0.13\bin` [into your $PATH](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)#:~:text=To%20add%20a%20path%20to%20the%20PATH%20environment%20variable&text=In%20the%20System%20dialog%20box,to%20Path%20and%20select%20it.). You might have to reopen your IDE (or cmd, or explorer.exe) or reboot your computer for the changes to take effect
> 
> Or, maybe replace `javac` with `C:\Users\kashi\.jdks\corretto-11.0.13\bin\javac`

Thanks @zhongfu !! The first method solved it:))
