### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#110]
Hi,

If GUI is implemented, do we also have to ensure that CLI is working?

**Comment by MontyPython28** [comment]
Hi,

This is from the Week 4 Project section in the CS2103/T website-

> Note that you no longer need to keep the text-based UI after adding a GUI. Similarly, there is no need to use the I/O redirection style automated testing anymore (that technique is suited for text UIs only).

Is this what you're asking about?
