### ISSUE TITLE
Gui not showing full list

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#112]
I have a problem with my list not displaying fully when the user input the "list" command. Is there anyway I can resolve this?

<img width="301" alt="image" src="https://user-images.githubusercontent.com/77788377/152650151-87fcd8a1-23b5-4c59-ade9-307afcbdf95f.png">

**Comment by yusufaine** [comment]
I actually faced the same issue as well, and it's actually due to the size of the `DialogBox::getDukeDialog`

What I did to solve this issue was to set the min height to fit the size of the text using:
```java
    public static DialogBox getDukeDialog(String text, Image img) {
        ...
        dukeDb.setMinHeight(Region.USE_PREF_SIZE);
        dukeDb.flip();
        return dukeDb;
    }
```

Hope it helps to solve your issue too! 👍

**Comment by Punpun1643** [comment]
Hi, drop in here as I faced the same issue and tried out @yusufaine method and it works! Thanks a lot!

**Comment by paing-oo** [comment]
Thank you @yusufaine !
