### ISSUE TITLE
Displaying Full Height of Children of ScrollPane in JavaFX

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#113]
I have built my Duke GUI following the [JavaFX Tutorial](https://se-education.org/guides/tutorials/javaFx.html), but I notice that the dialog boxes are not fully displayed when the content occupies more than 1 page.

Full dialogs:
<img width="293" alt="Screenshot 2022-02-05 210515" src="https://user-images.githubusercontent.com/67496158/152666078-9d88d2cb-226a-45c1-8083-bec0fac1866c.png">

Truncated dialogs:
<img width="298" alt="Screenshot 2022-02-05 210554" src="https://user-images.githubusercontent.com/67496158/152666074-85a53b06-996f-4b46-8f3f-92dd4e44b0be.png">

I wish that the dialogs are always displayed in full, but I haven't been able to find a solution. Does anyone know how to do this?

Thanks!

**Comment by damithc** [comment]
@zihaowrez a few others posted the same problem earlier. Perhaps look among [closed posts](https://github.com/nus-cs2103-AY2122S2/forum/issues?q=is%3Aissue+)?

**Comment by zihaowrez** [comment]
Thank you prof! @damithc
