### ISSUE TITLE
"Unable to open Display message" when running JAR file

### ISSUE THREAD

**Issue by NicsunXnus** [nus-cs2103-AY2122S2/forum#116]
When running the command ```java -jar duke-1.5.jar``` on my CLI, I received the error message:

![unable to open display error screenshot](https://user-images.githubusercontent.com/77189033/152684759-18fb26ec-4064-4c16-bfc3-d46ceeb8da9a.jpg)

I have already inserted the following lines into my ```build.gradle``` file:
```
repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```

Does anyone know a remedy to this problem?

**Comment by damithc** [comment]
@NicsunXnus Which OS and which flavor of terminal are you using to run the command?  If it is WSL on Windows, you can try regular DOS terminal instead.

**Comment by NicsunXnus** [comment]
> Which OS

I am using Windows.

> and which flavor of terminal

I am not really sure but I am using Windows Terminal to run the command.

>  If it is WSL on Windows, you can try regular DOS terminal instead.

From google, "Windows Terminal is a modern terminal application for users of command-line tools and shells like Command Prompt, PowerShell, and Windows Subsystem for Linux (WSL)". So I think this means I am using WSL? 
I am not sure how to run a DOS terminal, could you show me how?

Thank you for answering!

**Comment by limzk126** [comment]
Hi @NicsunXnus 
Is the Windows Terminal you are using also called `bash`? That is another name for WSL.

App icon for your reference:
![image](https://user-images.githubusercontent.com/88614036/152687151-44207738-29ef-4a03-b6e1-61c219725878.png)

**Comment by damithc** [comment]
> I am not sure how to run a DOS terminal, could you show me how?

DOS terminal is also called the 'Command Prompt'.
Hit Windows key and type 'cmd' which should point you to the Command Prompt app.
![image](https://user-images.githubusercontent.com/1673303/152687296-f5024122-c2fa-4ebb-a735-baedf371bd25.png)

**Comment by NicsunXnus** [comment]
Ok, thank you for the replies. I have tried running it on Command Prompt but I still received a similar error: 
```
javafx.fxml.LoadException:
file:/C:/Users/nicky/duke-1.5.jar!/View/MainWindow.fxml:9
        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
        ...
Caused by: java.lang.NullPointerException: Input stream must not be null
        ...
```
Edit: I have also removed the linux, mac lines from the depencies portion of the build.gradle file, and then created a new JAR file but still received the same error above.

**Comment by damithc** [comment]
> Ok, thank you for the replies. I have tried running it on Command Prompt but I still received a similar error:

This is a different error. Possibly a problem with locating image files or the data file?.



> Edit: I have also removed the linux, mac lines from the depencies portion of the build.gradle file, and then created a new JAR file but still received the same error above.

Best not to do this. If you do this, your JAR file might not work on those OS'es.

**Comment by limzk126** [comment]
@NicsunXnus 

I have a feeling it has something to do with the value of `fx:controller` in the `MainWindow.fmxl` file. Maybe you could take a look to see if that is correctly configured?

**Comment by NicsunXnus** [comment]
@damithc 
> This is a different error. Possibly a problem with locating image files or the data file?.
```
private final Image userImage = new Image(this.getClass().getResourceAsStream("/Images/Red.png"));
private final Image dukeImage = new Image(this.getClass().getResourceAsStream("/Images/Green.png"));
```
My code has these two lines that is responsible for getting the images. I have these two images' files stored in a ```resources``` folder under my ```main``` directory. I could run the program on my IDE so does that mean the problem may not be the missing files? Or do I need to do something additional outside the coding portion?

**Comment by NicsunXnus** [comment]
@limzk126 
> I have a feeling it has something to do with the value of fx:controller in the MainWindow.fmxl file. Maybe you could take a look to see if that is correctly configured?

My fx:controller is set to ```duke.gui.MainWindow``` as I have a MainWindow class inside a gui package, which is inside a duke package. The IDE did not flag it as an error so I think it should be ok.

**Comment by damithc** [comment]
@NicsunXnus push your latest code to a branch and share the link here so that someone else can take a look at it.

**Comment by NicsunXnus** [comment]
https://github.com/NicsunXnus/ip/tree/master/src/main

**Comment by limzk126** [comment]
@NicsunXnus 

Are you sure you are able to run the application using Gradle and use the javaFX GUI on Intellij? I tried cloning your latest code and it didn't seem to work on my end.

The `build.gradle` does not have correct configurations:
![image](https://user-images.githubusercontent.com/88614036/152690460-bb9459aa-af62-4141-ade0-aff2e2b6cc4e.png)

**Comment by NicsunXnus** [comment]
@limzk126 Sorry about that. I forgot to push the build.gradle file. Here is the new link: https://github.com/NicsunXnus/ip/tree/master/src/main
> Are you sure you are able to run the application using Gradle and use the javaFX GUI on Intellij? I tried cloning your latest code and it didn't seem to work on my end.

Yes. I ran it directly via the Launcher class. I am not sure how to run it by Gradle. Could you tell me how did you run it?

Screenshot of my gui:
![evidence](https://user-images.githubusercontent.com/77189033/152690787-5ef5a773-48c4-47f0-aa50-8fb837cc03b3.jpg)

**Comment by limzk126** [comment]
@NicsunXnus 

You can execute the Gradle run command by pressing `alt + F12` to open up the terminal in Intellij (Make sure the terminal's current directory is your project directory). And then use the command `./gradlew run`

This link provides you with the commands you can use for Gradle: https://docs.gradle.org/current/userguide/command_line_interface.html

You should substitute `gradle` with `./gradlew` as mentioned in the link above since we are using the Wrapper.

An alternative way is to use the Gradle side panel as shown below:
![gradle_example](https://user-images.githubusercontent.com/88614036/152691706-9b0c367e-6d36-411e-bd4a-e9599b00effc.png)

You can build, run, create jar files etc...

As for why you couldn't run the jar file using the Windows Terminal, I think it is because your image relative path is not following the exact case as your image file names. Apparently the relative path is case-sensitive so you should use the exact file name in your relative path instead.

decapitalize the 'R' and 'G':
```
private final Image userImage = new Image(this.getClass().getResourceAsStream("/Images/red.png"));
private final Image dukeImage = new Image(this.getClass().getResourceAsStream("/Images/green.png"));
```

Edit: As for why you could run the GUI on Intellij, It is possible that Intellij has a function to locate the right files even if they are not strictly following the exact casing.

**Comment by NicsunXnus** [comment]
@limzk126 
> decapitalize the 'R' and 'G':

Yes, that is exactly the problem. Thank you for your help! I think I will close this issue now.
