### ISSUE TITLE
Assertions are not verified

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#119]
Hi, I'm trying to use the assert feature but when I tested it out by inserting the `assert false` into the code, my program still runs perfectly without any error message.

I have already enabled assertions by adding the `enableAssertions = true` in the `build.gradle` file. 

Not sure if anyone faced similar problems or if I'm missing out on something 😅

**Comment by bingsen0806** [comment]
I rmb somewhere in the module website something mentioned about going to intellij settings, and set it such then whenever u run "java" command, a -ea flag will always be added to enable assertions

**Comment by Punpun1643** [comment]
Oh, yup that solved it. Thanks 😄 !
