### ISSUE TITLE
remotes/origin/HEAD* my command line shows this instead of my current branch, what does this mean?

### ISSUE THREAD

**Issue by Shivang211** [nus-cs2103-AY2122S2/forum#12]
I was trying to correct my ui-testing after which i commited the new changes. I did git add . -> git commit -m "..." -> git push, but instead of my changes being commited, my branch somehow changed to this and my changes weren't saved.

**Comment by damithc** [comment]
@Shivang211 perhaps give a screenshot of how things look in your repo e.g., how does the version graph looks in SourceTree?

**Comment by Shivang211** [comment]
> @Shivang211 perhaps give a screenshot of how things look in your repo e.g., how does the version graph looks in SourceTree?

Prof I am on Mac OS and am using CLI for git

**Comment by Shivang211** [comment]
my git log looks like this, however no changes were saved in the corrected ui-testing commit and all my work for that was reverted back as soon as i pushed :

```
commit 632898b76d54027fb2503524b73832ecdf97883f (HEAD, origin/master, origin/HEAD)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Thu Jan 20 10:57:48 2022 +0800

    corrected ui-testing

commit 262bf7635a5f24416444e765127b9c603443fe42 (master)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Thu Jan 20 00:17:08 2022 +0800

    abstracting print

commit 21063f6445a8adf93b98069cbdac4c707d579ade (tag: Level-6)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Thu Jan 20 00:07:07 2022 +0800

    added delete

commit d73f32910b88376bddcc73b8410b871c6e7e6abc (tag: Level-5)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Wed Jan 19 20:24:41 2022 +0800

    Added error checking

commit 55951fce3f985de5bf0e0995cb02181f4583f19e (tag: A-TextUiTesting)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Wed Jan 19 14:53:16 2022 +0800

    added ui-testing

commit cf648d2b7f5d0caf0c00ed3224f0282c57b1362d (tag: Level-4)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Wed Jan 19 13:55:04 2022 +0800

    Add level 4

commit 95924bbcc0a60a2af21b1060b5a2eda99c1c6067
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Tue Jan 18 15:36:14 2022 +0800

    Add event, deadline and todo classes

commit 3cf77a31e603678b46acaa8bb9885cbaf08358c7 (tag: Level-3)
Author: Shivang211 <shivanggupta2110@gmail.com>
Date:   Tue Jan 18 14:42:21 2022 +0800
```

**Comment by damithc** [comment]
> Prof I am on Mac OS and am using CLI for git

While it is good to master the git CLI, a GUI can be quite handy at times. For example, see how the screenshot helped in debugging this case https://github.com/nus-cs2103-AY2122S2/forum/issues/8 
For beginners, the best is to use both in tandem.

Actually, Git has an inbuilt rudimentary GUI named [gitk](https://www.atlassian.com/git/tutorials/gitk) if you don't want to install SourceTree

**Comment by Shivang211** [comment]
Prof i have reverted back to my master branch and redone my changes, however even after commiting, I am getting the following message, my gitignore contains *.class
`Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../.gitignore
        modified:   ../src/main/java/Duke.class
        modified:   ../src/main/java/Duke.java

no changes added to commit (use "git add" and/or "git commit -a")
(base) 
 ~/CS2103T/ip/text-ui-test/ [master*] 
`

**Comment by Shivang211** [comment]
Thanks Prof, I will do that. I have resolved my issue, should I be closing it?

**Comment by damithc** [comment]
> Thanks Prof, I will do that. I have resolved my issue, should I be closing it?

Good to hear that @Shivang211. Go ahead.
