### ISSUE TITLE
Use of Mockito Framework for Testing

### ISSUE THREAD

**Issue by sharpstorm** [nus-cs2103-AY2122S2/forum#120]
## Library
[Mockito Unit Testing Framework](https://site.mockito.org/)

## Purpose

Mockito adds the capability of [mocking](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks/) classes and methods for unit testing, providing unit tests with more control over the Class under test and its dependencies without necessitating major redesigns of the software to accommodate interfaces for Stubbing. I would like to use this library to write more comprehensive and robust JUnit test cases, and I will highlight some use cases in the write-up below.

### Motivation
Currently, unit testing is done entirely in the JUnit framework, which has limitations in isolating classes under test from its dependencies using Stubs. For example, JUnit cannot stub static methods which are not associated to an object and cannot be overriden by a subclass, so there is no viable way to change their behavior for testing.

### Mocking as the Solution
Mockito solves the limitation mentioned above by allowing the behavior of methods, both object-level and class-level, to be entirely changed without modifying the design of the software. Using mocks, the test case itself can specify the exact behavior of method calls, and completely eliminates external dependencies, either internally within the application's Classes or third party libraries, such as Java internal libraries or JavaFX libraries.

### Example: Mocking Static Methods
Consider this simplified excerpt from my `TaskList` inflation method:
```Java
class TaskListSerializer {
    public void inflate(InputStream stream) {
        ...
        for (int i = 0; i < recordCount; i++) {
            taskList.addTask(TaskSerializer.inflate(recordData));
        }
        ...
    }
}
```
There is a hard dependency on the static method of class `TaskSerializer`.
Using mocks, we can skip over the behavior of that method, isolating `TaskListSerializer` from `TaskSerializer` and any potential bugs.
```Java
try (MockedStatic<TaskSerializer> theMock = Mockito.mockStatic(TaskSerializer.class)) {
    theMock.when(() -> TaskSerializer.inflate(any())).thenReturn(new Todo(""));
    TaskList list = TaskListSerializer.inflate(new ByteArrayInputStream(data));
    assertEquals(4, list.getTaskCount());
}
```

### Example: Argument Capture
We can also capture the parameters used in method calls using Mockito. For example, this is how the `printCommand(String)` method can be mocked to capture the arguments it is called with, while at the same time overriding the original logic. This allows test specific logic to be contained within the test case itself, rather than using a Stub class overriding the Class being tested, which may not be reusable across multiple test cases and result in multiple single-use stubs being created.
```Java
ArrayList<String> lines = new ArrayList<>();
doAnswer((invocation) -> {
    invocation.<Function<Printable, Boolean>>getArgument(0)
            .apply((message) -> {
                lines.add(message);
            });
    return true;
}).when(ui).printCommand(any());
```
The lines `ArrayList` will contain the arguments that `printCommand` is called with at the end of the test.

## License

MIT License
[Mockito GitHub License Page](https://github.com/mockito/mockito/blob/main/LICENSE)

**Comment by damithc** [comment]
Approved.

**Comment by sharpstorm** [comment]
Thank you Prof. Closing issue since request has been approved.
