### ISSUE TITLE
GitHub CI build output differing from local machine output

### ISSUE THREAD

**Issue by jaegarpoon** [nus-cs2103-AY2122S2/forum#122]
Hi all, I noticed that there is a difference in output for the DateTimeFormatter locally vs the GitHub build.

Initial code:
```
    @Test
    public void testTask() {
        Task deadline = new Deadline("deadline return book /by 20/12/2022 1800");
        assertEquals(deadline.toString(), "[D][ ] return book (by: Dec 20 2022 6.00 PM)");

        Task event = new Event("event return book /at 20/12/2022");
        assertEquals(event.toString(), "[E][ ] return book (at: Dec 20 2022)");

        Task todo = new Todo("todo return book");
        assertEquals(todo.toString(), "[T][ ] return book");
    }
```

Error in GitHub Actions:
`DukeTest > testTask() FAILED
    org.opentest4j.AssertionFailedError: expected: <[D][ ] return book (by: Dec 20 2022 6.00 PM)> but was: <[D][ ] return book (by: Dec 20 2022 6.00 pm)>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:[55](https://github.com/jaegarpoon/ip/runs/5096757269?check_suite_focus=true#step:7:55))
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at DukeTest.testTask(DukeTest.java:20)`

The difference occurs in the formatting of "pm" and "PM", where the GitHub CI build outputs capital letters for it.

Not sure if any of you guys faced this issue, but just wanted to ask why the difference occurred. I am on an M1 Mac running the Azul build of JDK recommended by the module website. 

Thanks!

**Comment by damithc** [comment]
As this issue remains unresolved so far, I'm tagging a few other students (randomly selected) who have completed related increments, in case they can help: @zihaowrez @jaegarpoon @benmurphyy @dandaandaaaaaan @Wei-Xinn @tiewweijian @sharpstorm @michaelseyo @zzkzzzz @domlimm

**Comment by domlimm** [comment]
Hello @jaegarpoon ! I was wondering if you could print the Task before you call `assertEquals` and run `check` from your `gradle` window locally in IntelliJ to see what prints out. The CI config file that GitHub actions run uses `check` in gradle. Wondering if you have done this to take a look how it prints out.

E.g.:

```java
Task deadline = new Deadline("deadline return book /by 20/12/2022 1800");

System.out.println(deadline);

assertEquals(deadline.toString(), "[D][ ] return book (by: Dec 20 2022 6.00 PM)");
```

**Comment by sharpstorm** [comment]
Hello, could you also include the implementation for the method call you are using to format the date object into a String (in the `Deadline.toString()` function for reference?

**Comment by jaegarpoon** [comment]
Hi @domlimm, I ran on my local machine and was unable to print out since i was running the check with gradle.

Here's the output on gradle after editing for GitHub CI:

```
DukeTest > testTask() FAILED
    org.opentest4j.AssertionFailedError: expected: <[D][ ] return book (by: Dec 20 2022 6.00 pm)> but was: <[D][ ] return book (by: Dec 20 2022 6.00 PM)>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at DukeTest.testTask(DukeTest.java:21)
```

The toString method is here, @sharpstorm :
```
@Override
    public String toString() {
        return "[D]" + super.toString() + ("(by: " + this.getFullDateTime() + ")");
    }
```

getFullDateTime():
```
public String getFullDateTime() {
        return this.date.format(DateTimeFormatter.ofPattern("MMM d yyyy")) + " "
                + this.time.format(DateTimeFormatter.ofPattern("h.mm a"));
    }
```

Thanks!

**Comment by domlimm** [comment]
@jaegarpoon I've been trying to search online but to no avail.

My suggestion would be introducing a getter method to get your `fullDateTime` and returning `DateTime` instead of `String`. Essentially, testing your class variables i.e. description, datetime, taskType (D, E, T), etc. one at a time using getter methods in your test methods.

But this changes your test case entirely which is not really what we want though... 😭 

EDIT: Wondering if there's an equivalent to `equalsIgnoreCase(...)` when comes to testing. But defeats the purpose of testing :')

**Comment by damithc** [comment]
Also keep in mind that default date formats can be influenced by locale settings of the OS.

**Comment by sharpstorm** [comment]
> EDIT: Wondering if there's an equivalent to `equalsIgnoreCase(...)` when comes to testing. But defeats the purpose of testing :')

You could change the assert statement to this if case-sensitivity is not important in testing:
`assertTrue(actual.equalsIgnoreCase(expected))`

Though, do note that doing the assertion this way means that the error message output by JUnit is not as verbose as `assertEquals`.

**Comment by jaegarpoon** [comment]
Ok thank you so much for all your help! Understood that it is likely to be difference in settings, will be closing this issue :)
