### ISSUE TITLE
A-JUnit, cannot create package with the same name

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2103-AY2122S2/forum#125]
Hi guys, I was doing the A-JUnit increment right now when I encountered an issue. I know I'm weeks behind so any help is very much appreciated haha:)

Following step 4 of the instructions on https://se-education.org/guides/tutorials/junit.html, 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/92561253/152971364-caf5234a-8b1c-4056-a823-887cf157c4d7.png">
I tried creating the identical duke package in my src/test/java folder by _right clicking test/java folder -> new -> package_ but it doesn't let me name it because it already exists. Anything that I'm doing wrong here and maybe overlooking?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/92561253/152971722-3db0dfde-2c36-4cab-8ab5-a8d82d9a12cc.png">
 

Thank you so much in advance x!

**Comment by Shivang211** [comment]
Hi Varshney, looks like your test.iml file is not in the right folder. Please try putting it in the ip/test/java. :)

**Comment by kxshxsh** [comment]
Hi Gupta! Thanks for the suggestion, it works:)

**Comment by rajobasu** [comment]
Hi guys, seems like you are helping each other. good job! @Shivang211 Gupta, @kxshxsh Varshney
