### ISSUE TITLE
Proper way to display "bye" message and terminate GUI

### ISSUE THREAD

**Issue by YiHern-Lee** [nus-cs2103-AY2122S2/forum#127]
Hi everyone, after completing Level-10, I felt that I could improve the way that I terminate my GUI. My current implementation for terminating my GUI is to execute a `System.exit(0)` when I receive the "bye" message as a response from my chatbot. 
However, I noticed that the "bye" message is not displayed on the GUI before the GUI closes. 

I have followed the code provided in the JavaFX tutorial closely:
```java
    @FXML
    private void handleUserInput() throws InterruptedException {
        String input = userInput.getText();
        String response = stevie.getResponse(userInput.getText());
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, userImage),
                DialogBox.getStevieDialog(response, stevieImage)
        );
        userInput.clear();
        if (response.equals("Bye! Hope to see you again!")) {
            exit();
        }
    }
    private void exit() throws InterruptedException {
        Thread.sleep(1000);
        System.exit(0);
    }
```

I tried to pause the program for a couple of seconds before the `System.exit(0)`, however, I noticed that the message is only displayed on the GUI after the method `handleUserInput()` exits.

I have an idea to perhaps alter some field in `MainWindow.java`, and have a method execute upon the change in state. However, I am not too clear on how to implement it. 

Any inputs will be greatly appreciated. Thanks!

**Comment by domlimm** [comment]
Hello @YiHern-Lee ! I myself have not enhanced the `bye` command yet but there was a discussion on the enhancement that you can find here (#85) too. Maybe you could get some insights, perhaps a few different approaches to consider!

**Comment by RyanCheungJF** [comment]
Hi! You can look into [PauseTransition](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/PauseTransition.html) from JavaFx, it might help you in achieving your goal of sending the message first and then closing the window after a delay.

**Comment by YiHern-Lee** [comment]
Thanks for the helpful tips! @domlimm @RyanCheungJF 

I have managed to successfully implement PauseTransition. 😄
