### ISSUE TITLE
What to do if in a switch-case statement nothing needs to be done in the default branch?

### ISSUE THREAD

**Issue by Graphcalibur** [nus-cs2103-AY2122S2/forum#128]
See the question above. I only want the switch-case statement to specify how to handle certain cases. For the default branch, I don't need to do anything.

**Comment by lkldev** [comment]
Hi, based on the [textbook](https://nus-cs2103-ay2122s2.github.io/website/schedule/week5/topics.html#:~:text=you%20can%20use%20the%20default%20branch%20to%20detect%20errors%20(i.e.%20if%20execution%20reached%20the%20default%20branch%2C%20raise%20a%20suitable%20error).), you can use the default branch to raise error since there is no way it should reach the default case.

**Comment by Graphcalibur** [comment]
I don't want to throw an error though, because I do expect to the default branch to be reached. I just don't want to do anything in it.

**Comment by Jacky142857** [comment]
Maybe you can put one of the cases as default.

**Comment by damithc** [comment]
> I don't want to throw an error though, because I do expect to the default branch to be reached. I just don't want to do anything in it.

@Graphcalibur Perhaps leave it empty, with a comment to explain why nothing should be done by default?

**Comment by litone01** [comment]
Hi everyone, I'm an ex-student of the CS2103/T module dropping in to see if I can be of any help. 

For this question, maybe there can be another perspective to be considered, is whether this `switch-case` statement should be used, or it can be effectively refatored into another form that may be more suitable for the question to be solved. However, do note that this may not be directly related to the context of CS2103/T, i.e. by no means I am saying you should avoid using `switch-case` in CS2103/T, but rather for the general discussion of how to improve our code quality.

Some potential readings if you would like to read on about the alterantives of `switch-case` can be found here:
https://refactoring.guru/smells/switch-statements

Again, this is personal view, and only used for discussion purpose, and not suggesting whether there is a right or wrong answer:)
