### ISSUE TITLE
A-TextUiTesting: 'javac' file not found

### ISSUE THREAD

**Issue by declanleeler** [nus-cs2103-AY2122S2/forum#13]
Hello, I am using IntelliJ 2019.2, Java version 11.0.2.
When I run the runtest.sh file I receive this error:
<img width="756" alt="Screenshot 2022-01-20 at 4 03 48 PM" src="https://user-images.githubusercontent.com/50820543/150297678-0cbb35f5-2d58-44c8-ab68-d1a0b3cfc282.png">

I tried to run the file from my terminal and it gives me the same error even though the files are definitely in the same directory. 
<img width="930" alt="Screenshot 2022-01-20 at 4 04 53 PM" src="https://user-images.githubusercontent.com/50820543/150297812-7c5a11b3-a78b-4656-9a55-66565e356ec3.png">

I did search for some answers and came across a Stackoverflow post (https://stackoverflow.com/questions/20587840/javac-file-not-found-first-java-usage-javac-options-source-files/20587857) that says I need to set JRE path but im not sure what that means?

Hope someone can help me with this issue, thank you!

**Comment by domlimm** [comment]
Hi @declanleeler ! I suppose you're running from the CLI instead of using IntelliJ's run button. Check these 2 issues (#1 and #11) out. They might help.

Do you have any other java files other than `Duke.java`?

When I ran from the CLI instead of using IntelliJ, I had to be in the `text-ui-test` directory.

Inside the `runtest.sh`, Line 16 onwards:
```shell
# compile the code into the bin folder, terminates if error occurred
if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/*.java // This part!
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi
```

Maybe you could double check the directory of all your java files.

**Comment by damithc** [comment]
@declanleeler what happens if you use `javac .\Duke.java`?

**Comment by declanleeler** [comment]
Hi Prof @damithc , the same error occurs even when I use javac .\Duke.java
<img width="289" alt="Screenshot 2022-01-20 at 4 30 39 PM" src="https://user-images.githubusercontent.com/50820543/150301778-71e4c331-be8c-422d-bcf7-ca9a89df1b8d.png">

Hi @domlimm I tried IntelliJ and CLI but unfortunately I get the error on both. I tested out on Duke.java and *.java too but the error stays the same.

**Comment by domlimm** [comment]
@declanleeler may I ask how does your directory look like now (The current directory that you've been showing in this thread)? Is it the same as when you forked?

**Comment by declanleeler** [comment]
@domlimm Sure! Here is the directory. I added an out folder but other than that everything else is the same.
<img width="241" alt="Screenshot 2022-01-20 at 4 56 17 PM" src="https://user-images.githubusercontent.com/50820543/150305933-606549e4-82f5-468e-9a33-e16da9adc801.png">
w

**Comment by declanleeler** [comment]
@cheehongcw yup I am in the correct working directory.

**Comment by putaojuice** [comment]
Could it be due to a mac privacy setting issue? Like did you allow IntelliJ to access your folder where you put the ip project folder in?

**Comment by declanleeler** [comment]
IntelliJ was working fine up till this stag of the project so I don' think so since I am able to run the Java files from Intellij. The reason why I switched to terminal is because I was tracing through the javac file not found error in the shellscript and realized that I could not even run javac commands in my terminal.

**Comment by s7manth** [comment]
It might be due to the permissions set for the file `./runtest.sh`. Try changing the permissions by running this command in the terminal : `chmod +x ./path/to/runtest.sh`. Then you can move to the `text-ui-test` directory and directly run `./runtest.sh`. 

This worked for me on Mac.

**Comment by punnyhuimin** [comment]
Hi, could you check that java version 11 is set in your terminal? You can try following [this link](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos) to see how to go about doing so.

 If all else fails you might want to reinstall java 11.

**Comment by declanleeler** [comment]
@putaojuice and @s7manth I changed the permission but it didn't work. 
I have deleted all java versions and reinstalled java 11. I can now javac files in terminal but the shellscript error remains.

**Comment by lzan98** [comment]
Hi

Seeing that you are using zsh, maybe the following could be of help:

https://stackoverflow.com/questions/10230293/java-commands-runs-on-bash-fails-on-zsh

Perhaps you could try using IntelliJ's terminal or update the cp directory instead? Good luck.

**Comment by lzan98** [comment]
Hi there

I believe it is an issue with the way you run the .sh file. 

What you should do is to navigate to your text-ui-test directory in terminal (either in IntelliJ or Mac's default terminal). When in the directory, run ./test.sh

If you get a permission error, use the fix s7manth mentioned.

(This should work, because I tested by typing the exact same command as you shown in your original post and got the same error)

**Comment by declanleeler** [comment]
> Hi there
> 
> I believe it is an issue with the way you run the .sh file.
> 
> What you should do is to navigate to your text-ui-test directory in terminal (either in IntelliJ or Mac's default terminal). When in the directory, run the following:
> 
> `./runtest.sh`
> 
> If you get a permission error, use the fix s7manth mentioned.

Thanks so much @lzan98 and @s7manth that worked !

**Comment by damithc** [comment]
Good to hear this got resolved. Thanks everyone who pitched in.
