### ISSUE TITLE
Built MainWindow.fxml does not recognise URIs

### ISSUE THREAD

**Issue by ianfromdover** [nus-cs2103-AY2122S2/forum#132]
I am facing a Launcher.main() fail Caused by: java.lang.reflect.InvocationTargetException. The FXML Loader was not able to read the nodes on my stage.
![Screenshot 2022-02-10 at 9 03 08 PM](https://user-images.githubusercontent.com/62384984/153415534-e45b3f6d-ea67-439e-a826-dce8313aa0a4.png)
![Screenshot 2022-02-10 at 9 02 33 PM](https://user-images.githubusercontent.com/62384984/153415551-0f19489d-3a5a-469e-ad9e-1ac28ca5e2f8.png)
![Screenshot 2022-02-10 at 9 02 16 PM](https://user-images.githubusercontent.com/62384984/153415585-a1935081-f63e-4bc6-bed9-c8b07fe1853e.png)

### Attempts at resolving
Upon looking through my files, I realised that IntelliJ is referencing the built `MainWindow.fxml` in the build folder `ip/build/resources/main/view/`, which is identical to the `MainWindow.fxml` provided in the [JavaFX tutorial part 4](https://se-education.org/guides/tutorials/javaFxPart4.html) , which is identical to my `MainWindow.fxml` in the source folder `ip/src/main/resources/view/`.

However, IntelliJ does not recognise the URIs `xmlns="http://javafx.com/javafx/8.0.171" xmlns:fx="http://javafx.com/fxml/1"` inside the `MainWindow.fxml`in the build folder. Strangely, it could recognise the exact same URIs in the file in my source folder. 

MainWindow.fxml in the source folder
![MainWindow.fxml in the source folder](https://user-images.githubusercontent.com/62384984/153415618-b0ce2d45-dd05-40ab-b4b9-2c1ffd54b155.png)
MainWindow.fxml in the build folder
![MainWindow.fxml in the build folder](https://user-images.githubusercontent.com/62384984/153415643-2bc1f026-fc88-4d42-8685-7d3e89b454d5.png)

My external frameworks settings show no problems, and I am stumped.
![Screenshot 2022-02-10 at 9 03 27 PM](https://user-images.githubusercontent.com/62384984/153416134-28e89ee6-3bda-41f6-949d-cdd7b4fe8c8d.png)

I was unable to find any help online for the past 2h. Please let me know if you have a solution, it will be greatly appreciated.

**Comment by ianfromdover** [comment]
Solved. I placed the images in the wrong directory.

**Comment by damithc** [comment]
> I am facing a Launcher.main() fail Caused by: java.lang.reflect.InvocationTargetException. The FXML Loader was not able to read the nodes on my stage.
> ![Screenshot 2022-02-10 at 9 03 08 PM](https://user-images.githubusercontent.com/62384984/153415534-e45b3f6d-ea67-439e-a826-dce8313aa0a4.png)

@ian-from-dover Also share what you see when you click on the NullPointerException shown in this screenshot, in case it is relevant.

**Comment by ianfromdover** [comment]
I am not able to roll back to the version with the error, but I recall that the NullPointerException was thrown because the program was not able to locate the AnchorPane object to be loaded from the fxml.
