### ISSUE TITLE
Tagging required in order to create new release

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#134]
Hi everyone,

I tried to create a new FAT Jar file using gradle and tried to create a new release for it. However, I realized that tagging is required in order to publish. Hence, I decided to create a new tag A-NewJar that is not required. I am just wondering if creating this new tag will affect the scripts that detect the tags for my repo? Was hoping if prof @damithc or anyone can advise...

Thank you!

![image](https://user-images.githubusercontent.com/83687861/153533596-6a1d99f3-9f79-4ec7-9954-da19c660323e.png)

**Comment by damithc** [comment]
@yuqitanyq it's fine to have extra tags. It will not affect the script.

**Comment by yuqitanyq** [comment]
Okay got it! Thanks prof!
