### ISSUE TITLE
Correct format for Confirmation Messages

### ISSUE THREAD

**Issue by AAlghrairy** [nus-cs2103-AY2122S2/forum#136]
Let's say for instance I have a method that, after it processes, I wish to send a confirmation message to the user that this particular process has finished.

Is it better practice to separate the processing and confirmation,

```
processCommand(Command c);
return confirmProcess(Command c);
```

or combine the processing and confirmation and return the initial method:

```
return processCommand(Command c);
```

If the latter is preferable, what would be an appropriate name for the method that would abide with the Coding Standard?

**Comment by putaojuice** [comment]
IMO the first way is better as we should try to make our function single responsibility as much as possible Even if there is a need for a method to process multiple things sequentially, we could apply SLAP.

Also, if you choose to go with the second way, your method name might need to be something like `processCommandAndConfirmation()` which feels a bit long for me, might be misleading too if you don't name it properly.

**Comment by damithc** [comment]
You can also take how AB3 handles command processing as another reference point.

Somewhat related https://en.wikipedia.org/wiki/Command%E2%80%93query_separation

**Comment by AAlghrairy** [comment]
Thank for very much for your responses @putaojuice and @damithc
