### ISSUE TITLE
What do you guys write for the git tag message?

### ISSUE THREAD

**Issue by jbkim1999** [nus-cs2103-AY2122S2/forum#138]
After using CLI `git tag -a "tagName"`, it always redirects to write a message for tag.

So far I have been just writing `Implement "tagName"`, but is there a convention to write a tag message as well?

**Comment by damithc** [comment]
@jbkim1999 Good question. Let's see if someone else can share how to create a tag that doesn't need a message.

**Comment by bakano98** [comment]
You can just do `git tag "tagname"` and you won't have to add a message for the tag. If you want to add a tag to a specific commit, you'll have to add the commit hash 😄

**Comment by jbkim1999** [comment]
Thanks, @bakano98! 

After googling the difference between mine and your command, I found that I was using an annotated tag, as opposed to a lightweight tag (which does not need the additional `-a`).

More information here for those who want to know more: https://git-scm.com/book/en/v2/Git-Basics-Tagging

But I do wonder what to write for the tag message if I were to keep using annotated tags 🧐 
My assumption is that it would be very similar to a full commit message...?

**Comment by damithc** [comment]
> But I do wonder what to write for the tag message if I were to keep using annotated tags 🧐
> My assumption is that it would be very similar to a full commit message...?

@jbkim1999 It is indeed a good point to explore further. The module does not impose any convention on such messages though.

**Comment by jbkim1999** [comment]
Thanks for the response, prof @damithc.

Maybe I can come back to this once I find some resources regarding the tag message!
