### ISSUE TITLE
Clarification -- tP Week 6 Task 5 Tutorial 2

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#139]
Hi Prof Damith, 

On behalf of my team, we wanted to clarify if Tutorial 2 of Week 6's [Task 5](https://nus-cs2103-ay2122s2.github.io/website/schedule/week6/project.html#5-get-familiar-with-the-code-base) is to be completed by 1 person from the team, a few persons from the team or everyone in the team? 

Thank you 😄

**Comment by damithc** [comment]
@waffledood it is to be done everyone, as _everyone_ needs to learn the codebase.

**Comment by waffledood** [comment]
got it, thanks Prof!
