### ISSUE TITLE
Unable to access other classes inside java folder

### ISSUE THREAD

**Issue by tanweien** [nus-cs2103-AY2122S2/forum#14]
I have 2 other classes in ip/src/java, Task and TaskList. I am able to call methods from both classes in the main Duke class. However, I cannot call Task methods in TaskList and vice versa (cannot resolve method). String.format(...) also does not work in both Task and TaskList for some reason. Does anyone know how to resolve this issue? Thank you. 

![Screenshot 2022-01-20 at 5 55 31 PM](https://user-images.githubusercontent.com/85757107/150315731-dc4dcdd3-8a81-40db-be71-1ab073ab1ab9.png)
![Screenshot 2022-01-20 at 5 55 54 PM](https://user-images.githubusercontent.com/85757107/150315795-fa5b4da8-d75d-41e0-adde-be86fc290140.png)

**Comment by Spyobird** [comment]
Perhaps this may help you.
https://stackoverflow.com/questions/22795894/cannot-resolve-method-in-java/22796097
