### ISSUE TITLE
Java CI workflow run keeps failing due to issues related to checkstyle

### ISSUE THREAD

**Issue by yunbinmo** [nus-cs2103-AY2122S2/forum#141]
Hi all,

I followed the steps [here](https://se-education.org/guides/tutorials/githubActions.html) to add the `.yml` file into my repo to set up CI for my project, I encountered the following error when I tried to run the workflow:
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/77217780/153704572-dfe755b6-48bd-4f9c-98b9-36c875035e94.png">

Looks like something is wrong with the checkstyle but I cannot figure out why, here's my checkstyle import in build.gradle file:
```Java
checkstyle {
    toolVersion = '8.29'
}
```

I've been searching online but can't seem to find a way to solve this, appreciate if anyone could help!

**Comment by damithc** [comment]
Hint: a file checkstyle needs is missing in your fork.

Are you able to run checkstyle locally? If yes, you have not pushed that file to the fork. If no, you are missing that file even in your local environment.

**Comment by yunbinmo** [comment]
> Hint: a file checkstyle needs is missing in your fork.
> 
> Are you able to run checkstyle locally? If yes, you have not pushed that file to the fork. If no, you are missing that file even in your local environment.

Thank you prof! The checkstyle files were indeed missing in my fork. I noticed that I accidentally excluded checkstyle related files from revision control before, after updating the `.gitignore` file and pushed again, the CI workflow runs without error.
