### ISSUE TITLE
How to get Duke to speak first? 

### ISSUE THREAD

**Issue by isabelteo** [nus-cs2103-AY2122S2/forum#142]
I am using IntelliJ community 2021.1.2 , Windows and JDK 11. I am using JavaFx Version 17.0.2. 

I couldn't really find a similar issue yet, do let me know if this issue was raised already! I am wondering if anyone has managed to get Duke to speak first and could give tips on how that was achieved? I don't really understand how to achieve Duke greeting the user first to e.g. introduce the command formats 

Here is the link to my branch if you need: https://github.com/isabelteo/ip/tree/branch-BCD-extension

Thank you so much!!

**Comment by lzan98** [comment]
Hi! Assuming you are referring to the GUI, what I did was to add the following line in the `initialise()` method of `MainWindow`.

```
initialise() {
     ... // existing code
     dialogContainer.getChildren()
         .add(DialogBox.getDukeDialog("Your welcome message here", dukeImage))
}
```

You could give it a try and see if it works 😄

**Comment by isabelteo** [comment]
@lzan98  Thanks so much!! It worked 💯
