### ISSUE TITLE
How do you resolve commit not belonging to any branch in repo?

### ISSUE THREAD

**Issue by brian16600** [nus-cs2103-AY2122S2/forum#143]
![image](https://user-images.githubusercontent.com/83962069/153720144-978c77f1-a1e4-4885-a012-4e997744c43f.png)
Some of my previous commits have this issue where only I'm able to view the commit with the tag. How do I resolve this?

**Comment by damithc** [comment]
@brian16600 Have you pushed the commit and the branches the commit was in? Can you give the link to one such commit?

**Comment by brian16600** [comment]
@damithc  Yes, I have pushed the commit, however I think when I pushed it previously it belonged to a detached head
https://github.com/brian16600/ip/commit/b8bfabe289c26c10b64918400aede2af923e3b23

**Comment by AllardQuek** [comment]
Hey @brian16600, have you tried checking out a new branch (from your current commit or the commit you want to push to a branch) and pushing that new branch to GitHub?

**Comment by AllardQuek** [comment]
As an aside, with regards to your commit messages, try and use the ["imperative mood"](https://se-education.org/guides/conventions/git.html) instead (i.e. "Add file" instead of "Added file") 🙂

**Comment by tlylt** [comment]
Hi @brian16600, according to this [answer to a similar question](https://github.community/t/github-tells-me-the-commit-does-not-belong-to-any-branch-while-its-not/156393/2?u=tlylt):
> My best guess here is that your were trying to access the old commit, i.e. via the its hash before the rebase operation. Beware that any history rewrite operation (commit amending, force pushes, rebasing, etc.) will change the hash of the commits involved. Every commit has a unique hash, and you can’t edit a commit without changing its hash.

> So, if 91d64ce was the original hash of the commit that you edited, it’s correct that GitHub (and Git) report that commit as not being part of any branch, since it’s now deleted and replaced by a new commit — even if you only changed the commit message, the whole commit was replaced by a new one, which is an edited version of the original.

> You should still be able to see the original 91d64ce commit in the RefLog (locally), which stores deleted elements for undo operations.

Perhaps you have accidentally edited the git history. 

Anyways, what do you mean by "resolve commit"?

**Comment by takufunkai** [comment]
I agree that you might've set a tag for a specific commit, then removed it somehow from your history. That could be why this commit does not exist on your repository.

I suggest you delete the tag for the missing commit, then tag an existing commit in your main branch that reflects the correct work required for the given increment tag to resolve the issue.
