### ISSUE TITLE
Not sure why the dialogbox is not expanding for some windows users

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#145]
Hey everyone, 

I did the set min-height to USE_PREF_SIZE, here in my dialogbox.java, [link](https://github.com/yuqitanyq/ip/tree/master/src/main/java/duke/ui)

The issue was resolved on mac, (I am a mac user). Screenshot attached below:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/83687861/153738249-0a8f079f-2991-4d41-806a-90d19ac536f6.png">

However, on windows,
the issue still seems to persist after asking my friends to test it out. I was wondering if there is a way for it to make the dialog box work for both windows and mac.

![2022-02-13 12 13 59](https://user-images.githubusercontent.com/83687861/153738325-1400e46f-1eeb-4138-8c00-37b9476ecdd7.jpg)

Apparently, this issue happens for some windows users, another friend that just helped me to test out said it works well...
So I'm not really sure if the problem is with my code or with the operating system for windows...
![2022-02-13 12 23 26](https://user-images.githubusercontent.com/83687861/153738522-39ad316c-7bd6-4447-8e25-504119280914.jpg)
 
This is my jar file:
[YQ Chatbot(Final).jar.zip](https://github.com/nus-cs2103-AY2122S2/forum/files/8054953/YQ.Chatbot.Final.jar.zip)

Appreciate it if anyone could help!

prof @damithc This is the new thread, thanks for alerting me that the previous thread #88 has been closed!

**Comment by damithc** [comment]
Tagging a few other students (randomly selected) who have completed related increments, in case they can pitch in: @Geralddtan @Ashuh @declanleeler @onefangg @punnyhuimin @darshan152 @TeddYE @hieunm1821 @DALIN-Prog @limweiliang

Perhaps Windows users can help check if the error is reproducible on their computers?

**Comment by onefangg** [comment]
Hi, currently using Windows 10 Home, version 10.0.19043

The chat message is expanding properly on my end as shown: 
![image](https://user-images.githubusercontent.com/46132040/153741830-12c30263-57d0-4011-8861-d0bedcef04ee.png)

**Comment by darshan152** [comment]
Im unable to replicate the issue as well, 
![image](https://user-images.githubusercontent.com/59141335/153742281-e6433200-359c-49e8-b316-b033e5dd0aa4.png)

Maybe you can double check the java version on the computer with the issue, or try ask your friend to try again with an updated jar file

**Comment by 9teMare** [comment]
Encountered this issue a few weeks ago on my Windows machine, I believe it has to do with the **font** you are using. 
Notice in your screenshot which the issue appears, the font is different from everyone else' screenshot. The reason why Mac users (and everyone else who tested your program) do not have this problem, is probably because somehow the font is being configured back to the default font. If you change the font back to the default one (I think it's called `Standard` if I'm not wrong), the issue should go away. 
Not too sure why this is the case, probably someone else can explain the reason behind this :)

**Comment by yuqitanyq** [comment]
Okay since it works for most of the people that tested, I think it should be ok. @9teMare I think there is no such font family for Standard though... but I will just change the font for the button to System. Thanks!

**Comment by 9teMare** [comment]
@yuqitanyq Ah yes the font is called System, my mistake.

**Comment by hieunm1821** [comment]
I also have this problem and i am using ubuntu-linux
I think you can try set minHeight in label component in dialogbox in the fxml file to -Infinity.
```
<Label fx:id="dialog" text="Label" wrapText="true" minHeight="-Infinity" />
```

**Comment by cheehongw** [comment]
Managed to encounter the bug on my windows machine. I don't think it is an issue with the font, but an issue with how `scrollPane` handles nodes with variable heights.

Large text labels like those from executing the command `list` have their heights automatically resized when there are too many `dialogboxes` and the `scrollPane` kicks in.

The fix by \@hieunm1821 worked for me.

**Comment by yuqitanyq** [comment]
okay thank you all for your inputs!
