### ISSUE TITLE
tP: Naming of the team project repo: team repo or leave as is?

### ISSUE THREAD

**Issue by ryantanlien** [nus-cs2103-AY2122S2/forum#146]
What should be the correct name of the repo for our team project? Should we leave it as is which is currently tp or should we change it to _team repo_? (it was mentioned in italics in the set-up guide)

**Comment by pyk595** [comment]
After you set up your team organisation you can just fork it the tp repo directly to the organisation, no need to change it. The guide calls it team repo for easy referencing of the tp repo.

**Comment by damithc** [comment]
> After you set up your team organisation you can just fork it the tp repo directly to the organisation, no need to change it. The guide calls it team repo for easy referencing of the tp repo.

@pyk595 is correct. Keep it as `tp`
