### ISSUE TITLE
Modifying README.md after submitting final version

### ISSUE THREAD

**Issue by AAlghrairy** [nus-cs2103-AY2122S2/forum#147]
Would there be an complications if one decides to modify the docs/README.md file after having released the "final version" of the JAR file? Also, is it better to edit the file on Github or using an IDE (followed by committing)?

**Comment by domlimm** [comment]
Hello @AAlghrairy , I highly doubt it! I've seen some of my peers that have already done that!

**Comment by damithc** [comment]
@AAlghrairy it's fine, as long as the documentation matches the JAR file behavior. You can also update the JAR file if you want.

**Comment by AAlghrairy** [comment]
Thanks for the inputs @domlimm and @damithc.
