### ISSUE TITLE
Debugging with JavaFX

### ISSUE THREAD

**Issue by sbhbenjamin** [nus-cs2103-AY2122S2/forum#148]
Hi, I am currently following the [Tracing Code Tutorial for Week 6](https://nus-cs2103-ay2122s2.github.io/tp/tutorials/TracingCode.html). Under the **Tracing the execution path** segment, the tutorial mentions that we should start the debugging session, using `Run` > `Debug Main`. Then, it says that:
> _When the GUI appears_, `enter edit 1 n/Alice Yeoh` into the command box and press `Enter`.

However, I don't see the GUI appearing in debug mode. The GUI only launches when I run `Main` normally.

Can I ask what I can do to get the launcher to run in debug mode? Thank you!

**Comment by damithc** [comment]
@sbhbenjamin Probably depends on where you put the first break point? If the break point is in a statement that is _before_ the GUI shows up, it will not appear at first.

**Comment by sbhbenjamin** [comment]
Thank you prof, that really helps!
