### ISSUE TITLE
Created tag instead of branch

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#149]
Basically, instead of branching out for these parts, I just created tags for them therefore all of them are red. 
![image](https://user-images.githubusercontent.com/56862300/153837280-e69cbd3d-a036-4cea-a605-f9763fb12f84.png)

May I know what I can do? This is how it looks like on my SourceTree. But there is no doubt that I do know how and the reason why we need to create branches (I created an additional branch to seperately learn how to create pie chart on another window, tested it until it works and then merged into master).
![image](https://user-images.githubusercontent.com/56862300/153837410-a8754cd4-bc34-4927-a0ae-a3f5f963bfdc.png)

**Comment by damithc** [comment]
@hsiaojietng in terms of the dashboard, it will turn green as long as there is a merged branch with the expected name. You are free to turn them green using new branches if you wish.
FYI, there is more to branching than just creating and merging branches e.g., dealing with merge conflicts, creating branch-based PRs etc. and different iP increments were supposed to focus on those different things.
