### ISSUE TITLE
SourceTree do not allow me to Commit

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#150]
**Not sure why, and I just modify some code in the project, but I'm virtually unable to click to commit as shown below.**
![image](https://user-images.githubusercontent.com/56862300/153843299-1c2df88a-0395-48e3-bf93-025d0ab8f10b.png)

**It also shows there is are things to be commited, so I'm confused.**
![image](https://user-images.githubusercontent.com/56862300/153843424-136954c6-1700-499b-b160-a96924d8b777.png)

**Please let me know how I can go about solving this? Most online sources just talks about how they click on "Commit" but SourceTree does not commit, which isn't my case.**

**Comment by lkldev** [comment]
Hi, make sure you have selected files to stage. You should be able to see staged files and unstaged files. I suspect all your files are unstage at the moment, hence you will need to stage them first

**Comment by hsiaojietng** [comment]
omg I didn't realise I accidentally clicked on 
![image](https://user-images.githubusercontent.com/56862300/153849907-0635a908-1e9b-4350-9c9a-2af6ec68206f.png)
I got it now, thanks alot!
