### ISSUE TITLE
Implementing BCD-Extension as GUI

### ISSUE THREAD

**Issue by takufunkai** [nus-cs2103-AY2122S2/forum#152]
For `BCD-Extension` I chose `D-Clients`. My clients module has create and list functionalities, but no save to disk, delete, or update functionalities. I implemented it as a fully GUI component with no commands for the module.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/15829042/153991766-d7dcb629-e7bf-42ce-bee7-8b9abcc29eda.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/15829042/153991794-1cf308c6-3944-4325-8a44-74badefacc6b.png">

I'm wondering if this is acceptable or we should at least have some CLI-related functionalities for our implementation?

**Comment by damithc** [comment]
@takufunkai It's fine. Unlike the tP, the iP doesn't insist on a CLI-first approach.

**Comment by takufunkai** [comment]
@damithc Thanks prof, closing the issue now.
