### ISSUE TITLE
JavaFx runtime components missing, and are required to run this application.

### ISSUE THREAD

**Issue by aditi2313** [nus-cs2103-AY2122S2/forum#153]
My jar file seems to run fine on my M1 Mac but there seems to be an issue when it's run on Windows.
Not sure how to fix a "JavaFx runtime components missing, and are required to run this application." error. The GUI doesn't seem to be working on Windows OS either

![photo_2022-02-15 12 24 12](https://user-images.githubusercontent.com/52269537/153992333-4a6b2707-17b0-4e9b-a17b-e4e6fdbcc08d.jpeg)

**Comment by jbkim1999** [comment]
Hi,

Sorry that my answer might not be directly based on that error message, but try to check

1. That your .jar file is indeed a fat .jar file (that will include JavaFX libraries)
2. That you have followed the advisory given to M1 Mac users regarding the use of the Azul build of OpenJDK 11 version

**Comment by AAlghrairy** [comment]
If the .jar file is less than 10 MB, then you may forgotten to build a fat .jar file, as @jbkim1999 said.

On Gradle, make sure you run the command "gradle clean shadowJar" to build a fat .jar file, which will include all JavaFX libraries.

**Comment by yl-ang** [comment]
Hi, managed to solve the issue with @aditi2313, in build.gradle file, remember to change the following fields in it:
```
...
application {
    mainClassName = "Main" // change it to point to your Launcher class i.e "duke.Launcher"
}
...
```

**Comment by manu2002g** [comment]
Hi,

Not sure if this is the best way to fix this, but I had the exact same issue as you and following the below steps worked.

1. Use a Launcher class that doesn't extend from Application [(here)](url)
2. Make sure mainClassName in build.gradle is set to "duke.Launcher"
3. Make sure you build.gradle has the necessary dependencies as indicated [here](https://se-education.org/guides/tutorials/gradle.html)
4. Run gradle clean shadowJar. Your file should be more than 10mb if it is a fat jar file

Hope this helps!

**Comment by litone01** [comment]
Hi @aditi2313, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). 
Just a gentle reminder to close this issue if the problem has been resolved. If not resolved yet, please post a comment explaining which part of the problem/question remains unresolved, and we will see how we can help to resolve the issue:)
