### ISSUE TITLE
Can run in intellij but cannot run as a jar file

### ISSUE THREAD

**Issue by xpzmichael** [nus-cs2103-AY2122S2/forum#154]
My ip **can run successfully in intellij** (by clicking the run button)
But the jar file I built (with gradlew shadowJar) cannot be opened by clicking it.

Then I try to run it in terminal, it shows 
`
XPZ-MacBook-Pro:jar peizhexu$ java -jar duke.jar
Error: Could not find or load main class Main
Caused by: java.lang.ClassNotFoundException: Main
`
&nbsp;
I downloaded other people's jar file and I can run them successfully, But **within the same directory**, I cannot run mine.
&nbsp;
I checked and compared my [Launcher class](https://github.com/xpzmichael/ip/tree/master/src/main/java/duke) and [Main class](https://github.com/xpzmichael/ip/tree/master/src/main/java/duke) to the others' code and did not find any big difference.
&nbsp;
Anyone knows what's the issue? Thanks!

**Comment by lkldev** [comment]
Hi, you will need to modify your `build.gradle` to point to the right `mainClassName`. You can take a look at this issue #104. Hope this helps :)

**Comment by xpzmichael** [comment]
@lkldev Thanks! I solved the `mainClassName` in `build.gradle` and now it can run in terminal, but it still cannot be launched by double clicking it.🥲

**Comment by domlimm** [comment]
Hello @xpzmichael! May I ask where are you trying to double click from? Are you trying to do it in IntelliJ?

**Comment by xpzmichael** [comment]
@domlimm Oh I mean in the folder where I put my jar file. I can open it in intellij or in terminal using `java -jar`, but I cannot launch it in my folder(finder) with mouse clicking the file or `right click` and `open with` `JavaLauncher(default)`.
