### ISSUE TITLE
[MacOS] Running Duke.jar via Terminal vs Double Click

### ISSUE THREAD

**Issue by vishandi** [nus-cs2103-AY2122S2/forum#155]
Hi! I noticed there are few issues addressing this issue, but I think my problem is different, hence this new issue. 

I use MacOS, and the problem I encountered is when running duke.jar by double clicking, **no** ./data/TaskList.txt file is created anywhere (see first picture), I suspected that it means Duke did not save my tasks, but apparently it saved it somewhere, but not on ./data/TaskList.txt, because when I restarted the Duke, it shows that I have the task that I previously added (see second picture). 
<br>
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77654963/154023770-67b40131-8ca1-4189-8fe3-c08f6a1667be.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77654963/154023990-fe3aade0-449f-4214-852e-b68210659f39.png">
<br> 
However, when I run duke.jar using terminal, it did create the ./data/TaskList.txt. 
<br>
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77654963/154024398-4930a75b-9496-4428-ab18-76a420b5f8ea.png">
<br>
Apparently, I have two "versions" of Duke going with different Storage file (left: double click, right: Terminal). Could anyone give me a solution to make both of these ways in running duke.jar perform similarly? 
<br>
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77654963/154024855-9efa9b42-64e7-4013-adfe-bee4ee09fee3.png">
<br>
I asked my friend who use Windows to try my duke.jar, and it works perfectly fine in their laptop.

**Comment by damithc** [comment]
@vishandi see if this thread (from a previous semester) helps https://github.com/nus-cs2103-AY2122S1/forum/issues/221

**Comment by vishandi** [comment]
Thank you very much, Prof! Yes, it solve the problem! 

Info: Anyone who encountered the same problem, just follow the instruction of the last message on the thread that Prof mentioned.

**Comment by michaelseyo** [comment]
Hi @vishandi is your java file that you located also under the zulu-11.jdk/Contents/Home/bin/java ? I'm using an M1 mac and after right clicking it I located the java launcher to be in that directory and have added it to the full disk access but somehow the application still behaves different when double-clicked and run in terminal with java -jar

![Screenshot 2022-02-15 at 9 59 34 PM](https://user-images.githubusercontent.com/76872115/154077259-efc81459-037d-4537-a75d-312000218029.png)

**Comment by vishandi** [comment]
Hi @michaelseyo! I think the application you want to find is exactly JavaLauncher and it is located in `/System/Library/CoreServices`. This folder is not accessible from System Preferences (at least in my case), so what you can do is you go to `/System/Library/` (via Finder's Go To Folder... or Shift + Command + G), then you make an alias of the CoreServices folder (see screenshot)
<br>
<img width="800" alt="image" src="https://user-images.githubusercontent.com/77654963/154078288-3c2ce1aa-8ff1-4a79-93b0-d60638f440d0.png">
<br>
Then you can select the JavaLauncher from the System Preference as the alias will be on Desktop and accessible from System Preference.

Hope this helps!

**Comment by michaelseyo** [comment]
@vishandi ohh thank you so much! It works great now :)
