### ISSUE TITLE
Cannot launch the application by clicking.

### ISSUE THREAD

**Issue by xpzmichael** [nus-cs2103-AY2122S2/forum#156]
My ip **can run successfully in intellij** (by clicking the run button)
My jar file **can run in terminal with** `java -jar duke.jar`
But I **cannot** launch the application by clicking it in my folder (or `right click` and chose `open`).

&nbsp;
I downloaded other people's jar file and I can launch them successfully, But **within the same directory**, I cannot launch mine.
&nbsp;
I checked and compared my [Launcher class](https://github.com/xpzmichael/ip/tree/master/src/main/java/duke) and [Main class](https://github.com/xpzmichael/ip/tree/master/src/main/java/duke) to the others' code and did not find any big difference.
&nbsp;
Anyone knows what's the issue? Thanks!

**Comment by domlimm** [comment]
Hello again @xpzmichael, I'm on Windows and I just tried your project. I ran `shadowJar` from the `gradle` panel and it works (i.e. Clicking from inside the folder itself)! That's really odd...

I check your `build.gradle` and this is also correct:
```
application {
    mainClassName = "duke.Launcher" // the path here
}
```

Maybe someone on macOS can chime in..

**Comment by declanleeler** [comment]
Hi @xpzmichael. I also have the same issue as you. When I double click JAR files from others, there is an error, but when I run it through the terminal everything works perfectly. 
Not sure if this helps, but I referred back to the guide here, [Working with JAR files @SE-EDU/guides](https://se-education.org/guides/tutorials/jar.html), and it does mention that "the fool-proof way to run a jar file is to use the java -jar command e.g., java -jar foo.jar launches the foo.jar file". I interpreted this to mean that the double clicking issue is not a serious one as it's more important to ensure that the jar files can be run through the terminal.

**Comment by damithc** [comment]
> Not sure if this helps, but I referred back to the guide here, [Working with JAR files @SE-EDU/guides](https://se-education.org/guides/tutorials/jar.html), and it does mention that "the fool-proof way to run a jar file is to use the java -jar command e.g., java -jar foo.jar launches the foo.jar file". I interpreted this to mean that the double clicking issue is not a serious one as it's more important to ensure that the jar files can be run through the terminal.

Yes, as far as the module is concerned, it is good enough if the JAR file can be run using the `java -jar` command.

**Comment by xpzmichael** [comment]
@everyone Thank you so much! I updated my system to MacOS Monterey 12.2.1 and finally it can be launched!✌️✌️✌️
