### ISSUE TITLE
Unable to Build Jar

### ISSUE THREAD

**Issue by isabelteo** [nus-cs2103-AY2122S2/forum#157]
I am using IntelliJ community 2021.1.2 , Windows and JDK 11. I am using JavaFx Version 17.0.2. 

I tried to build my JAR with Gradle (with [this tutorial](https://www.jetbrains.com/help/idea/getting-started-with-gradle.html#deploy_gradle))but there was an issue with my checkstyle file. I tried to fix my checkstyle version (by following the [SEguide tutorial](https://se-education.org/guides/tutorials/checkstyle.html) on checkstyle) but I couldn't as well because of the same error when building with Gradle

```java
TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard
```
Even when I tried to shift the LineLength module out, it just leads to a new error 

```java
Property 'allowMissingThrowsTags' does not exist, please check the documentation
```

I tried to build using Intellij Project structure --> Artifacts to build a JAR file but there is an error when I try to run the jar file:
![image](https://user-images.githubusercontent.com/83572953/154125892-de82598c-6f0d-4ee3-a931-ed8482acbf81.png)

```java
no main manifest attribute, in NoFace.jar
```
I looked the problem up, but seems like there is a MANIFEST.MF in resources folder already and I updated the main class in it to be launcher.java so I'm not really sure how to fix it

Here is a branch of my code: https://github.com/isabelteo/ip/tree/branch-BuildJar

Thank you!!

**Comment by damithc** [comment]
@isabelteo You should use gradle to build the JAR file, which means focus on fixing the checkstyle error first. Ensure the checkstyle version is correct. You can compare your build.gradle and checkstyle config file with others to see if you are doing something differently.

**Comment by isabelteo** [comment]
@damithc thank u! I did that after referecning some of the tagged iP's and fixed the issue
