### ISSUE TITLE
CI Problem with tP PR to main repo

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#158]
As can be seen below, the CI check for macOS was cancelled when I created a PR from my team repo to Seedu's repo. I am unsure why this happened as the same commit passed all CI on my team repo. Also, the only thing that I've made is to change "AB-3" to my project's name.

![image](https://user-images.githubusercontent.com/71639142/154249248-d4250dbe-b954-4815-92e2-493598600060.png)

**Comment by damithc** [comment]
@bingsen0806 perhaps you can give the link to the PR here so that others can easily go have a look?

**Comment by bingsen0806** [comment]
https://github.com/nus-cs2103-AY2122S2/tp/pull/36

**Comment by bingsen0806** [comment]
I think the CI test was cancelled, not failed. I suspect it will pass if the action workflow is re-run but I do not have permission to run it since it's from seedu's repo

**Comment by damithc** [comment]
@bingsen0806 I restarted the CI. If a similar thing happens in future, you can wait till the next CI run (i.e., at the next update to the master branch) to see if it rectify itself.
