### ISSUE TITLE
gradle run just keeps executing for ages

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2103-AY2122S2/forum#160]
Hello! My program was working well till yesterday, until I added the JavaFX plugins to my build.gradle file. Today, as I ran my program, the building and running kept executing for over 4 minutes. I ran `gradle clean shadowJar` on my terminal so that I could have the JavaFX Libraries, I restarted my IDE too but there was no change in the time taken to run my iP program. I then read somewhere online about someone who had solved the issue by disabling plugins, restarting and then enabling them again. So all I did was commented-out all the JavaFX plug ins in build.gradle to revert back to the previous, working state. But that doesn't seem to work anymore either (even after restarting my IDE). Screenshot is attached below.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/92561253/154413814-e6282715-1a61-418d-bb83-a00a4914c340.png">

I tried running `./gradlew run` through the terminal which at least allows me to see the duke logo and interact with the program but the status bar is stuck at 75% execution and simply doesn't seem right
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92561253/154416118-3126ffc0-9c9f-46f0-8b21-0890012d5bca.png">

Please help me out:') Thanks in advance!

**Comment by damithc** [comment]
@kxshxsh it's normal for Gradle to report less than 100% if the code is still running. That is, Gradle is still not finished with the `run` task, and hence, not 100% done. It will go to 100% after you exit Duke.

For the other problem, if it is still not resolved, perhaps you can push the latest code to a branch and post the link here?

**Comment by kxshxsh** [comment]
This was an issue local to my IDE and has been solved:)) Thank you!
