### ISSUE TITLE
JNI error after creating a fat JAR file

### ISSUE THREAD

**Issue by Justinnje** [nus-cs2103-AY2122S2/forum#161]
![image](https://user-images.githubusercontent.com/77234960/154446984-b98e39d2-b890-473e-a091-770918f31971.png)

Hii, 

I need some help. After creating the fat JAR file, i tried to open it only to receive this error message.

I changed my mainClassName to be "duke.Launcher" and ran "gradlew clean shadowJar" as instructed.
Both my java - version and javac -version are 11.0.9 and I indicted in the dependencies of the build.gradle file that the javaFx version is 11.
I have tried running the command again but experienced the same issue.

Any help will be appreciated thanks!!

**Comment by damithc** [comment]
@Justinnje in case this info is helpful for someone replying to this thread later, are you able to run the AB3 JAR file?

**Comment by Justinnje** [comment]
Hi prof, i have not tried AB3 yet. But I have resolved the issue. 

What i did was download the jdk 11.0.9 file again from oracle. Then i think there were some updates or something that took place,  im not too sure as well. But after i did that, the jar file now executes.
