### ISSUE TITLE
Anyone knows what's happening with this dot?

### ISSUE THREAD

**Issue by Jacky142857** [nus-cs2103-AY2122S2/forum#162]
![png](https://user-images.githubusercontent.com/77191979/154455208-2f648f9a-edbf-407a-89f0-75be00e6dfbb.png)
I tried to set a theme on github then deleted the pull request of this set theme, and pulled to my local machine

**Comment by damithc** [comment]
@Jacky142857 let's wait to see if someone can explain what's happening. In the meantime, it's nothing to worry about.

**Comment by domlimm** [comment]
Hello @Jacky142857 ! I believe this means that the initial branch that was created to add this commit, `Set theme jekyll-theme-cayman`, in is no longer in your repository remotely.

I think you could try looking into `git prune` [here](https://www.atlassian.com/git/tutorials/git-prune), to remove that 🔴. I might be wrong!

**Comment by damithc** [comment]
> Hello @Jacky142857 ! I believe this means that the initial branch that was created to add this commit, `Set theme jekyll-theme-cayman`, in is no longer in your repository remotely.
> 
> I think you could try looking into `git prune` [here](https://www.atlassian.com/git/tutorials/git-prune), to remove that 🔴. I might be wrong!

Nope, that's not it :-)

**Comment by domlimm** [comment]
@damithc Could it be... Jacky's local branches got detached from the `origin/gh-pages` branch?

**Comment by damithc** [comment]
@domlimm If you do a fetch from your fork, you'll find that you have a similar situation in your fork too :-)

**Comment by charmainehly** [comment]
I'm wondering if the red dot indicates the "delete" action you carried out on the PR? 

As my IDE shows a red dot at the relevant directories/subdirectories in my local repository if there happen to be some files or code deleted when I pull and merge branches?

**Comment by damithc** [comment]
Guys, It's actually a special branch named `gh-pages` created by GitHub (the 'Pages' feature of GitHub), to host your repo website. It appears as a dot because there is only one commit at this time. Every time you push a commit to the master branch, GitHub will automatically build a new version of the website and push that version as a new commit to the `gh-pages` branch. The color red is a random choice by SourceTree -- doesn't mean anything.
