### ISSUE TITLE
Ui.png not appearing in iP showcase and URL link

### ISSUE THREAD

**Issue by aceszhenwei** [nus-cs2103-AY2122S2/forum#163]
Hi guys, I followed the [rules](https://nus-cs2103-ay2122s2.github.io/website/schedule/week6/project.html) for the Ui.png upload, but it is not appearing on the iP showcase or the link.

My [repo/docs](https://github.com/aceszhenwei/ip/tree/master/docs) for reference.

As you can see, I have uploaded my picture into the docs folder, and named it exactly `Ui.png`:
<img width="892" alt="Screenshot 2022-02-17 at 9 16 13 PM" src="https://user-images.githubusercontent.com/70692871/154489401-2048b839-bc86-4105-9f66-a01db9eddb2e.png">

However, it is not showing up at neither the iP Showcase nor the [link](https://aceszhenwei.github.io/ip/Ui.png).

I had uploaded this yesterday as well, so it is not an issue due to slow update time. I have also successfully managed to publish my User Guide, which has been logged by the iP Progress Tracker:

<img width="706" alt="Screenshot 2022-02-17 at 9 20 25 PM" src="https://user-images.githubusercontent.com/70692871/154490022-1597dcf6-5257-4eef-8cbd-dc699cd5c702.png">

I'm sorry if I'm missing out something super basic here. Can anyone point out where I had gone wrong? Thanks in advance!

**Comment by damithc** [comment]
@aceszhenwei Perhaps an issue with the read/write access permission of that specific file?

**Comment by Jacky142857** [comment]
I also had the same problem and now I solved it. You might be choosing the master folder instead of docs folder. See 'Enable the GitHub Pages feature for your fork' in A-UserGuide.

**Comment by aceszhenwei** [comment]
@Jacky142857 That worked! Thanks so much.
