### ISSUE TITLE
jar file not running on macos

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#164]
Hi im using windows and I built my jar file using gradle shadowJar. It runs fine on my computer even when I transferred it to an empty folder. However, when I sent it to my friends that are using MacOS, it is not running. Does anyone have an idea of what the issue might be?

**Comment by damithc** [comment]
@e0543517 You can share the JAR file here so that others can give it a try, in case the problem is with your friend's set up rather than your JAR file.

**Comment by paing-oo** [comment]
https://github.com/e0543517/ip/releases/tag/v0.2

here is the link thanks to anyone helping!

**Comment by zxgoh** [comment]
@e0543517 Hi, so far the workaround other members have found was on #44 which is to use `java -jar name.jar`. This seems to be an issue with macOS.

Your app works fine.

<img width="399" alt="Screenshot 2022-02-18 at 2 31 53 AM" src="https://user-images.githubusercontent.com/73661051/154547442-1f8321aa-ac30-487a-8bf4-f408c3d2a4a9.png">

**Comment by gigituang** [comment]
@e0543517 Hello, I've tested out your JAR file and it works fine on my side. It could be the java issue. I faced the same issue in the past but i redownloaded my java.

You can try this link that the prof provided for mac users:) Hope it helps!
https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language

**Comment by jessicajacelyn** [comment]
@e0543517 hello! I'm a mac user also and your jar file seems to be working fine on my side too. I was wondering that maybe it's not that the file is not running on your friend's mac, maybe he did not allow the file to run from the system preference>privacy&security side, because mac does not really allow you to just run a file you downloaded online randomly without certificate. Hopefully this is the problem! :))

**Comment by damithc** [comment]
Thanks all who pitched in so far @jessicajacelyn @gigituang @zxgoh 
Similar issue, if you guys want to pitch in with that too https://github.com/nus-cs2103-AY2122S2/forum/issues/167

**Comment by paing-oo** [comment]
thank you @jessicajacelyn @gigituang @zxgoh
