### ISSUE TITLE
Jar file unable to be run properly on macOS but runs perfectly fine on Windows

### ISSUE THREAD

**Issue by xSaints19x** [nus-cs2103-AY2122S2/forum#165]
My computer is running on Windows 10 and I've passed smoke test 1 which is:

1. Copy the jar file to an empty folder and test it from there. This should surface issues with hard-coded file paths.

But I'm having issues with smoke test 2 which is:

2. Pass the jar file to team members and ask them to do a test drive. Assuming some of your team members' OS differ from yours, this should verify if the app is cross-platform.

It seems that running the `java -jar duke.jar` command on the macOS terminal works as expected but double-clicking the jar file results in this error showing up: 

![image](https://user-images.githubusercontent.com/67327422/154508549-e8a711c1-67c2-4255-b1a5-c2238e31bc28.png)

Can anyone kindly advise on this issue? Thanks in advance! 😊

Jar file can be found [here](https://github.com/xSaints19x/ip/releases/tag/A-Release).

**Comment by AAlghrairy** [comment]
To offer you some piece of mind, as was stated by @damithc in #156:

> Yes, as far as the module is concerned, it is good enough if the JAR file can be run using the java -jar command.

But you could try using the solution in #159 and see if it works for you too.

**Comment by xSaints19x** [comment]
Alright, thanks AAlghrairy for the help!
