### ISSUE TITLE
tP: Run test after cloning from team organization repo and setting up the project

### ISSUE THREAD

**Issue by putaojuice** [nus-cs2103-AY2122S2/forum#166]
Hello, would like to ask if anyone encounter this problem after following through the instructions for tP individual fork set up. I've done the set up for developer environment according to [Setting up and getting started page](https://nus-cs2103-ay2122s2.github.io/tp/SettingUp.html) from the module website. 

It says **248 of 248 tests passed** but i am not sure if the red texts are supposed to appear. 

Would appreciate anyone to help me look into this

![Screenshot 2022-02-18 at 1 17 58 AM](https://user-images.githubusercontent.com/33406416/154535621-3fe4f669-dbcd-49a8-8d95-a88e882d8fed.png)

**Comment by damithc** [comment]
Perhaps others who have set up the tP in their computer can comment on if the behavior observed by @putaojuice is same as theirs or different?

**Comment by domlimm** [comment]
Hello @putaojuice! I've the same output when running `test`. They're 'just' `warning` and `info` statements. Will look more into them and see how to make them disappear! Not sure if anyone has already found out how to remove these statements...

**Comment by damithc** [comment]
Possibly relevant comment, from the forum of a different module https://github.com/nus-tic4002-AY2122s2/forum/issues/15#issuecomment-1035292771
