### ISSUE TITLE
How to resolve `/docs/Gemfile.lock` conflicts on different environment

### ISSUE THREAD

**Issue by Rye-Catcher** [nus-cs2103-AY2122S2/forum#168]
So I was trying  to deploy the `tp` site locally for testing by referring to this [guide](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll) suggested by the SE-Edu website 

When I run `bundle install` on Windows 10 with ruby version `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]`

It shows an error 
`Your bundle is locked to listen (3.2.1) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in that source. That means the author of listen (3.2.1) has removed it. You'll need to update your bundle to a version other than listen (3.2.1) that hasn't been removed in order to install.`

So I run `bundle update` and solved this issue.

Also, similar issues happened on macOS and solved it in similar way

But the thing is: the file `/docs/Gemfile.lock` now is different in the local repo on Windows 10 and the one on macOS. So how do I resolve this conflict? Do I  just not to stage and commit that file?

I found this [post](https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore) but still a bit confused.

**Comment by damithc** [comment]
@Rye-Catcher most likely you don't need to push that file to your fork, if GitHub is able to render your website already.
You can also try reverting those changes to see if that causes any problems in your local dev environment.

**Comment by Rye-Catcher** [comment]
> @Rye-Catcher most likely you don't need to push that file to your fork, if GitHub is able to render your website already. You can also try reverting those changes to see if that causes any problems in your local dev environment.

Yes, GitHub is able to render the website. But if I revert changes, it causes issues for deploying the site on my local environment.
