### ISSUE TITLE
Does GitHub Actions only need to be set up in the team repo only, or in our individual repo's as well? 

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#169]
Hi all, 

I wanted to clarify if the GitHub actions need to be set up in our individual repo as well? Or just the team repo only? I tried enabling GitHub actions in my repo & there seems to be a failure with error `{'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}`

**Edit**: I realized the instructions in [Individual Fork Setup](https://nus-cs2103-ay2122s2.github.io/website/schedule/week6/project.html#tp-individual-fork-setup) did not specify setting up GitHub Actions as well. But out of curiosity, would it be possible to set up GitHub actions & CodeCov in our individual repo as well?

**Comment by domlimm** [comment]
Hello @waffledood! I believe it's only for team repo!

**Comment by waffledood** [comment]
@domlimm yup it is, thanks for the confirmation!
