### ISSUE TITLE
Requesting help to test jar file across all platforms

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#170]
Hi guys, as I have received an email that my jar file has failed the smoke test. I have changed the dependencies in my build.gradle and created a new jar file. Would appreciate anyone's help in testing out my jar file and please state the operating system that you are using as well. Thank you!

https://github.com/e0543517/ip/releases/tag/v0.3

**Comment by Punpun1643** [comment]
Works fine on my side for macOS 👍

**Comment by zhongfu** [comment]
![image](https://user-images.githubusercontent.com/1695582/154855027-4382a12f-7638-455b-a1fb-ca777dc5221d.png)

launches fine on linux + wayland, though you don't seem to be handling invalid dates properly

**Comment by lkldev** [comment]
launches fine on my windows 10 👍 although some wrong commands can be executed while some are not able to, not sure what is the intended outcome...
