### ISSUE TITLE
Failed smoke test but tested JAR file running successfully on macOS and Windows + Requesting for help to test JAR file

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#171]
I received an email that I failed the automated smoke test with the following errors across all platforms:

`Error: LinkageError occurred while loading main class duke.Launcher java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

However, I have tested the JAR file by running the command as well as clicking to open. Both run successfully. 

I think it was some problem with my `build.gradle` dependencies so I changed it slightly. Tested on both macOS and Windows and worked fine.

Edit: I made the mistake of building and compiling using Java 13.

I would appreciate if I could get some help testing my JAR file across all platforms 😊: https://github.com/Punpun1643/ip/releases/tag/v0.2

**Comment by zhongfu** [comment]
you're compiling & building with Java 13, not 11

**Comment by Punpun1643** [comment]
Thanks! @zhongfu I completely overlooked that. I think it should work now!

**Comment by kavxya** [comment]
Hi! Can I ask how you changed the compile to Java 11?

**Comment by yusufaine** [comment]
@kavxya what I did was specify the what Java version to build on in my [build.gradle](https://github.com/yusufaine/ip/blob/master/build.gradle)

**Comment by kavxya** [comment]
Thank you so much! That fixed the LinkageError!
