### ISSUE TITLE
Request help for testing on Linux and Mac

### ISSUE THREAD

**Issue by brigittesantoso** [nus-cs2103-AY2122S2/forum#175]
Hi I failed the smoke tests for Mac and Linux. Any Mac/Linux users can help to test my new release out? Thank you!

https://github.com/brigittesantoso/ip/releases/tag/v0.2

**Comment by Punpun1643** [comment]
Tested on macOS and worked for me. However, not sure if this is intended when expanding the window.
![Screenshot 2022-02-21 at 3 20 48 PM](https://user-images.githubusercontent.com/60144099/154907416-2a3a3941-f412-4b30-8800-f312962db986.png)

**Comment by sbhbenjamin** [comment]
Tested it on mac as well, and it works (i.e. commands work and can save to and load from the data file). Also, I was unable to see the title of the app on the menu bar, maybe that could be a reason why the smoke test fails?

<img width="412" alt="Screenshot 2022-02-21 at 5 55 13 PM" src="https://user-images.githubusercontent.com/34487322/154947231-98692bb0-927f-4a48-a664-2420e667dfed.png">

**Comment by zhongfu** [comment]
seems to work fine on Linux + Wayland (incl load/save)

**Comment by brigittesantoso** [comment]
Okay thank you for all the help!
