### ISSUE TITLE
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @..'

### ISSUE THREAD

**Issue by janald99** [nus-cs2103-AY2122S2/forum#176]
Hi guys I need your help! I believe my JAR file cannot be opened on Mac, and as some errors when running on linux. Here is a screenshot of my friend's computer:
![image](https://user-images.githubusercontent.com/77261002/154907837-34b8ec5b-dd77-4498-af1b-592e734e9936.png)

For Mac computers, it says file is 'damaged and can't be opened'.

I always end back up at this website after trying to find out how to solve the issue, but I am not sure where to start:
https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna

Anyone else that faced the same issue? How did you guys fix it? Thank you!

**Comment by damithc** [comment]
@janald99 `no suitable pipeline found` is a common error. See if you can find past posts in this forum (also check closed issues) dealing with the same problem.

Tip: FYI, text is preferred over screenshots when posting error messages in the forum https://nus-cs2103-ay2122s2.github.io/website/admin/appendixD-help.html#:~:text=Avoid%20showing%20text%20as%20screenshots

**Comment by janald99** [comment]
Alright thanks prof! Going to close this issue now, think i fixed it.

**Comment by tlylt** [comment]
Hi @janald99, glad that your problem is fixed! 

If possible, it would be extremely helpful(and kind ) if you could include the rough ideas of your solution before closing the issue. You can either comment or edit it into the description so that others who might be in the same situation could benefit from it.

**Comment by janald99** [comment]
I referred to this thread in the past semester:

https://github.com/nus-cs2103-AY2021S2/forum/issues/173

So I removed the following plugins from build.gradle:
plugins {
    id 'org.openjfx.javafxplugin' version '0.0.9'
}
