### ISSUE TITLE
Requesting for help testing on MacOS

### ISSUE THREAD

**Issue by zhongfu** [nus-cs2103-AY2122S2/forum#178]
It's a little late, but I'd appreciate any help testing out my submission -- https://github.com/zhongfu/ip/releases/tag/A-Release

I'd appreciate if you could also help me check the following:
- text in message bubbles and labels wrap properly when window is resized 
- text field/button stays at the bottom and messages pane expands properly when window is resized
- pressing <kbd>up</kbd>/<kbd>down</kbd>/<kbd>enter</kbd> keys while the text field is in focus works (<kbd>up</kbd>/<kbd>down</kbd> should go through command history, <kbd>enter</kbd> should run commands)

**Comment by Punpun1643** [comment]
* (should work well) text in message bubbles and labels wrap properly when window is resized
* (works well) text field/button stays at the bottom and messages pane expands properly when window is resized
* (works well) pressing up/down/enter keys while the text field is in focus works (up/down should go through command history, enter should run commands)

Here is a screenshot of how your GUI looks like when resize (not sure if the text at the top is intended that way):
![Screenshot 2022-02-21 at 10 58 43 PM](https://user-images.githubusercontent.com/60144099/154980344-b53937d7-4d4e-4c6d-b0a6-875ca32b3d57.png)

**Comment by zhongfu** [comment]
@Punpun1643 alright, thanks!

text on the top is a little weird, yeah -- it's supposed to wrap as well, but eh, i guess it probably isn't too much of an issue
