### ISSUE TITLE
Requesting for help to test JAR file on Linux

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#179]
Hi, I have yet to test my JAR on Linux yet after failing the smoke test. Would really appreciate it if any Linux user could help me test my JAR file out at https://github.com/Punpun1643/ip/releases/tag/v0.2

Thanks! 😊

**Comment by zhongfu** [comment]
linux + wayland: launches fine, load/save works, `bye` doesn't actually quit the program

**Comment by Punpun1643** [comment]
Alright, thanks for helping!
