### ISSUE TITLE
Can our team use ControlsFX? 

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#181]
## Library

[ControlsFX](https://github.com/controlsfx/controlsfx)

## Purpose

We would like to implement pop-up notifications that contain information for the user. Currently, this functionality is not natively available in JavaFX. The closest option to this in JavaFX are [Alert](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Alert.html)s but Alerts will cause the user to lose control of the main window, as the user will need to close this Alert before they are able to perform any actions in the main window. We want pop-up notifications that will remain active, but still allow the user to perform actions in the main window.

## License

{[BSD-3-Clause License](https://github.com/controlsfx/controlsfx/blob/master/license.txt)}

**Comment by damithc** [comment]
Approved.
