### ISSUE TITLE
Updating final release of iP

### ISSUE THREAD

**Issue by AAlghrairy** [nus-cs2103-AY2122S2/forum#182]
If a bug or coding violation is spotted, and the jar file of the latest release is **updated** (rather than creating a new release), will the grading be performed from where the tag `A-Release` corresponds to, or from the latest commit?

**Comment by damithc** [comment]
@AAlghrairy We use the latest code/JAR for grading.

**Comment by AAlghrairy** [comment]
Thank you very much for your response @damithc
