### ISSUE TITLE
tP: Is it okay to change theme?

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#183]
Hi, is it okay to change the theme from minima to other themes? I noticed the se-edu/addressbook-level3 uses minima for its documentation.

**Comment by damithc** [comment]
@albertsutz Yes, you are allowed to change the theme. 

But keep in mind that the UG and the DG you will submit at the end will be PDF files generated from your tP website, and if the theme makes it hard to read the UG/DG (in PDF format), those testing your tP at the PE can report it as a bug/flaw. 
In other words, ensure your new theme doesn't degrade the documentation even when converted to PDF format.

**Comment by albertsutz** [comment]
Thank you!
