### ISSUE TITLE
Package for tP

### ISSUE THREAD

**Issue by lkldev** [nus-cs2103-AY2122S2/forum#185]
Hi prof, do we have to rename the package for tP or can we leave it as `seedu.address`?

**Comment by damithc** [comment]
@lkldev Up to you, but if you do want to change, best to do it early. If you do it later, it can throw off our authorship tracking as renaming packages can attribute a whole lot of code to the person who did the renaming.

**Comment by lkldev** [comment]
Noted! Thank you prof :)
