### ISSUE TITLE
What exactly are optional elements in UML Sequence Diagrams? 

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#186]
Hi Prof & fellow classmates, 

I wanted to clarify what constitute optional elements in UML Sequence Diagrams? This is with regards to the omission of certain elements in UML Sequence Diagrams. In the CS2103 online textbook, [Part W6.1 → Minimal Notation](https://nus-cs2103-ay2122s2.github.io/website/schedule/week6/topics.html#design-modelling-modelling-behaviors-sequence-diagrams-basic), it is stated that 

> To reduce clutter, **optional elements (e.g, activation bars, return arrows) may be omitted** if the omission does not result in ambiguities or loss of relevant information. Informal operation descriptions such as those given in the example below can be used, if more precise details are not required for the task at hand.

Based on this & if I understood the sentence correctly, **any element** (even method calls, self-invocation) in a UML Sequence Diagram **_can_** be an optional element & thus omitted from the UML Sequence Diagram **_as long as_** its omission does not cause any confusion. The sentence in the textbook only quoted activation bars & return arrows as examples, but optional elements are not restricted to those 2 only. Is my understanding correct? 😕

**Comment by damithc** [comment]
> Based on this & if I understood the sentence correctly, **any element** (even method calls, self-invocation) in a UML Sequence Diagram **_can_** be an optional element & thus omitted from the UML Sequence Diagram **_as long as_** its omission does not cause any confusion. The sentence in the textbook only quoted activation bars & return arrows as examples, but optional elements are not restricted to those 2 only. Is my understanding correct? 😕

Yes, that's right @waffledood

**Comment by waffledood** [comment]
ah okay, that's great, thanks for the clarification Prof! 👍
