### ISSUE TITLE
Is my use case diagram correct? 

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#187]
Hi Prof & fellow classmates, 

I was attempting the exercises in Week 7's Requirements: Use Cases section. I wanted to clarify my solution for this question "Use case diagram for QA system"

> A software house wishes to automate its Quality Assurance division. 
The system is to be used by Testers, Programmers and System Administrators. Only an administrator can create new users and assign tasks to programmers. Any tester can create a bug report, as well as set the status of a bug report as ‘closed’. Only a programmer can set the state of a bug report to ‘fixed’, but a programmer cannot set the status of a bug report to ‘closed’. Each tester is assigned just one task at a time. A task involves testing of a particular component for a particular customer. Tester must document the bugs they find. Each bug is given a unique identifier. Other information recorded about the bug is component id, severity, date and time reported, programmer who is assigned to fix it, date fixed, date retested and date closed. The system keeps track of which bugs are assigned to which programmer at any given time. It should be able to generate reports on the number of bugs found, fixed and closed e.g. number of bugs per component and per customer; number of bugs found by a particular tester; number of bugs awaiting to be fixed; number of bugs awaiting to be retested; number of bugs awaiting to be assigned to programmers etc.
**Develop a use case diagram to capture their requirements given below.**

I wrote something like this: 

![image](https://user-images.githubusercontent.com/59903913/155913575-984a7bc9-30fa-4bef-9993-79032cdaf71b.png)

But the answer given is: 

![image](https://user-images.githubusercontent.com/59903913/155913656-c0c3f33b-9d0b-4fb1-a4c2-fa4d8d2b47b2.png)

May I clarify how & why the "edit bug report" & "generate report" use cases (circled in red) were derived? Those were the ones I missed out. The given description above did not **explicitly mention** that System Administrators _can_ generate reports or that Testers & Programmers _can_ edit bug reports. Were the details of these use cases referenced in the description? 

Are other use case diagram exercises similar to this? Where use cases are not often explicitly mentioned but have to be inferred from the description provided?

**Comment by damithc** [comment]
@waffledood Good question. Let's wait a few days to see if other classmates have anything to contribute

**Comment by takufunkai** [comment]
### Generate reports
I feel that as a sysadmin, you are representing the system in a way -- you should be able to have __full__ read and write access to all its functionalities and settings.

> (The system) should be able to generate reports on the ...

This line tells me:
1. The system has some "generate report" functionality
2. Based on the assumption of the sysadmin's authority in the system as stated above, the sysadmin should be able to execute "generate report" function

### Edit bug report
I am not too sure about this, but I guess that is inferred from the `date retested` field? 
Need another opinion on this 🤔

**Comment by damithc** [comment]
In most real projects, the problem description provides a starting point only. Some requirements can be teased out by reading between the lines (in this case, I can't imagine the system being any use unless the bug reports can be edited after the initial entry). Some more requirements can be discovered through follow up communications with stake holders.
Given this is an exercise (i.e., not a real project), you are not expected to go that far. Still, the answer given is the not meant to be the only correct answer; multiple use case diagrams can fit a reasonable interpretation of the given description. 
If this is an exam question, there will be more information provided as to the expectations.
