### ISSUE TITLE
IP: Class has been compiled by more recent version of the Java Runtime

### ISSUE THREAD

**Issue by Gernene** [nus-cs2103-AY2122S2/forum#188]
Hello! I was trying to troubleshoot a separate warning when I used `./gradlew clean shadowJar` to rebuild my jar. Although I didn't change any code, I'm now getting this error:

```
Gernenes-MacBook-Pro:ip gernene$ java -jar ip-all.jar
Error: LinkageError occurred while loading main class duke.Launcher
	java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Gernenes-MacBook-Pro:ip gernene$ java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
```
I'm using VSCode on MacOSand suspect that I messed something up when I clicked VSCode's option to "update the Java classpath". 
<img width="547" alt="Screen Shot 2022-02-28 at 10 29 24 AM" src="https://user-images.githubusercontent.com/15025605/155914251-e72f6a76-194b-4205-9f2d-2fceef6a07d2.png">

Does anyone know how to fix this? Thank you!

**Comment by yusufaine** [comment]
Hey! So I faced the same issue as well and specified these lines in my [`build.gradle`](https://github.com/yusufaine/ip/blob/0a80543e7b3daedfd35f8e04df54d847eb8e75db/build.gradle#L8), which specifies which Java version to build in -- hope this helps!

**Comment by Gernene** [comment]
@yusufaine Thank you so much for the speedy help! That did the trick for me! 🤩
