### ISSUE TITLE
Branching levels 7 and 8 incorrectly

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#19]
I think I have created the branches for levels 7 and 8 in a wrong way... Is there anything I can do with this? Or should I just continue? Will this affect the grading?

<img width="403" alt="Screenshot 2022-01-22 221442" src="https://user-images.githubusercontent.com/67496158/150641951-becd646a-cba9-429f-a15b-0fb5e28fb31d.png">

Thanks for helping!

**Comment by damithc** [comment]
It's a common mistake @zihaowrez 
Just leave it be. It will not affect marks.

**Comment by zihaowrez** [comment]
Thank you prof!
