### ISSUE TITLE
Proper way to sync fork with upstream repo

### ISSUE THREAD

**Issue by lzan98** [nus-cs2103-AY2122S2/forum#194]
Hi folks

I would like to clarify if there is a preferred method for this module to sync our fork with our team's repo?

My typical approach would be to click the `Fetch Upstream` option in my fork, which syncs the fork with the team repo, then pull to my local repo.

However, it is stated in the textbook under **7.7a Point 7** that 
`This is done by pulling the new code to their own local repo and pushing the updated code to their own fork.`

In that case, what commands should I be entering into the CLI? Tried running `git pull` but it says `Already up to date`, which I assume because I am pulling from my fork.

**Comment by yusufaine** [comment]
From the CLI, you'll have to do the following:

1. add upstream:
    * `git remote add upstream <link to TP.git>`

confirm by using `git remote -v` and ensuring that your upstream repo is set properly

2. fetch and merge from upstream: (ensure that you're in the master branch)
    * `git fetch upstream` -- fetch latest HEAD of the upstream repo
    * `git merge upstream/master` -- pulls the update to your local repo
    * `git push` -- push the latest changes from upstream to your personal remote fork

Alternatively for (2): `git pull upstream HEAD` -- from `git pull` docs: 

> In its default mode, git pull is shorthand for git fetch followed by git merge FETCH_HEAD.

**Comment by damithc** [comment]
> My typical approach would be to click the `Fetch Upstream` option in my fork, which syncs the fork with the team repo, then pull to my local repo.

@lzan98 `Fetch upstream` seems to be a fairly new GitHub feature. Likely you can use that too, instead of the one mentioned in the module website. The workflow recommended in the module website gets you to learn how to pull from multiple repos, which is a useful thing to know too -- so, there's a bit of additional value in there.

**Comment by lzan98** [comment]
Thank you Prof @damithc for the clarification and @yusufaine for the guide!
