### ISSUE TITLE
IP:  Request for help to test JAR file on Linux and Macs

### ISSUE THREAD

**Issue by teominghuang** [nus-cs2103-AY2122S2/forum#195]
I am currently using a Windows system, and I need help testing the JAR file on Linux and Macs environment. I have enlisted help from some of my friends, but my Jar filed still failed the shadow test despite having passed on my friend's systems. I have since made more changes, but I need a little more help with the testing portion using Linux and Macs systems as those are the environments my Jar file failed.

The release version can be found: [here](https://github.com/teominghuang/ip/releases/tag/A-Release)

**Comment by domlimm** [comment]
Hello @teominghuang! It works on `macOS`!

<img width="858" alt="image" src="https://user-images.githubusercontent.com/46486515/156304001-4bf3aaa5-81be-4d63-b1b6-b8f3b943dcb4.png">

**Comment by yusufaine** [comment]
Yup, I can confirm that it loads from the datafile too 👍. You can also consider the `bye` command to close the GUI

![image](https://user-images.githubusercontent.com/29030941/156304435-6918ff5f-b8cc-4f9a-8d7b-56ce734962c2.png)

**Comment by zhongfu** [comment]
launches on linux, save/load works, `bye` command doesn't seem to do anything

![image](https://user-images.githubusercontent.com/1695582/156320654-d3a1123f-8fef-4c6e-bb08-5eec4c02b9f6.png)

**Comment by ngjunkang** [comment]
It can be started on MacOS `12.2.1`. and works well! Maybe you might want to add more tests to ensure that all exceptions are handled and the logic works well. I will just list three below (not all of them):
1. Program hangs, when I enter `delete n`, where n is `n`, a string and not an integer. Perhaps `mark` and `unmark` will have the same problem?
2. Unhandled error, when I enter `delete c`, where c is `<= 0`. Perhaps `mark` and `unmark` will have the same problem?
3. If there's no tasks to `list`, I would reply `You have no tasks`.

**Comment by teominghuang** [comment]
You guys are angels, thank you! I have since made the necessary changes to account for the errors above!
