### ISSUE TITLE
iP: Request for help to test JAR file on Mac and Linux

### ISSUE THREAD

**Issue by ovidharshini** [nus-cs2103-AY2122S2/forum#196]
I am on Windows, and need help testing the JAR file on Mac and Linux environments. The release can be found [here](https://github.com/ovidharshini/ip/releases/tag/A-NewRelease). 
Thanks!

Edit: I have reuploaded the release as of 3pm 3/3/2022 and would really appreciate if someone could confirm if it now works on Linux!

**Comment by zhongfu** [comment]
launches on linux, but todo/event/etc results in a blank response and tasks don't seem to save properly

![image](https://user-images.githubusercontent.com/1695582/156321733-aeeef293-29b0-4e92-a72b-91164e69c537.png)

**Comment by yusufaine** [comment]
Tested the latest version (v1.1) on MacOS and it works fine for me!

![image](https://user-images.githubusercontent.com/29030941/156331340-0b0bb240-2a8f-4f97-bf19-acbc2c37a03b.png)

**Comment by Gernene** [comment]
Tested on MacOS and works for me! I did have some issues with the font, but I'm 99.99% sure it's a problem with my system.

**Comment by damithc** [comment]
> Tested on MacOS and works for me! I did have some issues with the font, but I'm 99.99% sure it's a problem with my system.

@Gernene if you are facing font problems, ensure you have followed the steps given in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language

**Comment by Gernene** [comment]
Hello Professor! I was just about to get around to this and finally downloaded zulu. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ovidharshini** [comment]
Thanks for the feedback! The updated jar file now appears to function as intended when tested on a VM with Ubuntu 20.04 so I will close this issue.
