### ISSUE TITLE
How to check the difference after a test fails?

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#199]
I have created a test class called **FavouriteCommandTest** that has a method called **execute_favouriteUnfilteredList_success()**:
```java
Person firstPerson = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
Person favouritedPerson = new PersonBuilder(firstPerson).withFavourite(true).build();

FavouriteCommand favouriteCommand = new FavouriteCommand(INDEX_FIRST_PERSON);


String expectedMessage = String.format(favouriteCommand.MESSAGE_FAVOURITE_PERSON_SUCCESS, favouritedPerson);

Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()), new UserPrefs());
expectedModel.setPerson(firstPerson, favouritedPerson);

assertCommandSuccess(favouriteCommand, model, expectedMessage, expectedModel);
```
I encountered a fail in the test case and wanted to check what's wrong but I only got back this error message 
![image](https://user-images.githubusercontent.com/56862300/156906212-361cb8be-b104-4692-91a3-5884a3adeb6d.png)
It does not show the actual difference in the result but just the name (CommandResult@87761b5f vs CommandResult@10eff) which I am unable to decipher. Please provide some help, I do appreciate it!

> The FavouriteCommand acts similar to the MarkCommand in iP, which changes an attribute "Favourite" of the first Person in the list to True when "favourite 1" is called.

**Comment by joshuayapwj98** [comment]
Hi! There's actually a lot of underlying code that you need to cypher through and debug (mostly the code in the logic folder). However, from my experience, the first thing you'd want to check is the implementation of your Person class `equals` function; does it compare your attributes correctly.

Next, another potential issue could be the `PersonBuilder` class. Ensure that your newly added variables are implemented inside the `PersonBuilder` class. Hope this helps!

**Comment by damithc** [comment]
> However, from my experience, the first thing you'd want to check is the implementation of your Person class `equals` function; does it compare your attributes correctly.

I think this tip from @e0544333 is in the right direction, but based on the screenshot, the comparison is between two `CommandResult` objects?

**Comment by damithc** [comment]
@hsiaojietng is the matter resolved?

When a Java program prints out something like `ClassName@123456`, it means the class does not override the `toString` method and therefore Java doesn't know how to give a meaningful string representation of the object. The error message will be more informative if you override the `toString` method of the `CommandResult` class, to return a string with more meaningful data about the object.

More info https://nus-cs2103-ay2122s2.github.io/website/se-book-adapted/chapters/cppToJava.html#the-object-class

**Comment by hsiaojietng** [comment]
@damithc Thanks for the recommendation, it helped alot!

**Comment by gweeyc** [comment]
Thank you will take note.
