### ISSUE TITLE
Merge branch 'branch-Level-7' not showing

### ISSUE THREAD

**Issue by aceszhenwei** [nus-cs2103-AY2122S2/forum#20]
I had merged branch-Level-7 with master and pushed. Subsequently, I merged branch-Level-8 with master, and had to manually resolve some conflicts in order to push. However, I see that I have only merged branch-Level-8 in my history.

<img width="336" alt="Screenshot 2022-01-22 at 10 44 09 PM" src="https://user-images.githubusercontent.com/70692871/150643160-36ea75cc-afdb-4ba5-afcb-4a334c1aff68.png">
 
However, my main code in master branch already has both changes from both branches committed to it already.

<img width="450" alt="Screenshot 2022-01-22 at 10 45 34 PM" src="https://user-images.githubusercontent.com/70692871/150643207-0b09d637-e279-4439-8a1e-a67b026f935c.png">

Will this affect the script? If so, what can I do to correct this?

Thank you in advance!

**Comment by damithc** [comment]
> Will this affect the script?

I'll answer this later. In the meantime, others can pitch in if they have any inputs on troubleshooting/diagnosing this issue

**Comment by VimuthM** [comment]
It doesn't seem to be an issue, but just a matter of git creating a merge commit or not.

Usually, if your merge can be done without the need for conflict resolution, git will not create a merge commit (it is called fast forwarding) unless you specify the `--no-ff` flag when you merge.

Seems to me that merging `Level-7` to `master` did not have conflicts as `master` was not updated at that time but after that merge, `Level-8` had conflicts to the updated `master` which resulted in a merge commit.

**Comment by aceszhenwei** [comment]
Thanks for the clarification! Careless of me. I'll leave this open for prof to address the issue regarding the script.

**Comment by damithc** [comment]
> This is mentioned under Week 3, so prof will answer if the absence of a merge commit for `Level-7` will affect the script.
> 
> ![image](https://user-images.githubusercontent.com/62249192/150644104-df35f0df-ab64-425d-8e8b-f97930972b27.png)

It's OK; it will not affect the grading.
