### ISSUE TITLE
Is GUI testing necessary?

### ISSUE THREAD

**Issue by bakano98** [nus-cs2103-AY2122S2/forum#201]
AB3 does not have any GUI testing. If I added GUI stuff as "good to have" features, would I **need** to implement any sort of GUI testing?

**Comment by damithc** [comment]
@bakano98 It's not a requirement to add automated GUI testing but you are welcome to do so. You can use manual testing for the GUI, if you don't implement automated GUI testing.

Note that it is not easy to implement automated GUI testing. FYI, [AB4](https://github.com/se-edu/addressbook-level4) implements automated GUI testing using TestFX framework, in case you would like to see a reference implementation.
