### ISSUE TITLE
Why does IntelliJ show related problems when methods are not related?

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#205]
While trying to implement some methods, I realise IntelliJ sometimes show "related problems" for the methods. An example would be for this `hasGroup` method.

![Screenshot 2022-03-11 at 1 31 22 PM](https://user-images.githubusercontent.com/60144099/157808257-0989c043-6a2a-461c-a41d-5f5023a4210b.png)

However, upon inspection, I realise the related problems are in tests that use other methods that are not related. An example is the tests that use `hasPerson` method.

![Screenshot 2022-03-11 at 1 34 15 PM](https://user-images.githubusercontent.com/60144099/157808529-ae2d68ba-2a0a-41d8-9cd0-529c76d63be1.png)

I'm wondering why this is so. Although I am able to pass all the current test cases so far.

**Comment by damithc** [comment]
@Punpun1643 See if `File -> Invalidate Caches` help get rid of the problems indicated by Intellij.

**Comment by Punpun1643** [comment]
Hi prof, that works thank you!
