### ISSUE TITLE
Codecov percentage drops after remove a prefix

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#206]
Hi all, I'm looking for some help on this (mentioned in title). 

I removed the `email` prefix i.e. User does not need to input `e/EMAIL` anymore, and the `codecov` dropped when I removed it.

Is there a reason why? I'm not sure how to go about solving this. Wondering if anyone faced this too.

Here is the link to the [coverage file](https://app.codecov.io/gh/AY2122S2-CS2103-F11-2/tp/compare/59/changes#D1L1).

Do not hesitate to let me know if more info is required!

Appreciate any help please, thank you! 😢

**Comment by yusufaine** [comment]
Hey @domlimm, I haven't dug around in your code yet but I think [this](https://stackoverflow.com/questions/38281319/what-is-codecov-score-and-how-it-is-measured/38281635#38281635) might be helpful in figuring out how CodeCov calculates coverage. Going off on a limb, I'd say your test files need to be updated to account for the change in Prefix.

**Comment by domlimm** [comment]
Hello @yusufaine! Yes, I've refactored all test cases related to this change. `test` from gradle runs successfully without any failed cases. And I did check what the coverage % means too but to no avail :')

^ This was what I was about to send and thank you, I actually missed out a test case.

Thanks @yusufaine! 💯

Closing this now.
