### ISSUE TITLE
Fixing a missed out code quality feedback in iP

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#208]
Hello, I realised I have forgotten to fix a feedback shared by the `nus-se-bot` for the Individual Project.

Am I still able to do that? Would I need to shift `A-Release` tag up to the latest commit or will grading be done as a whole of the entire repo? Or even create a new `release`?

Thank you so much!

**Comment by damithc** [comment]
@domlimm We take the latest JAR file and the latest code. The tags don't matter. Sure, you can create a new release or update the previous one. No need to change the tag.

**Comment by domlimm** [comment]
@damithc Alright prof. I'll just push out the feedback change. Could I leave the JAR file alone as it is? Not really keen on messing with it incase something crops up again...

Thank you! 😃
