### ISSUE TITLE
Getting java.lang.NullPointerException at JsonSerializableAddressBookTest.java:34

### ISSUE THREAD

**Issue by joey-chance** [nus-cs2103-AY2122S2/forum#209]
I did not change the JsonSerializableAddressBookTest.java file but yet when I make a PR, I am getting java.lang.NullPointerException at JsonSerializableAddressBookTest.java:34 which is not allowing me to pass the checks.
Here is the full error message.
![Screen Shot 2022-03-16 at 10 07 18 AM](https://user-images.githubusercontent.com/92976979/158502442-03e6b681-7206-412b-a665-770a4f195d41.png)

I was wondering if anyone encountered this issue before or knows how to fix it? Thanks in advance!

**Comment by joey-chance** [comment]
Needed to add JsonProperty

**Comment by damithc** [comment]
> Needed to add JsonProperty

This is how tests help you catch regressions faster :-)
