### ISSUE TITLE
Adding a Person via GUI

### ISSUE THREAD

**Issue by bakano98** [nus-cs2103-AY2122S2/forum#210]
Would adding a Person via GUI and their respective mandatory fields + optional fields go against the requirements of `Command Line Interface (CLI) is the primary mode of input.`, if they still have to type, instead of say, a dropdown box?

For example, the flow might look like something like:
- User clicks on something to open up a new window
- Window has text boxes for user to type and add fields accordingly (i.e. name, contact num, etc...)
- User presses confirm
- New `Person` is added into AddressBook

From the above flow, multiple commands _may_ be executed.

I am thinking that it does not violate the requirement, as their main mode of input is still via the keyboard, but just needing a confirmation

**Comment by damithc** [comment]
@bakano98 the important question is, is this UX optimized for a person who is good at typing? If such a person can accomplish the same task by typing a single command (provided such a single command is supported) faster than entering values in multiple places, the UX is not optimized for the target user, which can be reported as a _feature flaw_ by testers.

Personally, I prefer to type everything as a single command and hit enter as it is faster (once I'm familiar with the command). It can be made even faster by optimizing the command format e.g., making the command shorter by using shorter keywords, making some parts optional

**Comment by bakano98** [comment]
> @bakano98 the important question is, is this UX optimized for a person who is good at typing? If such a person can accomplish the same task by typing a single command (provided such a single command is supported) faster than entering values in multiple places, the UX is not optimized for the target user, which can be reported as a _feature flaw_ by testers.
> 
> Personally, I prefer to type everything as a single command and hit enter as it is faster (once I'm familiar with the command). It can be made even faster by optimizing the command format e.g., making the command shorter by using shorter keywords, making some parts optional

Thanks Prof! In other words, am I right to say that if the UX could be optimised in such a way that it would be _equally fast_ or perhaps, even faster than typing it in `CommandBox`, then it would perhaps be considered to be a good addition, rather than a feature flaw?

**Comment by damithc** [comment]
> Thanks Prof! In other words, am I right to say that if the UX could be optimised in such a way that it would be _equally fast_ or perhaps, even faster than typing it in `CommandBox`, then it would perhaps be considered to be a good addition, rather than a feature flaw?

Yes, as long as the input remains typing-centric (as our target user prefers typing as the mode of input).
