### ISSUE TITLE
Error when merge pr (Java CI problem)

### ISSUE THREAD

**Issue by yumengtan** [nus-cs2103-AY2122S2/forum#211]
I am facing this problem when I merged the pr. The pr passed the CI test.
May I know what caused this error and how to fix it?
![image](https://user-images.githubusercontent.com/77229521/158648575-d305af0d-2022-4d5e-a03f-f661c97ac2d7.png)
[More details here](https://github.com/AY2122S2-CS2103-F11-4/tp/runs/5573866893?check_suite_focus=true)

**Comment by Punpun1643** [comment]
I had the exact same error before when everything passed the CI test. Turned out it was some styling issue/ spacing issue in my fxml file and css file. Maybe you could look into that as well 😄

**Comment by damithc** [comment]
@yumengtan still not resolved? Are you the only one in your team facing this error?
Is this the PR in concern? https://github.com/AY2122S2-CS2103-F11-4/tp/pull/38
Seems it is merged already.

**Comment by yumengtan** [comment]
Dear Prof,

I discussed with the team and tried re-running the action. It seems to be working now. So sorry for the inconvenience caused.

Thank you.

Best Regards,
Yu Meng
________________________________

**Comment by damithc** [comment]
@yumengtan Good to hear the issue is resolved. You can go ahead and close the issue now.

**Comment by yumengtan** [comment]
@damithc After trying to re-run the merge pr, it seems to be working fine now.
