### ISSUE TITLE
GitHub CI not running 

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#212]
I'm trying to do a draft PR from my branch to the team repo. However, after the PR I realise the CI is not running. Is there any possible reasons why this is so? I did not modify anything in the `gradle.yml` file.

<img width="910" alt="Screenshot 2022-03-17 at 2 55 22 AM" src="https://user-images.githubusercontent.com/60144099/158666497-38627f35-10c9-4fbb-86e8-58c35fbf2f02.png">

**Comment by Punpun1643** [comment]
Update: It's running fine now, although I didn't change anything. Still quite curious why it didn't work initially 🤔

**Comment by domlimm** [comment]
Hello @Punpun1643, GitHub Actions was down last night. My team faced the same issue and we were wondering why too!

**Comment by damithc** [comment]
Thanks @domlimm 

Guys, if a similar thing happens again, you guys can check https://www.githubstatus.com/ to see if it is a problem on GitHub side.

Yes, there was an 'incident' on their side, as per https://www.githubstatus.com/history

**Comment by Punpun1643** [comment]
Thank you prof @damithc! Thanks @domlimm for the update!
