### ISSUE TITLE
Failure to deploy to github pages

### ISSUE THREAD

**Issue by LapisRaider** [nus-cs2103-AY2122S2/forum#214]
Hello, I'm currently having some issues with deployment to github pages. I kept getting this error stating that there is another deployment in progress when there aren't any. 

I tried waiting for an hour before rerunning the workflow, however, I still get the same error.

I found an online forum that mentioned deleting the workflow that was causing issues (the one that is supposedly 'running'), however, that didn't solve the issue either.

Anyone has any advice on what I can do?

![image](https://user-images.githubusercontent.com/36361212/158814305-c8e30475-cc2a-44b8-bc7a-677380beac8f.png)

**Comment by vishandi** [comment]
Our group encountered the same problem as well, getting the exact same error. Any help would be greatly appreciated :).

**Comment by damithc** [comment]
Same as https://github.com/nus-cs2103-AY2122S2/forum/issues/213 ?
No indication of a problem at https://www.githubstatus.com/ though.

**Comment by LapisRaider** [comment]
Yup, it was the same issues as #213.

**Fixed:**
After forcing a lot of re-runs, it finally passed (Took about two hours). I think there are just some issues on Github, as I'm seeing forums on StackOverflow created just a few hours ago about this issue.

[Supposed workaround](https://stackoverflow.com/questions/71507460/react-app-deployment-to-github-pages-build-successful-but-deploy-failed?noredirect=1&lq=1)

The workaround is to go to your last successful workflow run for the pages deployment (the one supposedly 'running'), and re-run all jobs, before going to your latest one and re-running. Not sure if this will work cause I followed another forum advice and deleted my workflow run :")

If that doesn't work, just keep waiting and re-running your failed workflow till it does.

**Comment by damithc** [comment]
GitHub is aware and looking into the matter, as per https://www.githubstatus.com/
Let me keep this issue open for a while in case someone else comes here with the same problem

**Comment by bingsen0806** [comment]
@LapisRaider did you delete only the **pages build and deployment** action for the commit that is supposedly 'running', or did u also delete also the **merging** and **CI** actions as well?

**Comment by LapisRaider** [comment]
> @LapisRaider did you delete only the **pages build and deployment** action for the commit that is supposedly 'running', or did u also delete also the **merging** and **CI** actions as well?

@bingsen0806 
I deleted only the **pages build and deployment** action for the commit that is supposedly 'running'. However, even after that, I was still failing the **pages build and deployment** action for my latest commit even after re-running it. 

In the end, what worked was I just left it alone for a while before re-running it again.

**Comment by damithc** [comment]
Guys, probably best to wait till GitHub confirms the affected features are working as expected again. ATM, they are still investigating. https://www.githubstatus.com/
