### ISSUE TITLE
Pass all CI and tests but fail github pages deployment

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#215]
I am able to pass all built tests and CI, but somehow GitHub pages has deployment error. Anyone knows how to resolve this issue?

![image](https://user-images.githubusercontent.com/71639142/158824042-511070c1-a18b-44bd-91bd-f8e282b96cd9.png)

Here's the link to my team repo
https://github.com/AY2122S2-CS2103T-W14-1/tp

**Comment by damithc** [comment]
@bingsen0806 See #214

**Comment by bingsen0806** [comment]
Attempt: I followed #214 and attempt to rerun my previously passed deployment, but now it got stuck as well.

So as the picture below I now have 2 stuck workflows.

I then try to delete/cancel both of them, as shown below
![image](https://user-images.githubusercontent.com/71639142/158826108-851a9f11-78f5-4fe8-89f0-800430ecd1fe.png)

But then I got server error 500 from GitHub
![image](https://user-images.githubusercontent.com/71639142/158826230-7c3c3e3a-7d9e-4d97-91f8-c35fb23f3307.png)
