### ISSUE TITLE
Java CI passing on group's repo but not on course's repo

### ISSUE THREAD

**Issue by vishandi** [nus-cs2103-AY2122S2/forum#216]
Hi!

Our group noticed that our PR doesn't pass the Java CI on [course's repo](https://github.com/nus-cs2103-AY2122S2/tp/pulls), although it passes the Java CI on [our group's repo](https://github.com/AY2122S2-CS2103T-W09-1/tp/actions). I've checked the commits and both repos are doing the Java CI check on the same commit. Is this an issue in GitHub or do we need to do something about it?

Any help would be greatly appreciated :). Thank you!

![image](https://user-images.githubusercontent.com/77654963/158962841-63497468-0990-48e4-8c9a-1512eb09514e.png)

![image](https://user-images.githubusercontent.com/77654963/158963204-930f8c6c-306f-40a7-92f6-5583b94b6f63.png)

Note: As seen on the screenshot, it seems like the failing check on the course's repo doesn't even started.

**Comment by damithc** [comment]
@vishandi possibly a temporary issue. Not to worry about it, as we don't use the PR CI status for anything.

**Comment by vishandi** [comment]
Noted, thank you Prof!
