### ISSUE TITLE
Is it okay to change UI in V1.4

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#218]
Is it okay to change the UI? Like maybe colours, placings, adding buttons, etc in V1.4?

I remembered that it is supposed to be a feature-freeze where we cannot add features. In this case, we are not adding feature just the display of the existing features?

**Comment by damithc** [comment]
@albertsutz only cosmetic tweaks such as alignment/color/font allowed, in addition to fixing bugs in the GUI. So, adding buttons will not be allowed.

More info https://nus-cs2103-ay2122s2.github.io/website/schedule/week10/project.html#3-start-the-next-iteration

![image](https://user-images.githubusercontent.com/1673303/159147806-4269f365-d5e4-4169-ab1c-0af779566dcb.png)

**Comment by albertsutz** [comment]
Okay, thanks prof. 
So am I right to say that changing how it looks is okay, just don't change/mess with the logic part of the UI? (E.g adding buttons means you add some functionalities, therefore it is not allowed)?

**Comment by damithc** [comment]
> So am I right to say that changing how it looks is okay, just don't change/mess with the logic part of the UI? (E.g adding buttons means you add some functionalities, therefore it is not allowed)?

That's right @albertsutz

**Comment by albertsutz** [comment]
Thanks prof!
