### ISSUE TITLE
Merging of Level-7 with master

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#22]
Hello! Quite a silly and quick question but... We are supposed to merge `Level-7` with `master` before doing `Level-8` right?

**Comment by Yukun99** [comment]
If they do not affect the same files, it's generally pretty safe to merge everything later, but if they do affect the same files, it would be good to merge level 7 first, if not you'll have to do more work later with merge conflicts.

**Comment by domlimm** [comment]
Alright! I'll decide on it again! Thank you!

**Comment by damithc** [comment]
> Hello! Quite a silly and quick question but... We are supposed to merge `Level-7` with `master` before doing `Level-8` right?

@domlimm is your question answered by the highlighted part of the below?
![image](https://user-images.githubusercontent.com/1673303/150680918-9f432bbe-3184-421b-91ca-8e863377bb9c.png)

**Comment by domlimm** [comment]
@damithc Hello prof, yes I have actually read that a few times and studied Levels 7 and 8 before working. I feel that the highlighted could mean after finishing Levels 7 and 8? Both levels don't seem to have much of a connection as @Yukun99 has mentioned, also based on what we need to implement for each level. 

I understood the highlighted sentence in this way:
```git
From master:
git checkout -b branch-Level-7 // Work on Level-7

Then, once completing Level-7, again from master:
git checkout -b branch-Level-8

Then, we'll merge them one after another.
```

But prof I suppose, either way works (i.e. Doing Levels 7 and 8 respectively then merging or merging `Level-7` with `master` then doing `Level-8` and merging again)? :sweat_smile:

**Comment by damithc** [comment]
> I understood the highlighted sentence in this way:
> 
> ```
> From master:
> git checkout -b branch-Level-7 // Work on Level-7
> 
> Then, once completing Level-7, again from master:
> git checkout -b branch-Level-8
> 
> Then, we'll merge them one after another.
> ```

Correct 👍 


> But prof I suppose, either way works (i.e. Doing Levels 7 and 8 respectively then merging or merging `Level-7` with `master` then doing `Level-8` and merging again)? 😅

Yes, either way _works_. But the exercise is meant for you to practice working in _parallel_ branches. Hence, the extra requirement not to merge the first branch before starting the second one. For example, a common mistake when working on parallel branches is to start the new branch from the previous branch instead of from the master branch. This exercise is meant as an opportunity to learn to avoid that mistake.

**Comment by domlimm** [comment]
Great, got it! Thank you prof! 😄
