### ISSUE TITLE
Bug reports for smoke-testing CATcher

### ISSUE THREAD

**Issue by MontyPython28** [nus-cs2103-AY2122S2/forum#220]
I'm a bit confused on how to smoke-test CATcher. When we're asked to make dummy reports, do they have to be about an actual bug we found in our versions of AB3? Or can we pretend that we found an issue and report the made-up issue instead?

**Comment by damithc** [comment]
@MontyPython28 fake/made-up bug reports.

**Comment by vishandi** [comment]
Hi Prof, a follow-up question regarding this issue: does the screenshot need to be a screenshot of some code/GUI or it could be anything also?

**Comment by damithc** [comment]
> Hi Prof, a follow-up question regarding this issue: does the screenshot need to be a screenshot of some code/GUI or it could be anything also?

@vishandi anything.
