### ISSUE TITLE
Using External Images

### ISSUE THREAD

**Issue by vishandi** [nus-cs2103-AY2122S2/forum#221]
Hi! In this post, I would like to ask whether we are allowed to use external images that we found on the internet, such as from [flaticon](https://www.flaticon.com) or not. If the answer is yes, do we need to give credit somewhere for the artists of the images?

Thank you!

**Comment by damithc** [comment]
@vishandi yes, you can use such assets if
1. the license it has been released under permits such reuse, 
2. you adhere to any license terms, 
3. and you credit the source appropriately.

**Comment by AAlghrairy** [comment]
If you want to avoid having to deal with licenses or crediting, you can try using images under Creative Commons License.

For example, on Google Images, there is an option under `Tools` labelled "Usage Rights". Select Creative Commons licenses and you will be shown images that are free to use.

**Comment by vishandi** [comment]
Thank you, Prof!
