### ISSUE TITLE
How to name a package for commands of a specific domain

### ISSUE THREAD

**Issue by Rye-Catcher** [nus-cs2103-AY2122S2/forum#223]
If I have several commands of a specific domain, for example, about the task scheduling. And I want to wrap those command classes in a package. How should I name the package?

Should the name be `seedu.address.logic.commands.schedule` or `seedu.address.logic.commands.schedulecommands` or don't wrap them at all?

**Comment by damithc** [comment]
From grading/admin perspective, we don't have any requirements on  this other than the naming conventions specified in the coding standard. This is a good opportunities for you guys to look for, share, and discuss good practices for creating/naming Java packages.

**Comment by Rye-Catcher** [comment]
> From grading/admin perspective, we don't have any requirements on this other than the naming conventions specified in the coding standard. This is a good opportunities for you guys to look for, share, and discuss good practices for creating/naming Java packages.

Thanks Prof. I think I will choose  `commands.schedule` for now because the alternative choice is a bit too long for me
