### ISSUE TITLE
Where is the data folder/ json file stored on Mac?

### ISSUE THREAD

**Issue by xpzmichael** [nus-cs2103-AY2122S2/forum#224]
When executing the jar file on Windows, a data folder will be automatically created, but I cannot find it anywhere on mac. Anyone knows where is it?

**Comment by pyk595** [comment]
It should be in the directory you placed your jar file in. Alternatively, you can try checking whether the path is hardcoded and if your code handles a missing directory in the proper manner.

**Comment by xpzmichael** [comment]
@pyk595 But i cannot find it in my directory on mac. Even running the original AB3 application i cannot find the folder. But on windows i can.

**Comment by pyk595** [comment]
@xpzmichael You can try modifying the data first and exiting (running an add command)? AB3 is save on write

**Comment by yusufaine** [comment]
> It should be in the directory you placed your jar file in.

Just wanted to chime in and say that this is the case for me.


![image](https://user-images.githubusercontent.com/29030941/159476185-79a6dbd3-7289-4d6d-aa7d-04e91981f1c0.png)

**Comment by damithc** [comment]
@xpzmichael See if this (from a previous semester) is relevant https://github.com/nus-cs2103-AY2122S1/forum/issues/221
