### ISSUE TITLE
Label style not appearing in application

### ISSUE THREAD

**Issue by tzhan98** [nus-cs2103-AY2122S2/forum#225]
In `PersonCard.java`, I have made the following changes:
```
name.setText(person.getName().fullName);
name.setTextFill(Color.web("#a30026"));
name.setFont(new Font("Arial", 30));
```
"#a30026" is supposed to be a dark red, however the `name` field of my application does not reflect that (still white). Does anyone know why? Similarly, the `setFont()` customization does not appear to reflect on my GUI.

**Comment by domlimm** [comment]
hey @tzhan98! Hmmm.. It seems like you're doing it correctly. Not sure if it's existing styles having higher priority (e.g. Maybe a stylesheet overwriting) over your explicit setting in your code block.

Could you try this (Nevermind, this is in Java 7):
```java
name.setTextFill(Color.decode("#A30026");
```

`name` is a Label right?

Could try this using `css`:
```java
name.setStyle("-fx-text-fill: #A30026;");
```

Or maybe look for the `name` Label in your `FILE.fxml` and set in-line styling:
```java
<Label fx:id="name" style="-fx-text-fill: #A30026;" />
```

**Comment by tzhan98** [comment]
Thanks @domlimm!

`name.setStyle("-fx-text-fill: #A30026;");`

did the trick.

I had change the styling based on attributes of the field 'name' so I couldn't just change the `fxml` file. (e.g if `name` started with `A` give a different colour)

**Comment by domlimm** [comment]
You're welcome @tzhan98! Any clue why it didn't work with the former method? 😭

**Comment by tzhan98** [comment]
Sorry for the late reply! Tbh I have no idea too 😭
