### ISSUE TITLE
How is contribution counted and marked?

### ISSUE THREAD

**Issue by FYimu** [nus-cs2103-AY2122S2/forum#226]
Hii can I ask how contribution to the team repository is counted? For example, if I wrote a java file, and someone refactored (by copy and paste) it into another folder, and his/her commit shows that he/she added a new file and all lines were added by him/her. Would this (codes written by me were deleted together with the file) affect my contribution or final mark?

**Comment by damithc** [comment]
@FYimu We don't grade your contribution based on the lines of code attributed to you -- it is graded based on peer evaluations. But we do grade your code quality based on the code attributed to you in the code dashboard.
The default code authorship is based on who modified the line last, but you can override that behavior to claim certain code blocks as yours. More info https://nus-cs2103-ay2122s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

**Comment by FYimu** [comment]
@damithc Thank you prof!
