### ISSUE TITLE
In video question for 10.4a is empty

### ISSUE THREAD

**Issue by whtan99** [nus-cs2103-AY2122S2/forum#228]
It appears there is a small bug on the 10.4 video on `Test Cases: Equivalence Partitions` [here](https://nus-cs2103-ay2122s2.github.io/website/schedule/week10/topics.html#w10-4-test-cases-equivalence-partitioning).

There is not supposed to be any in-video quiz. However, midway through the video at the ***1:45 mark***, a pop up appears with an empty slide as shown
![Screenshot 2022-03-23 at 12 10 20 PM](https://user-images.githubusercontent.com/54658569/159622262-efcbd36b-08cb-45d3-a093-c015b745f894.png)

I was wondering whether there was supposed to be a question intended (since the video paused at the moment where the viewer is asked whether 275 should be tested).

Thanks!

**Comment by whtan99** [comment]
Update: After reloading the page multiple times and trying to get past the first quiz, the question finally loaded (have not encountered slow loading from other quizzes before). Perhaps the video should be changed to have the label Q+ instead to signal there are questions inside the video (since there is another question in the last 20s of the video)?

**Comment by damithc** [comment]
Good catch @goalfix I'll add the `Q+` in the next update of the website.

**Comment by whtan99** [comment]
Awesome! Thanks Prof @damithc, I'll close the issue now.

**Comment by damithc** [comment]
@goalfix A follow up: I recalled later that I did not mark this one with a `Q+` because 4 other videos for the same week have `Q+` already. So, while this video has some in-video quizzes, I didn't want to count it for participation.
