### ISSUE TITLE
Java CI gradle failing but no issues on local machine

### ISSUE THREAD

**Issue by NatalieTanML** [nus-cs2103-AY2122S2/forum#229]
Hello, I am currently facing some issues with Github Actions failing. [Here is the link to the workflow](https://github.com/AY2122S2-CS2103T-T13-3/tp/runs/5658003359?check_suite_focus=true).

I have tested it on my machine and I do not get any errors. It seems like the errors are related to the static objects after I updated them, but I'm not sure how to fix it/force clean(?) on Github's side. 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/43518715/159672318-61bcfbd0-cb9c-4f19-a3c8-246df0afa20f.png">

**Comment by domlimm** [comment]
Hey @NatalieTanML! I saw that you tried to re-run the CI but to no avail.

Could you in IntelliJ go to `File -> Invalidate Caches -> Invalidate and Restart` (ensure these 2 boxes are checked; In image below) and then go to your gradle panel look for `build -> clean` and try to run `test` locally again?

Let us know how it goes!

![image](https://user-images.githubusercontent.com/46486515/159675034-fde2f43d-fd29-465a-a111-aeb572502a45.png)

**Comment by NatalieTanML** [comment]
> Could you in IntelliJ go to `File -> Invalidate Caches -> Invalidate and Restart` (ensure these 2 boxes are checked; In image below) and then go to your gradle panel look for `build -> clean` and try to run `test` locally again?

Hi @domlimm, I just tried this out but I still managed to pass all the test cases locally.

**Comment by damithc** [comment]
> I have tested it on my machine and I do not get any errors. It seems like the errors are related to the static objects after I updated them, but I'm not sure how to fix it/force clean(?) on Github's side.

A caching problem is more likely to happen locally than on GitHub, as GitHub uses a clean slate for each CI run.

Also try deleting your local `build` folder and `output` folder (if any) manually.

**Comment by NatalieTanML** [comment]
Wow after a few hours of debugging and tracing through the errors, it seems like there were some locale issues from the GitHub Actions environment with regards to date time string parsing. Updating our date time string parser to enforce a 24-hour format and removing the AM/PM format somehow resolved this issue. 

Strangely enough even when i re-ran only the macOS GH action workflow it also broke there but on my local environment it was fine...
