### ISSUE TITLE
Error creating a `jar`

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#235]
Hey all,
Wanted to create a release for the tP by running `gradlew shadowJar`, but encountered the following error
```shell
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
```

This StackOverflow [post](https://stackoverflow.com/a/64533389/15781733) suggested updating the gradle distribution value in `distributionUrl` in `gradle/gradle-wrapper.properties`. 

If this was indeed the fix for the solution, what was the new gradle distribution used? 

Thanks in advance!

**Comment by waffledood** [comment]
hey guys, it's okay! I managed to fix the issue, i ran the command `gradlew shadowJar` in `tp/` & that's why i faced the error, i realized i could've just run the `shadowJar` command from the Gradle panel in IntelliJ! 

As a follow-up, is there a specific location in the repo to run the `gradlew shadowJar` command? or perhaps I've inputted the wrong command?

**Comment by yusufaine** [comment]
@waffledood thats a little weird, I run `./gradlew shadowJar` in the base directory of my TP and it works fine (running on MacOS, if it matters)

Could you perhaps try `./gradlew clean shadowJar`?

**Comment by waffledood** [comment]
@yusufaine I'm on Windows, so `gradlew clean shadowJar` but facing some other errors instead 😓 

```shell
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

**Comment by damithc** [comment]
@waffledood are you still facing this problem?
