### ISSUE TITLE
Assertions individual participation

### ISSUE THREAD

**Issue by reignnz** [nus-cs2103-AY2122S2/forum#236]
Hello may I ask for the assertions portion under individual deliverables, must it be added to our upstream repo or will it also be tracked from our individual tp repos? Thank you!

**Comment by damithc** [comment]
> Hello may I ask for the assertions portion under individual deliverables, must it be added to our upstream repo or will it also be tracked from our individual tp repos? Thank you!

@reignnz only code merged to the master branch of the team repo are considered in general, but for this case, the asserts also needs to in the code that is attributed to you. In other words, there should be asserts in the code that appears as yours in the tp code dashboard.
