### ISSUE TITLE
Randomly failing CI

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#237]
From time to time, Java CI will fail for no reason at all. Sometimes, it may be merging 2 PRs too quickly, or sometimes it may be for nothing at all. This has been extremely frustrating.

Over the past hour, I've gotten a string of failures, but I know for a fact that the code is correct and compiles because every single one of those failed CI runs only contain changes to the `UserGuide.md`.

![image](https://user-images.githubusercontent.com/13763067/160274606-c34ef976-734f-4da9-8252-216d72f3ce70.png)

![image](https://user-images.githubusercontent.com/13763067/160274726-23133526-8a3a-42b5-ae2e-e7798536baa3.png)

**Comment by yusufaine** [comment]
@TypeDefinition I'm facing the same issues as well but was able to push some PRs earlier without an issue. Chances are it's most-likely a GitHub issue as CI isn't able to get the gradle dependencies. Even if it's just a change to documentation, CI runs `./gradlew build` every time a push is detected.

**Comment by damithc** [comment]
Anyone else is facing similar problems? Also monitor https://www.githubstatus.com/ in case it's a problem on GitHub side.

**Comment by TypeDefinition** [comment]
> Anyone else is facing similar problems? Also monitor https://www.githubstatus.com/ in case it's a problem on GitHub side.

Hi prof, I think it's definitely GitHub's side. I re-ran some older commits that passed and they also failed now.

**Comment by lkldev** [comment]
From the error msg seems like it is coming from gradle instead, they are unable to pull some packages from their repo... tried to load them manually and couldn't connect to them as well

![image](https://user-images.githubusercontent.com/49238386/160275245-79b0d274-98dd-42bf-83b6-199dab8a83d3.png)

**Comment by yusufaine** [comment]
@TypeDefinition connection issue seems to have already been resolved and CI is working on my side.
