### ISSUE TITLE
Accidentally did fast forward merge - How to fix?

### ISSUE THREAD

**Issue by goalfix** [nus-cs2103-AY2122S2/forum#24]
Hey everyone, I think I accidentally did a fast forward merge instead of following the instructions specified in Week 3's project.

<img width="576" alt="Screenshot 2022-01-23 at 11 42 14 PM" src="https://user-images.githubusercontent.com/54658569/150686441-dd742aa9-3f45-4c8c-bda1-f3d8405ddeb1.png">

I have a couple questions:
1) Could someone more experienced confirm that I have done a fast forward merge between `master branch` and `branch-Level-7`?
2) Is it possible to "revert back" to the state of level 6, in order to do it in the correct manner?
3) How should I go about tagging for level 7? Because I did not create an extra merge commit, would it be okay to tag it in the fast-forwarded merge instead?

I was trying to follow the steps not to do a fast forward merge, but I got this window instead and just continued.
![Screenshot 2022-01-23 at 11 40 54 PM](https://user-images.githubusercontent.com/54658569/150686402-60c47243-50e7-4543-9285-9a7b0d271cd2.png)

Any help appreciated thanks!

**Comment by damithc** [comment]
@goalfix No need to rectify this. It will not affect your marks even if you used a fast-forward merge.
In future, if SourceTree GUI doesn't give you the option to not fast-forward, you can use the CLI to merge and use the `--no-ff` flag to prevent fast forwarding.

**Comment by goalfix** [comment]
Thanks Prof for the answer and tips!
