### ISSUE TITLE
Can we use GIFs in the User Guide?

### ISSUE THREAD

**Issue by bakano98** [nus-cs2103-AY2122S2/forum#245]
The GIF is to showcase how a particular command would work. GIFs are also a better visual aid for the user, as compared to a screenshot which is static.

Plus, it declutters the user guide as you would not need to have so many screenshots to show the user.

**Comment by damithc** [comment]
@bakano98 Indeed, gifs can be useful for that purpose. Unfortunately, the UG and DG are to be submitted to LumiNUS as PDF files; so, can't use gifs. Hence, the following constraint:

![image](https://user-images.githubusercontent.com/1673303/161003020-ded12c4f-6eb9-4997-a353-92461c25e576.png)
