### ISSUE TITLE
Improving code design `v1.4`

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#246]
Hello prof,

Are we allowed to add or shift codes around for improving the codebase's design to fit our DG's UML diagrams?

For example, defensive programming via `getters`, `setters` or `accessors`.

Thanks prof!

**Comment by damithc** [comment]
@domlimm Yes, you are allowed to _refactor_ the code if that doesn't affect the external behavior of the software.

**Comment by domlimm** [comment]
Noted, thanks prof! 😃
