### ISSUE TITLE
change java version in windows

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#247]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

Hi, I am having difficulty trying to change the java version to 11.

I have downloaded java installer for version 11 in oracle,
set JAVA_HOME variable to the java folder in the environment settings, and PATH variable to the bin folder for java 11 installed.
Below is the article i followed.
https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/

However, when I type `java -version` in PowerShell, I still get notified that the version I am using is 16(the default).

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by damithc** [comment]
@B1LLP4RK Remember to restart your terminal (e.g., PowerShell) after setting those environment variables.

**Comment by B1LLP4RK** [comment]
@damithc That was the part I missed. Thank you!
