### ISSUE TITLE
Modifying JSON during testing for PE

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#248]
Will this count as a bug:

As a tester, I go into the JSON file to modify a value of an attribute to some invalid value.
When I open the application I am testing, it should show an error message referring to an invalid value that exists in the json file in the results display.
But it does not display that, will that be considered a bug?

**Comment by zhongfu** [comment]
does #243 answer your question?

**Comment by hsiaojietng** [comment]
> does #243 answer your question?

Yup thanks for this!
