### ISSUE TITLE
Do we have to refute the bugs for PE-D?

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#249]
Will we lose marks at the end of the day if we do not refute the bugs found in PE-D and it shows up again in the actual PE?

**We disagree with some of the bug reports and do not feel a need to do anything about it, but are afraid that this will be counted as not "fixing" them if we do not close or refute it.**

**Comment by damithc** [comment]
@TypeDefinition there is no need to refute PE-D bugs. There is no penalty for receiving or not fixing PE-D bugs.

But if the same bug is reported again at the PE, you'll have to refute it then. Refuting it now will have no effect on the PE as PE testers are different from PE-D testers and PE bugs do not come to your own issue tracker anyway. PE bugs will be kept in a separate issue tracker and you will be submitting your response to those bugs using CATcher.

**Comment by TypeDefinition** [comment]
Thanks prof!
