### ISSUE TITLE
Jar file cannot find path

### ISSUE THREAD

**Issue by ryanwalterlee** [nus-cs2103-AY2122S2/forum#25]
As stated in the moreOOP level, a storage class is needed to handle file reading and writing.

The thing is, when i run duke.main, it works, but upon creating the jar file, it gives the error

"Exception in thread "main" java.io.IOException: The system cannot find the path specified
        at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1043)
        at duke.Storage.readFile(Storage.java:13)
        at duke.Duke.main(Duke.java:21)"

This means that the file path to be read which is "src/main/data/duke.txt" works in run duke.main but not in the jar file. 

I suspect that it has something to do with how the artifact settings are set and where the manifest.mf file is.

Currently my folder structure looks like that, not sure if main is supposed to be a module (after doing A-JUnit)
![image](https://user-images.githubusercontent.com/88182652/150692961-053ebc62-908c-4bed-9aac-367219ecdf7a.png)

On that note, if we are stuck on a level, can we do the next levels first? Will we be penalized by the grading script?

**Comment by Yukun99** [comment]
have you made sure that your jar file is running in the same directory as your project? If not that path would not exist. A better solution would be to perhaps use the directory that the jar file/program is being run in as the base directory, and then read from a data folder in that folder.

**Comment by ryanwalterlee** [comment]
I did what was stated in the youtube tutorial on the link on A-Jar level, which is to copy paste the path of the jar file followed by java-jar path/path/path

**Comment by Yukun99** [comment]
Where is your jar file stored right now?

**Comment by zhongfu** [comment]
> I did what was stated in the youtube tutorial on the link on A-Jar level, which is to copy paste the path of the jar file followed by java-jar path/path/path

is your current directory `C:\Users\user\OneDrive\Documents\CS\CS2103\ip`, or is it somewhere else? if that isn't your current directory, then change your directory to that before running `java -jar ...` (with the appropriate path for your jar file) again

**Comment by ryanwalterlee** [comment]
@zhongfu I don't think the issue is that the computer cannot find the jar file, rather, after it found it, it cannot navigate the file path for the reading of data.txt.

**Comment by zhongfu** [comment]
> @zhongfu I don't think the issue is that the computer cannot find the jar file, rather, after it found it, it cannot navigate the file path for the reading of data.txt.

that's not what I meant -- `src/main/data/duke.txt` is a relative path, so if your current/working directory isn't `C:\Users\user\OneDrive\Documents\CS\CS2103\ip`, your program isn't going to be able to find your file (or `src`, or `src/main`, etc)

**Comment by damithc** [comment]
@ryanwalterlee After you've solved this problem, also consider what will happen if someone else take your JAR file, put it in some random folder, and run it in there. Will it work even though that person doesn't have `src/main/data/duke.txt` to begin with? If it doesn't, your Level-7 is not done correctly.

**Comment by ryanwalterlee** [comment]
Solved: created JAR file out of main module (not ip module), also reconfigured the storage class to create a data folder + duke.txt folder in it if it does not exist so that if someone else downloads the JAR it can still be used. Thanks all for the help :)
