### ISSUE TITLE
"Handling manual edits to the data file." not in TP expectations.

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#251]
In the TP, this was an requirement.
![image](https://user-images.githubusercontent.com/13763067/161310981-ef03cfac-14a4-4888-8302-c34a99bcb262.png)

But it was not stated as requirement in the TP expectations.
https://nus-cs2103-ay2122s2.github.io/website/admin/tp-expectations.html

Our team decided early on to save our data file as a binary as it was not a requirement to save as a `.json`, and it is too difficult to convert to a `.json` at this point in the project.

**Comment by damithc** [comment]
@TypeDefinition it was stated in tP constraints `Constraint-Human-Editable-File`

https://nus-cs2103-ay2122s2.github.io/website/admin/tp-constraints.html

**Comment by TypeDefinition** [comment]
> @TypeDefinition it was stated in tP constraints `Constraint-Human-Editable-File`
> 
> https://nus-cs2103-ay2122s2.github.io/website/admin/tp-constraints.html

Hi prof, what if it is impossible for us to change it at this point?

**Comment by damithc** [comment]
@TypeDefinition you can leave it as is. It is a feature flaw (not allowed to be fixed in v1.4 anyway). The severity depends on how much it impacts your target audience. If it is reported again in the PE, it will have to be accepted. But unlikely it will affect your marks by itself, as marks are deducted only when the total bug impact exceeds a certain threshold.

**Comment by TypeDefinition** [comment]
> @TypeDefinition you can leave it as is. It is a feature flaw (not allowed to be fixed in v1.4 anyway). The severity depends on how much it impacts your target audience. If it is reported again in the PE, it will have to be accepted. But unlikely it will affect your marks by itself, as marks are deducted only when the total bug impact exceeds a certain threshold.

Thanks prof!
