### ISSUE TITLE
Will all bugs/issues reported in PE-D be transferred over?

### ISSUE THREAD

**Issue by AAlghrairy** [nus-cs2103-AY2122S2/forum#252]
Will all issues that testers find be transferred to our team's repository, or will only some be transferred?

**Comment by AAlghrairy** [comment]
Yes they are apparently. The issues are just not loaded at the same time.

**Comment by damithc** [comment]
All bugs will be transferred but it will take time to finish (GitHub API doesn't allow creating more than 150 issue per hour).
