### ISSUE TITLE
Would this be considered a functionality bug?

### ISSUE THREAD

**Issue by NatalieTanML** [nus-cs2103-AY2122S2/forum#253]
In one of our PE-D issues, a user mentioned allowing URLs to be entered without having to prefix it with `https://`. This was our intended use, but we overlooked this check in our validation. Would we still be allowed to fix this in v1.4? The user tagged it as a feature flaw, but we consider it to be a functionality bug instead.

**Comment by damithc** [comment]
@NatalieTanML does the following cover this case? (from https://nus-cs2103-ay2122s2.github.io/website/schedule/week12/project.html)

![image](https://user-images.githubusercontent.com/1673303/161376035-7ea0ac23-cd6e-422b-8f19-887dbe316b25.png)

**Comment by NatalieTanML** [comment]
Yes, it does cover the case mentioned. Thank you.
