### ISSUE TITLE
How to show multiple spaces in Markdown inside a code block

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#255]
Hi, I am trying to polish the UserGuide for the team project.
I have come across this task to write that
't/        ' is essentially the same as 't/'. 
The point is that I wanted to express that trailing spaces will be ignored.
Apostrophes was used above instead of backtick so that you can see my intention.

And the above gets shown as
`t/      `  is essentially the sase as `t/`.
Is there a way around this? I tried using `&nbsp;` but it didn't work inside a code block.

**Comment by Punpun1643** [comment]
Not sure if I understand correctly, but are you trying to show the trailing spaces but cannot show them in the UG?

You can probably try using `<code></code>` and `&nbsp;` together.

For example:

`<code>t/&nbsp;&nbsp;&nbsp;</code>` should produce <code>t/&nbsp;&nbsp;&nbsp;</code>

**Comment by B1LLP4RK** [comment]
@Punpun1643  Managed to describe in other means, but this is definitely something I would try in the future!
