### ISSUE TITLE
Where to draw the line between functionality bug and feature flaw?

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#258]
@damithc 
Hi prof, I have 2 bug reports from PE-D which I am unsure to classify it as a functionality bug (which I can fix), or a feature flaw (which I'm not allowed to fix). May I have your opinion on them? Thank you!

Bug reports:
![image](https://user-images.githubusercontent.com/13763067/162012224-bfb9cc5b-fd97-4b3a-b564-554a8a722a3d.png)

![image](https://user-images.githubusercontent.com/13763067/162012462-8c93ffcb-6582-4f43-b069-6a505056ed0a.png)

UG:
![image](https://user-images.githubusercontent.com/13763067/162012642-cc5d8be0-1e15-4046-ba24-9c901af042eb.png)

**Comment by damithc** [comment]
@TypeDefinition what's the current behavior for these two commands?

**Comment by TypeDefinition** [comment]
@damithc Hi prof, currently this is what they show:

![image](https://user-images.githubusercontent.com/13763067/162017864-98e278b5-4349-4f37-b8cc-cab0b0cdb05e.png)

![image](https://user-images.githubusercontent.com/13763067/162017904-95d0747b-95d4-474c-a5c6-844abfaeded0.png)

**Comment by damithc** [comment]
@TypeDefinition perhaps you can treat this as a UG bug, and update it to specify that `t/` is not supported? `t/` doesn't do anything useful anyway, right?

**Comment by TypeDefinition** [comment]
@damithc Alright, thanks prof!
