### ISSUE TITLE
How do you make the batch file run with the same relative path?

### ISSUE THREAD

**Issue by jaysmyname** [nus-cs2103-AY2122S2/forum#26]
I've coded the file writing method such that it works when I run it on intelliJ, using the relative path "data/xxxx.txt", but when I run the runtest.bat file in text-ui-test, it produces errors since as it can't find the same path to the file.

How do I go about fixing this?

**Comment by pyk595** [comment]
Hi, I wrote a tip in #27, but it's for the shell file, you can take a look and see if it helps!

**Comment by damithc** [comment]
@jaysmyname does it still work if you delete the data/xxxx.txt and run using Intellij?

If not, you may have missed this point in Level-7
![image](https://user-images.githubusercontent.com/1673303/150738842-09471282-550c-4857-bac1-073a3e7e940b.png)

**Comment by jaysmyname** [comment]
Ah, I did handle the case where the text file didn't exist, but not the ./data/ folder itself, thanks!
