### ISSUE TITLE
Feature Freeze Related Question : Limiting digits in phone number

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#261]
Hi everyone, i want to ask whether limiting digits (maybe limiting to 10 digits) for phone numbers is allowed in the feature freeze?

This is one of the bugs reported.

**Comment by damithc** [comment]
@albertsutz this feels like an enhancement rather than a bug, unless longer phone numbers cause the software to misbehave in some way. 
On a related note, as a user, I prefer to have the flexibility to decide what I want to store as the phone number e.g., `1234-5678 (call only after office hours)`

**Comment by albertsutz** [comment]
I see. My team and I also suspect that it is an enhancement. Then I will say that even the issues reported are a bit subjective and can differ with different users (considering your note).

**Comment by damithc** [comment]
> Then I will say that even the issues reported are a bit subjective and can differ with different users (considering your note).

@albertsutz Yes that's correct. Depends on your target users, the way the telephone number is displayed, how you expect the user to make use of the telephone number etc. 
BTW, PE-D issues may not be correct or could be mislabeled; you'll have to decide for yourself what's the true nature of the issue.

**Comment by albertsutz** [comment]
Thank you!
