### ISSUE TITLE
Would this be considered a functionality bug? 

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2103-AY2122S2/forum#262]
Hi prof, could you help clarify if this would be considered a functionality bug or a feature flaw (i.e. can we fix it)?

![1](https://user-images.githubusercontent.com/77227570/162364316-9881683b-e50b-447e-8fed-8b43623f76df.png)

**Comment by damithc** [comment]
@cindyangXQ This can be considered a bug if this (i.e., setting preference bound above the higher price) causes the app to behave incorrectly (or in an unexpected way) later.

**Comment by cindyangXQ** [comment]
Thank you.
