### ISSUE TITLE
Implementation of `remark` command from the tutorial in tp

### ISSUE THREAD

**Issue by charmainehly** [nus-cs2103-AY2122S2/forum#264]
Hi!

I wanted to make some quick clarifications on the reuse of the `remark` command from AB3 based on the tutorial in our tp:

Given as this is an implementation from AB-3, apart from ensuring that any repeated code snippets/code blocks (without major modifications) do not appear under our name in the code dashboard, would it be right to take it that this would otherwise not fall under the criterion for 'code re-use'?

Thank you!

<img width="697" alt="Screenshot 2022-04-08 at 8 59 15 PM" src="https://user-images.githubusercontent.com/65525578/162440457-9164cc24-79f9-4de8-83bb-5bee75f7f3af.png">

**Comment by damithc** [comment]
@charmainehly yes, that's right.

**Comment by charmainehly** [comment]
thanks prof!
