### ISSUE TITLE
Clarification on the product name in tP final submission

### ISSUE THREAD

**Issue by ngjunkang** [nus-cs2103-AY2122S2/forum#266]
@damithc For the product name in file submission, do we have to follow what we submitted in TEAMMATES on week 4? If so, will testers receive the file with the product name? Then we need to change the instructions in UG Quick Start?

**Comment by damithc** [comment]
@ngjunkang If you have changed the name, let us know so that we can update in https://nus-cs2103-ay2122s2.github.io/website/admin/teamList.html

Other than that, the product name in you documentation should match the JAR filename and the product name shown in the UI.

**Comment by ngjunkang** [comment]
Okay thank you!
