### ISSUE TITLE
Troubleshooting for runtest.sh after refactoring into packages💡

### ISSUE THREAD

**Issue by pyk595** [nus-cs2103-AY2122S2/forum#27]
Hi everyone!

I was working on the extension `A-More-OOP` and `A-Packages` so I refactored some of my classes. Even though I manage to get the expected output when running `Duke.main()`, I was unable to properly run `runtest.sh`, because it kept showing a runtime error. 

After investigating, I realised that the bin still contained the deprecated class files from the previous increments, which caused the runtime error because the code is no longer valid. 

For people with this error, you can run `rm -r ./bin` in console, and rebuild your `text-ui-test`. 

Check and make sure that your path is correct for your `javac` and `java` command.

For the `java` command, run with the `/bin packageName.javafile` instead of `/bin/packageName javafile`.

Hope this helps!

**Comment by damithc** [comment]
Thanks for sharing this @pyk595
