### ISSUE TITLE
Reusbmission of PPP

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#272]
Hi sir @damithc , I realized I have a mistake in PPP file that I have submitted, and fixed it.
Can I just submit the new version again, or is there something else I have to do?

**Comment by damithc** [comment]
Sure, you can delete the previous submission (if LumiNUS allows it) and submit again.

**Comment by B1LLP4RK** [comment]
tq prof @damithc !
