### ISSUE TITLE
Source Code portion for submission of deliverables

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#273]
Hello prof, may I ask what does this mean?

Is it related to the team's release for `v1.4`?

Thank you!

![image](https://user-images.githubusercontent.com/46486515/162760451-e788b987-eff5-4ac1-a70c-2fb63786d952.png)

**Comment by damithc** [comment]
@domlimm Yes, basically, ensure that GitHub has the latest code of your `v1.4` (that matches the PDF and JAR files that you uploaded to LumiNUS) and the code is divided correctly among the team members (as shown by the code dashboard).

**Comment by bingsen0806** [comment]
Hi @damithc , if I already created a v1.4 release on github, but later made minor edits to my UG and DG (no code at all) before submitting to LumiNus, do I need to delete my old v1.4 release and create a new v1.4 release based on the newest commit before uploading to luminus?

**Comment by damithc** [comment]
> Hi @damithc , if I already created a v1.4 release on github, but later made minor edits to my UG and DG (no code at all) before submitting to LumiNus, do I need to delete my old v1.4 release and create a new v1.4 release based on the newest commit before uploading to luminus?
@bingsen0806 You can do another release e.g., `v1.4.1` while keeping the previous. You can create the release *after* uploading to LumiNUS

**Comment by domlimm** [comment]
@damithc noted on it! thanks prof!

@bingsen0806 closing the issue as prof has answered your query too!
