### ISSUE TITLE
Are broken/incorrect links in the UG/DG counted as a Low or Very Low severity bug?

### ISSUE THREAD

**Issue by NatalieTanML** [nus-cs2103-AY2122S2/forum#274]
For example, the UG/DG contains links to AB-3's repo instead of the group's repo, or the link is not working. 

Would this be considered a `Low` or `Very Low` severity bug?

**Comment by damithc** [comment]
@NatalieTanML it'll depend on how much inconvenience is caused by the broken link (case-by-case).
