### ISSUE TITLE
CATcher cannot assign myself to a issue

### ISSUE THREAD

**Issue by Rye-Catcher** [nus-cs2103-AY2122S2/forum#276]
When I tried to assign myself to a PE bug in its response. It shows:

![image](https://user-images.githubusercontent.com/35390703/163701186-76439ea6-971c-4d07-a033-1f85f3bad70a.png)

**Comment by damithc** [comment]
@Rye-Catcher Another team reported a similar issue. You can follow it in https://github.com/CATcher-org/CATcher/issues/925

Are you able to assign other team members?

**Comment by Rye-Catcher** [comment]
> @Rye-Catcher Another team reported a similar issue. You can follow it in [CATcher-org/CATcher#925](https://github.com/CATcher-org/CATcher/issues/925)
> 
> Are you able to assign other team members?

Out of 5 team members, I am able to only assign the issue to one specific member. Trying to assign the issue to any one of the other 4 members will pop up the similar window

**Comment by damithc** [comment]
@Rye-Catcher CATcher team has pushed a fix. Can you try again now? You might have to do a hard refresh of the page first, in case of caching issues.

**Comment by Rye-Catcher** [comment]
> @Rye-Catcher CATcher team has pushed a fix. Can you try again now? You might have to do a hard refresh of the page first, in case of caching issues.

Thank you, prof! It works right now.
