### ISSUE TITLE
Is it wise to assign all members to a bug?

### ISSUE THREAD

**Issue by lzan98** [nus-cs2103-AY2122S2/forum#278]
Hi Prof @damithc !

Does assigning all members to a bug mean we are putting everyone in the team at a disadvantage in terms of penalty?

For example, our team feels that it is not fair to assign one member to a particular documentation bug just because he/she wrote the section, as none of us picked it up during our final checks.

Thank you!

**Comment by damithc** [comment]
@lzan98 the penalty will be divided among those assigned to the bug. e.g., if the penalty for the bug is -0.5 marks and there are five assigned to it, each person will be penalized -0.1 marks.
We don't impose any restrictions on how many or who are assigned to a bug.

**Comment by lzan98** [comment]
Thank you prof for the clarification 😄
