### ISSUE TITLE
Are User stories included in the documentation but not implemented considered a bug?

### ISSUE THREAD

**Issue by michaelseyo** [nus-cs2103-AY2122S2/forum#279]
Are user stories included in the documentation but not implemented in our actual app be considered a bug? Because I was thinking that user stories presented in the documentation are just a mere guide during our brainstorming and not necessarily had to be implemented.

**Comment by damithc** [comment]
@michaelseyo The _Requirements_ section of the DG is not limited to the current implementation, as we need to document not-yet-implemented requirements as well. Therefore, it is not a bug to have unimplemented user stories in that section.

**Comment by michaelseyo** [comment]
@damithc Thanks for the quick reply and clarification prof!
