### ISSUE TITLE
the meaning of -u in 'git push -u {remote} {branch}'

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#28]
Hi all, I am trying to understand what the -u option does in the command 'git push -u {remote} {branch}'

I know, the module website does specify

>If pushing a branch you created locally to the remote for the first time, add the -u flag to get the local branch to track the new upstream branch:

The also looked at the documentation, which says

>-u
>--set-upstream
>For every branch that is up to date or successfully pushed, add upstream (tracking) reference, used by argument-less git-pull[1] and other commands. For more information, see branch.<name>.merge in git-config[1].

However, both didn't really get to me... I would be happy if someone can explain what 'track the new upstream branch' specifically means, or how does it affect what I can do, or my local/remote git repo!

**Comment by damithc** [comment]
Good questions @B1LLP4RK It provides a good opportunity for others to share their Git knowledge. Let's wait to see who can help out ...

**Comment by lzan98** [comment]
I will try attempt to explain in simple terms using an example: 

Let's say you want to push branch-Level-9 to GitHub and you run `git push origin branch-Level-9` (without the -u flag).
When you try to run `git pull`(while in branch-Level-9), you will be prompted with the following message:

>There is no tracking information for the current branch.
>Please specify which branch you want to merge with.
>See git-pull(1) for details.
>
>    git pull <remote> <branch>
>
>If you wish to set tracking information for this branch you can do so with:
>
>    git branch --set-upstream-to=origin/<branch> branch-A-JavaDoc

In contrast, if you ran `git push origin -u branch-Level-9`, the next time you run `git pull` from branch-Level-9, it will run successfully and treated as `git pull origin branch-Level-9`(likewise for git push).

Read more from StackOverflow [here](https://stackoverflow.com/questions/5697750/what-exactly-does-the-u-do-git-push-u-origin-master-vs-git-push-origin-ma/16018004#16018004). The top 3 answers are pretty well explained.

**Comment by clement0010** [comment]
Adding on to what @lzan98 said, 'track the new upstream branch' means creating a connection between your new local branch and remote branch (upstream). See diagram below.

![image](https://user-images.githubusercontent.com/56408987/150775287-c8fe53d3-0481-42e0-bb6e-4efdabab8cec.png)

This connection lets you obtain information from your remote repositories, such as telling you if your commits are ahead/behind the remote branch. For example, in a project collaboration scenario, you will most likely be working on the same branch with other people and there will be frequent pushes on the same branch. Hence, when performing a "git fetch" command, you can bring the new commits from your remote repository and you can choose to merge them at will.

Another reason is that you can perform git pull and push quickly as git already knows which upstream branch to push/pull from.

You can read more from [here](https://www.git-tower.com/learn/git/faq/track-remote-upstream-branch)

**Comment by B1LLP4RK** [comment]
@lzan98 , @clement0010  Thank you both for answering my question and shedding light both on how it affects my future commands and theoretical aspect. The links were useful too. Have a great day:D
