### ISSUE TITLE
Incorrect bug type in phase 2

### ISSUE THREAD

**Issue by cheehongw** [nus-cs2103-AY2122S2/forum#283]
My group received several bugs in phase 2 mislabeled as a `FunctionalityBug` although it describes a `DocumentationBug`

Do we have the right to reject these based on phase 2 rules?

**Comment by damithc** [comment]
@cheehongw If a bug label is incorrect, change it to the correct label. You can reject a bug report only if it is _not a bug_ (as per the PE rules) -- having the wrong label is not enough to reject the bug.
