### ISSUE TITLE
Do we need to change the severity when rejecting a bug?

### ISSUE THREAD

**Issue by DALIN-Prog** [nus-cs2103-AY2122S2/forum#285]
Hi Prof, can I check if there is a need to change the severity when rejecting a bug? 

If it is not, is there any implication in changing the severity when say my group's true intention to reject the bug because we disagree with the bug reported i.e, we felt that it is not a bug (and not because we disagree with the severity)?

Thank you

**Comment by damithc** [comment]
@DALIN-Prog yes, it is advisable to do so. More info:

![image](https://user-images.githubusercontent.com/1673303/163917138-6dcdcf5a-5f13-4468-a1d8-f8274d0213c7.png)
