### ISSUE TITLE
Including links to recordings located elsewhere (i.e. not on GitHub) in PE responses

### ISSUE THREAD

**Issue by zhongfu** [nus-cs2103-AY2122S2/forum#286]
One of the issues that I have filed during a PE involves a long hang under certain circumstances; I intend to submit some screen recordings of the issue occurring on multiple platforms to substantiate the report (together with an explanation, of course).

However, long recordings will likely not be accepted by CATcher since it apparently [only allows files up to 10Mb (megabits? megabytes?) in size](https://nus-cs2103-ay2122s2.github.io/website/admin/tp-pe.html#pe-d-preparation). In this case, would it be acceptable to include links to (unlisted) YouTube videos? If not, is there any other method that I am allowed to use to submit longer screen recordings (with a length of up to 15 minutes)?

**Comment by damithc** [comment]
@zhongfu it is fine to link to externally hosted videos in your response.

**Comment by zhongfu** [comment]
Thanks prof!
