### ISSUE TITLE
Will TA look through justification for all duplicate bugs, if Master copy is already accepted as it is?

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#287]
Basically I reported a bug that is not cosmetic issue as low severity, and the developers marked it as duplicate of another very low severity report. The developers also accepted the very low bug as it is.

While I agree with the duplicate status, I do not agree that the bug should be very low.

Will the TA still look through my justification, and (possibly) change it back to low, since I accepted the duplicate status and the master copy is very low and already accepted as it is.

**Comment by damithc** [comment]
@bingsen0806 please email me the link to the issue in concern. I would like to have a look at the details first.

**Comment by bingsen0806** [comment]
Thank you prof, aside from this I have another similar question.

What if the developer changes something (did not accept as it is), will justifications from all duplicates still be read (instead of only master copy)?

For example, if developer changes a feature flaw to documentation bug (both master and child copies of the duplicate are initially feature flaws), if the tester for master copy agrees, but tester for the child copy thinks that it should still be a feature flaw, will the justifications of the second tester be read?

**Comment by damithc** [comment]
> What if the developer changes something (did not accept as it is), will justifications from all duplicates still be read (instead of only master copy)?

Yes, all disputes from all testers will be assessed independently. It doesn't matter if you are the one who reported the master copy or the duplicates (they are all treated equally).

**Comment by damithc** [comment]
> While I agree with the duplicate status, I do not agree that the bug should be very low.
> 
> Will the TA still look through my justification, and (possibly) change it back to low, since I accepted the duplicate status and the master copy is very low and already accepted as it is.

@bingsen0806 You can respond to each case separately (you can agree with one and disagree with the other), and all those disagreements will be evaluated by the teaching team.

**Comment by bingsen0806** [comment]
Thank you prof
