### ISSUE TITLE
Question on counter-argument for three-way duplicate bugs

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY2122S2/forum#288]
Hi Prof,

Suppose the dev team marks issues A and C as duplicates and issues B and C as duplicates. If I think A and B are duplicates but are independent from C, then it turns out that's not the case, will that count as 2 incorrect counter-arguments or one? It's the same counter-argument but I would need to respond to two duplicate markings separately in this case.

Thank you!

**Comment by damithc** [comment]
@sibinhho99-nus each duplicate _pair_ is considered independently. Does that answer your question? If not, feel free to ask follow up questions.

**Comment by ghost** [comment]
Hi Prof. Yes, that answers my question.
