### ISSUE TITLE
Question regarding grammar issue in the application

### ISSUE THREAD

**Issue by snoidetx** [nus-cs2103-AY2122S2/forum#289]
Hi prof,

I would like to ask if there is some grammar issue in the application itself that may cause inconvenience to users (not the documentations), should it be tagged as `FeatureFlaw` or `FunctionalityBug`? I prefer the first one because it seems like a feature to be improved instead of a wrong functionality.

**Comment by damithc** [comment]
@snoidetx Grammar errors are errors in the current implementation, hence `FunctionalityBug`.

**Comment by snoidetx** [comment]
Thank you prof!
