### ISSUE TITLE
Mixed up `FeatureBug` and `FunctionalityBug` type

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#290]
Hello prof,

Can the dev team reject bug reports because it has been tagged wrongly for the `type`? However, the content/description of the bug report is valid in my opinion.

I might have mixed up the title mentioned types.

Thanks!

**Comment by zhongfu** [comment]
No, see #283

**Comment by domlimm** [comment]
@zhongfu thank you!!! should've checked other issues before posting oops... 😢
