### ISSUE TITLE
Rejecting Dupicate when the dev response is not clear

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#292]
Hi, so I submitted 2 issues for the same reason (case insensitivity) but for different things (2 different parameters of the same command). The dev has responded to consider both issues as duplicates, but has not shown any proof. How do I know whether it can be fixed independently or not?

**Comment by damithc** [comment]
@albertsutz You can disagree if you suspect the two problems _can_ be fixed independently from each other. In your response you can state that the team hasn't shown any proof that the two actually the same bug. The burden of proof lies with the dev team, not the tester.

**Comment by albertsutz** [comment]
Thanks prof!
