### ISSUE TITLE
Use of roles and navigability in class diagram

### ISSUE THREAD

**Issue by jxt00** [nus-cs2103-AY2122S2/forum#294]
Hello, would like to clarify my doubts on this.

These diagrams and codes are taken from the textbook sections `Roles` and `Navigability`.

1. Given that `Man` and `Woman` each contains references to each other, would it be acceptable to add bidirectional arrows to the class diagram? (i.e similar to the ones in the `Dog` and `Man` UML.)
2. Would it also be acceptable to add the roles (e.g. `pet` and `owner`) to the `Dog` and `Man` UML?
3. Is it acceptable to use both roles and navigability in a single class diagram? (I do not think they are inter-changeable right?)

Thank you!

![image](https://user-images.githubusercontent.com/44643248/165519894-f844f8f2-5708-4935-ae65-6b1855bd9f0c.png)
```java
class Man {
    Woman wife;
}

class Woman {
    Man husband;
}
```

![image](https://user-images.githubusercontent.com/44643248/165519919-e2cfe4d5-01ad-488c-b981-ab1d801744a7.png)

```java
class Dog {
    Man man;
    // ...
}

class Man {
    Dog dog;
    // ...
}
```

**Comment by damithc** [comment]
@jxt00 Yes to all three questions.

**Comment by jxt00** [comment]
Thank you prof!
