### ISSUE TITLE
Clarification on answer: Practice Quiz 1

### ISSUE THREAD

**Issue by kavxya** [nus-cs2103-AY2122S2/forum#295]
<img width="1255" alt="Screenshot 2022-04-29 at 2 34 54 PM" src="https://user-images.githubusercontent.com/57605345/165895657-fb3b7f38-334b-492d-9ca9-c2781d479f86.png">

Hi! Can anyone help to confirm if the correct answer is magic numbers and SLAP as written on the comments or SLAP and coupling as seen on the quiz!

Thank you!

**Comment by domlimm** [comment]
Hello @kavxya, I don't think `SLAP` should be the answer.

[SLAP](https://nus-cs2103-ay2122s2.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard) is encouraged, so not to be avoided/minimised. I believe!

Anyone else please feel free to chime in!

![image](https://user-images.githubusercontent.com/46486515/165896127-b6edf05f-96ed-416a-9de7-bddcfde5e32f.png)

**Comment by ckcherry23** [comment]
Hi @kavxya!
I think SLAP and magic numbers should be the right answer.
I believe coupling is more of a design concept and it also comes under **Design Fundamentals** in the textbook.

<img width="287" alt="Screenshot 2022-04-29 at 2 46 14 PM" src="https://user-images.githubusercontent.com/68203159/165896605-2300af3e-aa4d-4c42-920d-4caa2b23c2af.png">

**Comment by damithc** [comment]
@kavxya don't confuse the main question with the justification. In this particular case, they are two different questions altogether.

**Comment by kavxya** [comment]
Thank you for the clarification!

**Comment by domlimm** [comment]
@damithc hello prof, I just attempted this question and got it wrong too. Does that mean in the quiz we need to answer the question, X, in the `Justification: X` instead of answering based on the main question?

EDIT: Seems like it!

**Comment by damithc** [comment]
(main question) to be avoided/minimized: magic numbers, coupling  -- select these options
(justification) more related to coding: magic numbers, SLAP  -- write these in the text box
