### ISSUE TITLE
Renaming Duke.java

### ISSUE THREAD

**Issue by jaysmyname** [nus-cs2103-AY2122S2/forum#3]
Can we rename the java project file to anything else? Basically changing the name of the bot including the filename to Marcus.java for example.

**Comment by damithc** [comment]
Sure @jaysmyname 
Renaming the bot is in fact encouraged.
Renaming the .java file is allowed.
Just don't rename the fork: it should remain `ip`

**Comment by jaysmyname** [comment]
Got it, thank you!
