### ISSUE TITLE
Mock Quiz Question 2

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#302]
![image](https://user-images.githubusercontent.com/71639142/166206220-0568b551-df1e-4176-8724-2cd53654303e.png)

According to Luminus, the correct answer is line 1 and 2.

Is it correct to also say line 4 has coding standard violation because the variable named "FILE_SIZE" should also be changed there. If similar questions regarding coding violations on variable naming comes out in exam, should we only choose the line where the variable is first declared?

**Comment by damithc** [comment]
> If similar questions regarding coding violations on variable naming comes out in exam, should we only choose the line where the variable is first declared?

Good question @bingsen0806 . Yes, select only  the line(s) that 'violated' the standard, not the the lines that are affected by the violation.

**Comment by bingsen0806** [comment]
Thank you prof
