### ISSUE TITLE
Mock Exam Q3

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#304]
Hello, is 29 accepted too based on my justification? Though 2 is definitely closer to 5.

My initial thought is the equivalence partition for `day` would be [1..31]. The boundary values would be 1 and 31, and the rest should be non-boundary values. Hence, 29 could be right too..?

Not too sure..

Appreciate any inputs, thank you!

![image](https://user-images.githubusercontent.com/46486515/166401619-2117d5b8-9c97-4cb0-b9d0-4b404b22e323.png)

**Comment by pyk595** [comment]
29 is a special day because of the leap day thing for February, probably why they put it in a separate EP for itself

**Comment by domlimm** [comment]
> 29 is a special day because of the leap day thing for February, probably why they put it in a separate EP for itself

Oh yes you're right... Thanks so much @pyk595!!!
