### ISSUE TITLE
Practice Exam Part 1 Q16

### ISSUE THREAD

**Issue by snoidetx** [nus-cs2103-AY2122S2/forum#305]
Isn't line 4 also wrong because the letter 's' of "string" should be capitalised according to [Java coding standard](https://se-education.org/guides/conventions/java/basic.html#comments)? 

<img width="1686" alt="Screenshot 2022-05-03 at 1 48 40 PM" src="https://user-images.githubusercontent.com/71825567/166409552-63eed946-3c27-4adf-8b96-098ff3133fed.png">

Also, I chose line 6 and 8 as well because I do not think `abcd` is a meaningful name. Are we supposed to ignore such things in the exam?

**Comment by damithc** [comment]
Good catch @snoidetx 
Corrected it just now.
![image](https://user-images.githubusercontent.com/1673303/166412029-c0a96d19-77ed-4f07-a3a1-eccbba406c1a.png)

**Comment by snoidetx** [comment]
Thank you prof! How about my second concern about the naming of `abcd`? Why are we not supposed to concern about it in this scenario? 🤔

**Comment by damithc** [comment]
> Thank you prof! How about my second concern about the naming of `abcd`? Why are we not supposed to concern about it in this scenario? 🤔

@snoidetx This question is about coding standard violations, not code quality in general.

**Comment by snoidetx** [comment]
Thank you prof very much! I get it!
