### ISSUE TITLE
Coding Vs Design

### ISSUE THREAD

**Issue by aweijun** [nus-cs2103-AY2122S2/forum#306]
Hi, I was just wondering why is coupling under coding instead of design?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/95308604/166413883-2e3c2e46-e44e-4c19-b645-ac8b7b470607.png">

**Comment by damithc** [comment]
@aweijun Does [this issue](https://github.com/nus-cs2103-AY2122S2/forum/issues/295) answer your question?

**Comment by ngjunkang** [comment]
The main question (which of these are to be avoided/minimised) is a different question from the justification question (answer should be SLAP and magic numbers).

**Comment by aweijun** [comment]
Ok thanks prof, so sorry I seem to missed the previous issue, thanks for pointing it out. I will close the issue now.
