### ISSUE TITLE
Omitting of activation bar in sequence diagrams with self-invocation

### ISSUE THREAD

**Issue by sbhbenjamin** [nus-cs2103-AY2122S2/forum#307]
Since it is optional to include the activation bar, how do we illustrate self-invocations when it exists? 
Would it be valid to also omit the activation bar illustrating the self-invocation?

**Comment by bingsen0806** [comment]
Yes you can, refer to quiz 6 below:

![image](https://user-images.githubusercontent.com/71639142/166436339-ef89e7ec-fd77-4c8a-a13f-608c0bae2b25.png)

You can see that the activation bars of the function printing A and the function printing B are omitted when they are supposed to be self-invocation

**Comment by sbhbenjamin** [comment]
@bingsen0806 Ahh I see, thanks so much! Will close the issue now.
