### ISSUE TITLE
Modeling System.out for Sequence Diagram

### ISSUE THREAD

**Issue by aweijun** [nus-cs2103-AY2122S2/forum#308]
Hi, I came across this question in the textbook. I was wondering how can we model `System.out` in this context.

![telegram-cloud-photo-size-5-6307294598598340561-y](https://user-images.githubusercontent.com/95308604/166437580-9361174d-129f-4c19-93d5-472396e3e1fa.jpg)

**Comment by damithc** [comment]
@aweijun There's no need to capture line 14 in the sequence diagram. But if you must, you can send a method call `println(q)` toe an entity `out:PrintStream` (`out` is a class-level public `PrintStream`object in the `System` class)

**Comment by aweijun** [comment]
Thanks Prof!
