### ISSUE TITLE
Issue with project after adding new main module

### ISSUE THREAD

**Issue by Btaykb** [nus-cs2103-AY2122S2/forum#31]
Hi prof and classmates, I seem to have an issue while following the instructions for adding JUnit support for my project. More specifically after deleting the extraneous module and creating the new main module, my imported packages within my project no longer work.

![Screenshot (127)](https://user-images.githubusercontent.com/77221233/150916362-49ce830e-3157-49a3-8e11-043b55b70b62.png)

![Screenshot (128)](https://user-images.githubusercontent.com/77221233/150916457-57e969bc-2f27-4f5a-b4a2-bea84d14b001.png)

![Screenshot (129)](https://user-images.githubusercontent.com/77221233/150916747-b3ed7b72-7bbf-4e97-a2fa-6f8a1465a21a.png)

As seen above, I have to change all my package names to include another duke to all my package names. I was wondering if anyone knows the actual cause and solution to this issue. Thanks !

**Comment by damithc** [comment]
See if [this](https://github.com/nus-cs2103-AY2122S2/forum/issues/30#issuecomment-1020800447) helps. i.e., delete .iml and .idea files and opening the project again in Intellij. Might have to set up JUnit again though.

**Comment by domlimm** [comment]
Hi @Btaykb ! It seems like you might have accidentally removed `ip` as the dependency.

Could you go to `File -> Project Structure` and see if you've these?

![image](https://user-images.githubusercontent.com/46486515/150917805-0fd68738-d201-4e53-a2f1-d9aad5ebad3c.png)

If not, you might have to redo the [entire setup](https://se-education.org/guides/tutorials/junit.html).

Also, point 8 in the JUnit link is important.

As mentioned by prof with the link, I faced quite a few issues when setting up. I've been doing mine in VSCode and moved to IntelliJ for the JUnit part.

Keep this thread updated, I'll check back!

**Comment by Btaykb** [comment]
Thanks @damithc and @domlimm for the responses! I tried running rm -rf .idea *.iml but ran into an issue. 
![Screenshot (130)](https://user-images.githubusercontent.com/77221233/150924934-77559d15-008f-4d04-862d-5b3637e91345.png)

Also, upon checking, it does appear that I have deleted ip as a dependency as I misunderstood the point on deleting any extraneous module before adding the main module in the JUnit guide.
![Screenshot (131)](https://user-images.githubusercontent.com/77221233/150925236-0a1f64f3-4c9e-4b7e-80a3-83daa967be97.png)

So in this case, I would have to set up the ip module again before restarting the steps outlined in the JUnit setup ?

**Comment by domlimm** [comment]
@Btaykb hello, not sure what went wrong there... That command basically does a kind of 'reset' so that when you restart IntelliJ, it generates those folders and its contents again.

Yes, would be better if you redid the entire process!

I checked your repo, everything looks good (as how it should be before doing `A-JUnit`). Basically, delete the entire project folder locally, then clone again and open in IntelliJ and follow the steps outlined in the JUnit setup!

Let us know how it goes!

**Comment by cheehongw** [comment]
@Btaykb

You can't do `rm -rf` in windows powershell

Try using a linux environment to do `rm -rf`. You can use WSL for this.

**Comment by Btaykb** [comment]
Hmm, I tried both running rm -rf .idea *.iml on WSL and also deleting my project and cloning again, but still could not fix the issue..
![Screenshot (134)](https://user-images.githubusercontent.com/77221233/150935910-c6693903-db5a-4dea-9bf2-909b4d26dd02.png)

My ip module is back now. 
![Screenshot (135)](https://user-images.githubusercontent.com/77221233/150936104-e10036c9-3f85-47fa-9080-680cadbe9419.png)

**Comment by damithc** [comment]
hmmm 🤔  this is odd
![image](https://user-images.githubusercontent.com/1673303/150937505-2293062b-6299-4927-b1c9-60ace2f508c6.png)

**Comment by damithc** [comment]
hmmm 🤔  this is odd
![image](https://user-images.githubusercontent.com/1673303/150937505-2293062b-6299-4927-b1c9-60ace2f508c6.png)

**Comment by Btaykb** [comment]
@damithc oh wait. Yup that was the issue all along! Apparently at some point through the JUnit setup, duke was added as a package prefix, which caused all my package names to include that extra duke. 

Thanks all for the inputs and responses!
