### ISSUE TITLE
No result from printwriter into specified text file

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#32]
I have a problem printing my output into the text file that I have specified.

I have encapsulated the creation of the file reader and writer into a class as shown below.

```java
public class FileAction {
    protected String filepath = "C:\\NUS\\CS2103\\iP\\data\\duke.txt";
    protected FileWriter file;
    protected PrintWriter writer;

    public FileAction() throws IOException {
        file = new FileWriter(filepath);
        writer = new PrintWriter(file);
    }

    public void save(String cont) {
        writer.write("Hello");
        writer.write(cont);
    }

    public void changeFilePath(String fileName) {
        filepath = fileName;
    }
}
```

Which is made used in the adding of tasks as shown below as 'f.save(t.toString());'

```java
public String add(Task t, FileAction f) {
        StringBuilder res = new StringBuilder();
        String line = "____________________________________________________________ \n";
        tasks.add(t);
        res.append(line).append("Got it. I've added this task: \n");
        res.append(t.toString()).append("\n");
        res.append("Now you have ").append(tasks.size());
        res.append(" tasks in the list.\n").append(line);
        f.save(t.toString());
        return res.toString();
 }
```

Additionally, the FileAction instance is supplied through an Action class which has an instance of FileAction created before use.
 (Shown in this link: https://github.com/hsiaojietng/ip/blob/branch-Level-7/src/main/java/Action.java)

Adding tasks such as 'todo Borrow books' runs the function save() without any errors, but I do not see any text created in the text file specified, is there a reason why?

**Comment by Spyobird** [comment]
Seems like you may have forgotten to `close` after you have written.

**Comment by putaojuice** [comment]
Try using File instead of FileWriter for your file variable.
