### ISSUE TITLE
Storing the tasks for Level-7

### ISSUE THREAD

**Issue by goel-a** [nus-cs2103-AY2122S2/forum#33]
Hi, 

 Could I clarify about the format of how we store the files for Level-7. Does it have to be a text based (.txt), or can we store it by using the Serializable interface which will result in the Task objects being stored in a .ser file ?

Thanks!

**Comment by damithc** [comment]
> Could I clarify about the format of how we store the files for Level-7. Does it have to be a text based (.txt), or can we store it by using the Serializable interface which will result in the Task objects being stored in a .ser file ?

@goel-a Yes, that's fine too.
