### ISSUE TITLE
Gradle causing code to not run

### ISSUE THREAD

**Issue by tzhan98** [nus-cs2103-AY2122S2/forum#34]
I messed with gradle and now it seems that none of my code will run. I tried to checkout my last commit but the issue persists.
my file 'gradlew' and 'gradlew.bat' is highlighted red if that matters.

Error: 
```java
Task 'Duke.main()' not found in root project 'ip'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.execution.TaskSelectionException: Task 'Duke.main()' not found in root project 'ip' < 112 internal lines >

```

**Comment by damithc** [comment]
Did you update the build.gradle to point to your man class? e.g., `duke.Duke`

**Comment by tzhan98** [comment]
![image](https://user-images.githubusercontent.com/77192480/151081492-2f43698e-d5a8-4fa5-b6c0-e6decaf6dc65.png)
I do not have the build.gradle file in my project.

**Comment by tzhan98** [comment]
Fixed the issue by cloning a new repo to local machine and creating a new configuration for it.
