### ISSUE TITLE
Files generated when creating jar file

### ISSUE THREAD

**Issue by pyk595** [nus-cs2103-AY2122S2/forum#36]
Hi, when I created the jar file, a file called `MANIFEST.MF` was created as well, are we supposed to commit this file or do we put it in gitignore?

**Comment by domlimm** [comment]
I think we can commit it. I did!

You mean the `META-INF/MANIFEST.MF`?

**Comment by ddx-510** [comment]
From the official java doc on [JAR file](https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html), the `MANIFEST.MF` contains the metadata for the JAR packaged. Since the JAR file is ignored, I think we could also ignore this file.

**Comment by pyk595** [comment]
Okay, thank you!

**Comment by damithc** [comment]
> From the official java doc on [JAR file](https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html), the `MANIFEST.MF` contains the metadata for the JAR packaged. Since the JAR file is ignored, I think we could also ignore this file.

Yes, files that are auto-generated and not hand-maintained thereafter are good candidates to be git-ignored. If the file contains info specific to the local environment (e.g., absolute file paths), they should definitely be git-ignored.

**Comment by pyk595** [comment]
Noted, thanks Prof!
