### ISSUE TITLE
Running UI-text testing results in difference between expected and actual after changing default Duke message

### ISSUE THREAD

**Issue by joey-chance** [nus-cs2103-AY2122S2/forum#37]
I had modified the "DUKE" greeting message to personalize it and designed a "JARVIS" greeting message instead. Here is the code for that.
```
String logo =
                " ------    -------    -------   ---        ---   ---------    -------\n" +
                        "|____  |  |   _   |  |   _   |  \\  \\      /  /  |___   ___|  |   ____|\n" +
                        "     | |  |  |_|  |  |  |_|  |   \\  \\    /  /       | |      |  |____ \n" +
                        " _   | |  |   _   |  |      _|    \\  \\  /  /        | |      |_____  |\n" +
                        "| |__| |  |  | |  |  |  |\\  \\      \\  \\/  /      ___| |___    ____|  |\n" +
                        "|______|  |__| |__|  |__| \\__\\      \\____/      |_________|  |_______|\n"
                ;
        System.out.println("Welcome home, sir.\n" + logo);
```
The output of this is shown in this image.
![Screen Shot 2022-01-26 at 4 32 03 PM](https://user-images.githubusercontent.com/92976979/151129192-1837b486-3835-45f9-80df-e9d79b6525bb.png)
However, when running my runtest.sh file, the expected and actual outcomes are different, and is seemingly caused by this new greeting message. The error is shown in this image.
![Screen Shot 2022-01-26 at 4 33 11 PM](https://user-images.githubusercontent.com/92976979/151129348-661a6585-0f42-47ef-8ff2-6702b5814c14.png)
I tried copy pasting the contents from my ACTUAL.TXT file to my EXPECTED.TXT file to test things out but I still receive the same difference. 
I was wondering if anyone has any idea as to why there is this difference between the outputs. Thank you in advance.

**Comment by domlimm** [comment]
Hi @joey-chance ! I think it is best if you could do this... Or at least I did it to overcome any differences when copying and pasting:

```
javac Duke.java; java Duke < input.txt > output.txt
```

Then just copying from `output.txt` to `EXPECTED.TXT`.

Not sure if you've done it this way or it will help your case..

**Comment by joey-chance** [comment]
Hey @domlimm! Thanks for the advice, that solved it. Cheers!
