### ISSUE TITLE
How to run runtest.bat file?

### ISSUE THREAD

**Issue by AdrianOngJJ** [nus-cs2103-AY2122S2/forum#39]
I was going through the Week 2 deliverables and got stuck at the following step:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/32859142/151137147-68186d0e-266a-4390-9bfb-542f307ec261.png">

I tried to run `java runtest.bat` and `bat runtest.bat` but to no avail. The current directory would be `/mnt/c/Users/adria/Desktop/iP/text-ui-test`

I also tried to right-click and run but i couldn't do it. 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/32859142/151137476-5667fc2b-2728-4320-9487-508a3d3b3bda.png">

**Comment by litone01** [comment]
Hi @AdrianOngJJ , if your issue has been resolved, please kindly close the issue. Thanks!

**Comment by AdrianOngJJ** [comment]
@litone01 Hihi, sorry I didn't close coz I haven't test it yet... I shall close it for now until something arise 

@cheehongw thanks for the help! I'll try it soon
