### ISSUE TITLE
Weekly Quiz Coding Standard Question

### ISSUE THREAD

**Issue by snoidetx** [nus-cs2103-AY2122S2/forum#40]
There is a question for us to choose if the variable name is compliant with coding standard:

`final static int ...`

May I ask for this question whether we only make choice based on the name of variable, instead of its keyword (such as `final`)?

**Comment by Spyobird** [comment]
Think the question is asking if the name of the variable is compliant based on its keywords. Do check naming section of https://se-education.org/guides/conventions/java/intermediate.html.

**Comment by damithc** [comment]
> Think the question is asking if the name of the variable is compliant based on its keywords. Do check naming section of https://se-education.org/guides/conventions/java/intermediate.html.

yes, that's correct. The question is about the variable name but `final static int` plays a role in the answer as well.

**Comment by snoidetx** [comment]
Thanks @Spyobird and prof! I understand that those keywords classify the variable as a constant which requires a certain naming convention. Actually I was wondering whether we need to follow certain order of the keywords (e.g. `static final` instead of `final static`) because I saw prof’s examples for the coding styles use `static final` instead.

**Comment by damithc** [comment]
@snoidetx good point, although not the focus of the question in concern.
If is best if the keyword order is consistent across the code base, from a coding standard point of view.
I've updated the question to use `static final`
