### ISSUE TITLE
runtest.sh encountering build failure after changing project structure

### ISSUE THREAD

**Issue by dionegoh** [nus-cs2103-AY2122S2/forum#41]
Hi, 
Just to check, does this project structure work? Currently under the Project tab, I only have 2 modules - src/main and src/test:
<img width="330" alt="Screenshot 2022-01-26 at 11 53 56 PM" src="https://user-images.githubusercontent.com/77088875/151197989-bc8ab469-6ef6-41e2-ba77-499c4ba702f4.png">

As per the instructions on the website, to view other subfolders in iP such as text-ui-test, I have to change tab to Project Files:
 
<img width="351" alt="Screenshot 2022-01-26 at 11 41 36 PM" src="https://user-images.githubusercontent.com/77088875/151196600-77a5cbca-b64a-46b4-ad78-a7e7594ac746.png">

However, when I try to run iP/text-ui-test/runtest.sh after completing the increment for A-JUnit, a build failure is thrown and I am not very sure if it is because of my project structure. 

<img width="985" alt="Screenshot 2022-01-26 at 11 51 52 PM" src="https://user-images.githubusercontent.com/77088875/151198529-85e12a11-1ca6-4689-a10c-9e8a667e4966.png">

Is iP supposed to be a module, and both src/main and src/test modules inside iP? If so, is there a way for me to rectify my current project structure?

Thank you so much!! :)

**Comment by dionegoh** [comment]
Thanks! :) After running the command and re-opening intellij, my file structure looks like this:
<img width="296" alt="Screenshot 2022-01-27 at 12 56 08 AM" src="https://user-images.githubusercontent.com/77088875/151209815-984b8c78-4636-43ae-b535-09ce90ab2989.png">

However, running runtest.sh is still throwing a build failure. This is the path in my runtest.sh, and it seems correct when I check it against my file structure. Is there something that I may be missing out on?:
 
<img width="710" alt="Screenshot 2022-01-27 at 12 54 54 AM" src="https://user-images.githubusercontent.com/77088875/151209985-feaf4910-9870-4f99-8d7e-617b11e4458c.png">

**Comment by damithc** [comment]
@dionegoh Did this file work after introducing the pikabot package?  Perhaps the script broke back then and not after JUnit was added?

**Comment by dionegoh** [comment]
Right perhaps so! I did not test the file after introducing the pikabot package. Should the path in runtest.sh be modified after introducing the pikabot package? Thank you!

**Comment by lkldev** [comment]
Hi, i believe you will need to update your path in runtest.sh. for the `javac` command, you should add `pikabot` to it, so something like
```
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\pikabot\*.java
```

Then you should update the `java` command to run your package pikabot, e.g.
```
java -classpath ..\bin pikabot.PikaBot < input.txt > ACTUAL.TXT
```

**Comment by dionegoh** [comment]
Ah I see!! It works now after updating the path and the commands! Thank you so much for your help :))
