### ISSUE TITLE
Is there a way to unit test methods with void return type?

### ISSUE THREAD

**Issue by xzzz3** [nus-cs2103-AY2122S2/forum#42]
From the weekly topics, it seems that JUnit testing can only be used on methods that return something, since we use assert to check whether the expected output is the same as the actual output of the method.

However, my implementation of Duke actually has quite some void return types in different classes. I tried to google and some suggested using Mockito's verify() function to do unit testing for void return types.

Is there a way to do it with JUnit? Or do void return types not need unit testing? Any advice is appreciated!

**Comment by Spyobird** [comment]
If your void methods still mutate some other variable, you can always test the mutated variable too see if the changes are expected. If not you can always change the void methods to boolean if you want assurance that a method has been called.

**Comment by 9teMare** [comment]
If your `void` method actually prints something, i.e.`System.out.println()`, you can test your method with `PrintStream` and `ByteArrayOutputStream` class. Note that you need to set up the output stream before any tests with  `@BeforeEach` and tear down the stream after any tests with `@AfterEach`. After setting up, in your test method, simply call your method under test, and `assertEquals()` the expected printed string with your `ByteArrayOutputStream` object (note to convert the object to string and trim the automatically added \n with `toString().trim()`).

**Comment by xzzz3** [comment]
Thank you!
