### ISSUE TITLE
Infinite loop with Boolean wrapper class

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#43]
Hi all, I was trying to use a while loop for the main logic in Duke.
However I got into an infinite loop, where the "bye" command was supposed to end the java program.
Below is a summary of the main loop.
```java
Boolean over;
while(!over) {
        if (command instanceof bye) {
            itIsOver(over);
        }
    }
}
```

the body of the method 'itIsOver' simply does the following.
```java
over = true;
```

From my understanding, the fact that Boolean is a wrapper class of boolean tells me that the 'over' variable in the main loop should change to a 'true' value. I failed to find a reason in the internet. Any help would be grateful!

**Comment by lkldev** [comment]
Hi, have you tried and see if it goes into the if statement? You can debug or a simple print statement will do.

**Comment by B1LLP4RK** [comment]
@lkldev  Thank you for your suggestion! But... It seems unrelated with the if statement. To make sure, I already tested with a separate code that looks like the following.
```java
Boolean over;
while(!over) {
        System.out.println("if successful, this line will be printed only once");
        itIsOver(over);
    }
}
```
This also resulted in infinite printing of the String.

**Comment by lkldev** [comment]
Ah sorry, I misunderstood your question. In java, the [primitive wrapper classes are immutable](https://www.geeksforgeeks.org/primitive-wrapper-classes-are-immutable-in-java/). Hence, the Boolean over cannot be changed by another function if you pass by reference. For your code to work, `itIsOver` will have to return a boolean and assign it back to `over`, so something like `over = isItOver()`.

**Comment by B1LLP4RK** [comment]
@lkldev that is crystal clear! Thank you:)
