### ISSUE TITLE
Addressbook.jar opens, but the interface becomes cryptic

### ISSUE THREAD

**Issue by zxgoh** [nus-cs2103-AY2122S2/forum#44]
Good day all, 

I have installed addressbook.jar, and managed to open it. However, the interface presents itself as such:
<img width="739" alt="Screenshot 2022-01-27 at 12 06 14 PM" src="https://user-images.githubusercontent.com/73661051/151290323-53944f26-79a0-42b0-8217-f271d056b65a.png">

Not sure how to fix this issue, im currently running macOS 12.0.1, with java 17.0.1 installed. 
Thank you!

**Comment by SimJM** [comment]
Hi @zxgoh, refer to https://github.com/nus-cs2103-AY2122S2/forum/issues/35

**Comment by zxgoh** [comment]
> Hi @zxgoh, refer to #35

Hi @SimJM , I deleted all other jdk and am left with only this:
<img width="404" alt="Screenshot 2022-01-27 at 3 17 03 PM" src="https://user-images.githubusercontent.com/73661051/151309926-9a250b53-1624-484d-a44b-fa27baa639f0.png">

When I type in java -version into terminal, terminal displays as such:
<img width="787" alt="Screenshot 2022-01-27 at 3 15 44 PM" src="https://user-images.githubusercontent.com/73661051/151309772-c16e97b0-b5f2-4799-bccb-e896d1d8b15d.png">

However, when I try to open addressbook.jar, it gives an error saying: 
<img width="255" alt="Screenshot 2022-01-27 at 3 17 55 PM" src="https://user-images.githubusercontent.com/73661051/151310024-185acb53-1abc-4ac8-b352-c8d6786ff59e.png">

I'm quite confused on how to open the jar file now with the current jdk 11. Thanks!

**Comment by petermonky** [comment]
Hey @zxgoh, not sure if it's relevant, but have you set the `JAVA_HOME` system variable? Assuming your shell is zsh, try adding this line to your `~/.zshrc` file:

`export JAVA_HOME=$(/usr/libexec/java_home -v 11.0.14)`

On a side note, I am also experiencing the same text corruption issue. I have an m1 MacBook and have thus installed the recommended version of Java, but the text still appears broken. What else can I do to fix this? Thank you!

**Comment by kouyk** [comment]
Hello @zxgoh, I'm a senior from a previous batch. From the screenshots it looks like you are attempting to launch the jar file by double clicking on it right? Have you tried the `java -jar name.jar` method yet? Also, make sure that you have downloaded the "JDK FX" and not "JDK" version as well.

**Comment by zxgoh** [comment]
> Hey @zxgoh, not sure if it's relevant, but have you set the `JAVA_HOME` system variable? Assuming your shell is zsh, try adding this line to your `~/.zshrc` file:
> 
> `export JAVA_HOME=$(/usr/libexec/java_home -v 11.0.14)`
> 
> On a side note, I am also experiencing the same text corruption issue. I have an m1 MacBook and have thus installed the recommended version of Java, but the text still appears broken. What else can I do to fix this? Thank you!
> 
> EDIT: I think I found a solution for my setup, I tried running `addressbook.jar` from the terminal instead of Finder. Calling `java -jar addressbook.jar` seems to work for me; the text doesn't get corrupted this way.

@petermonky  Yep, I tried entering the command into terminal `java -jar addressbook.jar` and it worked well. Thank you!

**Comment by zxgoh** [comment]
> Hello @zxgoh, I'm a senior from a previous batch. From the screenshots it looks like you are attempting to launch the jar file by double clicking on it right? Have you tried the `java -jar name.jar` method yet? Also, make sure that you have downloaded the "JDK FX" and not "JDK" version as well.
> 
> Edit: realised @petermonky found the solution as well, as for the doubling clicking through finder you might need to dig into associating jar files with the correct runtime, from the descriptions it appears that macos is currently using another version of JDK.

Hi @kouyk , yes, that solution that was suggested works well! Thanks for helping out too!
