### ISSUE TITLE
Unable to find main class when trying to run JAR file

### ISSUE THREAD

**Issue by chriswengqi** [nus-cs2103-AY2122S2/forum#46]
Hi! I am unable to run my JAR file because my main class Duke is not found. When I try to check my MANIFEST.MF file my Main-Class Duke cannot be resolved even though they are in the same directory. I've tried many ways to resolve this issue like moving my MANIFEST file and my jar file around the directory but none of them seem to work. Is there anybody who has faced the same problem? Been spending way too much time on this small increment.

![image](https://user-images.githubusercontent.com/67186918/151472291-52088ff1-6ec3-4ac7-a9f4-70c4573587ee.png)

![image](https://user-images.githubusercontent.com/67186918/151472274-9f02f099-593c-442e-a4bd-c033213d05e0.png)

**Comment by Spyobird** [comment]
Not sure if this is the solution but perhaps don't throw exceptions on your main method.

**Comment by limzk126** [comment]
Hi i think this is a similar issue to https://github.com/nus-cs2103-AY2122S2/forum/issues/45.

The format of your Main-Class should be `[Name of your package].[Name of your Main file]`

**Comment by yl-ang** [comment]
> Hi i think this is a similar issue to #45.
> 
> The format of your Main-Class should be `[Name of your package].[Name of your Main file]`
> 
> You can try creating a package called `duke` and putting `Duke.java` under it, and then change the Main-Class name to `duke.Duke` to see if it works. Hope it helps!

Hi, I find this helpful in resolving an issue with Gradle where the jar file generated from ShadowJar could not load the main class, I modified the mainClassName and ran the ShadowJar to generate a working jar executable. 

![image](https://user-images.githubusercontent.com/39936106/151693257-ef57916d-b6c8-41a4-9bd0-2b95c60ccb98.png)
