### ISSUE TITLE
How are proctected method/classes tested using JUnit?

### ISSUE THREAD

**Issue by thikhinab** [nus-cs2103-AY2122S2/forum#47]
May I know how protected method and classes are tested using JUnit in SE practice?

**Comment by robinrojh** [comment]
It seems that you can call it if the test is in the same package. You can find some more details in [](https://junit.org/junit4/faq.html#atests_10)!

However, this documentation is from junit4, so if it doesn't work, you can try this approach of creating a subclass that calls the protected method for testing purposes only.

**Comment by thikhinab** [comment]
Thank you for sharing!
