### ISSUE TITLE
Week 4 [W4.2] Class/Object Diagrams: Basics

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#48]
Hello! Is anyone able to see the in-video quiz at the timestamp `16:50`? It's missing for mine

**Comment by damithc** [comment]
> Hello! Is anyone able to see the in-video quiz at the timestamp `16:50`? It's missing for mine

@domlimm Looks like that question got deleted somehow. You can ignore it for now.

**Comment by domlimm** [comment]
Noted, thanks prof! 😃
