### ISSUE TITLE
Weekly In Video Quiz

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#49]
Hello, I am just wondering whether there is any penalty if you make any errors during the in-video quiz. Since some of the topics were new to me, I am usually unsure about my answers. (And I see that there is no retaking the quiz)

**Comment by damithc** [comment]
@albertsutz there is no penalty for wrong answers in in-video quizzes

**Comment by albertsutz** [comment]
@damithc Thank you!
