### ISSUE TITLE
Question regarding tracking system and doing tasks ahead

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#5]
I have some questions regarding how the tracking system works and doing tasks ahead. In particular:

**1.** If we complete Week X's in video quiz before Week X, will it be counted towards the "extra" participation for Week X. Also, do I need to answer all in-video quizzes of Week X to get the participation, or answering some of them will do?

**2.** Are we allowed to complete iP tasks for week X before week X? For example, if I completed (some or all) of Week 3's task before Week 3, commit and tag before Week 3, and push to my fork only during Week 3, will my commits and tags be tracked?

**3.** Under "Project Management" component for iP, one of the criteria is "submit some deliverables in at least 4 out of 5 iP weeks". Consider the scenario in question 2 above, will I be considered as "submitting some deliverables in Week 3" if I completed Week 3 tasks beforehand and only push in Week 3 (assuming I did not do any Week 4 tasks in Week 3)? What if, in addition to that, I complete some of all of Week 4's task in Week 3. Will I then be considered as "submitting some deliverables (week 4 tasks) in week 3"? 

**4.** Do "deliverables" refer to only commits tagged with the given tags? In the case if I completed all tagged tasks for Week 6 in Week 5, there will be no more "tags" for me to complete. Can I submit some untagged commits in Week 6 to be considered as "submitting some deliverables in Week 6"?

**Comment by damithc** [comment]
@bingsen0806 my answers below:

> **1.** If we complete Week X's in video quiz before Week X, will it be counted towards the "extra" participation for Week X. Also, do I need to answer all in-video quizzes of Week X to get the participation, or answering some of them will do?

No extra marks. Only _some_ will do. Video quizzes can earn bonus points only.

> **2.** Are we allowed to complete iP tasks for week X before week X? For example, if I completed (some or all) of Week 3's task before Week 3, commit and tag before Week 3, and push to my fork only during Week 3, will my commits and tags be tracked?

Not recommended to jump ahead in project tasks. More info in https://nus-cs2103-ay2122s2.github.io/website/schedule/week2/project.html

![image](https://user-images.githubusercontent.com/1673303/149700036-bbc3e3e9-8b7d-4c01-8a41-32b0c10e1566.png)


> **3.** Under "Project Management" component for iP, one of the criteria is "submit some deliverables in at least 4 out of 5 iP weeks". Consider the scenario in question 2 above, will I be considered as "submitting some deliverables in Week 3" if I completed Week 3 tasks beforehand and only push in Week 3 (assuming I did not do any Week 4 tasks in Week 3)? What if, in addition to that, I complete some of all of Week 4's task in Week 3. Will I then be considered as "submitting some deliverables (week 4 tasks) in week 3"?

For this, we just look at commit timestamp. We don't check _what_ the commits contain or the tags attached to them.
 
> **4.** Do "deliverables" refer to only commits tagged with the given tags? In the case if I completed all tagged tasks for Week 6 in Week 5, there will be no more "tags" for me to complete. Can I submit some untagged commits in Week 6 to be considered as "submitting some deliverables in Week 6"?

See previous answer.

**Comment by BryannYeap** [comment]
Hi @bingsen0806 , if you have no further questions regarding this issue, you are welcome to close the issue as resolved!
