### ISSUE TITLE
How to do unit tests for `Storage` class

### ISSUE THREAD

**Issue by cheehongw** [nus-cs2103-AY2122S2/forum#50]
Hello, how would one go about implementing unit tests for the methods in the storage module?

For example, one might expect a `Storage::readFile` method to read from a given file and return the contents of that file. How to handle the need for an external file?

**Comment by ong6** [comment]
Hello, I'm from a previous batch of CS2103 students (dropping by in this forum to see if I can help you guys with tech problems)! Not 100% sure if this works but...

Perhaps one of the ways you could do it without an extremal file is to simulate a fake file before you start your tests?

By using the @BeforeClass or @Before annotation, [details here](https://www.javatpoint.com/junit-tutorial) you can generate a file save it to a test directory and then read it in the test cases. Afterwards, you can use the @After and @AfterClass annotations to clear any files you may have generated.

This is just one way I could think of to accomplish this. I'm sure there are many other methods you could use to simulate something like this as well.

**Comment by ryantanlien** [comment]
Hi, presumably when we write unit tests, we test our code and not the libraries that our code depends on. Here, we have to trust that the File I/O methods in the libraries we use works.

I do not know what File I/O libraries or methods you are using, but one way as suggested above is to create test files and then delete them after the test. However, this would be considered an integration test not a unit test.

Another alternative is to just mock the data source with a StringReader and StringWriter. (I'm assuming you are using java.io)
Ensure that the File I/O correctly converts a File object to the relevant Reader object? (For file input)
Maybe ensure that the File I/O library correctly writes to the buffer? (For file output)

Perhaps another way to go about the unit test is to test whether your storage method processes the file data correctly.

Wish you all the best in your testing!
