### ISSUE TITLE
Week 4's 1st Task of iP

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#52]
Hello! As for `Use GFMD in the PR description`, are we able to write anything? i.e. Does not have to be related to the iP. Just to confirm!

It says:
> If you wish, you may write the PR description to be very similar to the example given above -- as the goal here is to demonstrate your mastery of the GFMD syntax (not ad writing skills).

Thank you!

**Comment by damithc** [comment]
@domlimm Yes, doesn't have to be related to the iP.
