### ISSUE TITLE
Running Duke Project in Gradle

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#53]
Hi,

I'm trying to add Gradle support to my Duke project. What I have done is that I created a new Gradle project, copied the file `build.gradle` from the new project to my Duke project and built it. It built successfully. After that, I try to run my Duke project in gradle by running the Gradle task shown in the figure:

<img width="220" alt="Screenshot 2022-01-29 140549" src="https://user-images.githubusercontent.com/67496158/151649813-dced6928-62fb-4962-a9ef-a0e0d00f17f0.png">

Below is the result:

<img width="242" alt="Screenshot 2022-01-29 140709" src="https://user-images.githubusercontent.com/67496158/151649808-448c0b26-d30c-48df-971b-b59cfc437e5a.png">

Although it built successfully, I do not see any outputs from Duke, and I did not have a chance to enter a command to Duke. Am I in the correct track? How should I run my Duke project?

Thanks in advance!

**Comment by damithc** [comment]
@zihaowrez did you try `./gradlew run` command (in the terminal)?

**Comment by zihaowrez** [comment]
> @zihaowrez did you try `./gradlew run` command (in the terminal)?

I cannot find a "run" task in Gradle:

<img width="296" alt="Screenshot 2022-01-29 152943" src="https://user-images.githubusercontent.com/67496158/151652421-63d75253-84a8-4f09-b16f-bbb09b61be90.png">

<img width="208" alt="Screenshot 2022-01-29 154133" src="https://user-images.githubusercontent.com/67496158/151652430-bcc31126-15f0-41fa-ac61-6df399c0b7ae.png">

How should I add a "run" task?

**Comment by damithc** [comment]
@zihaowrez just checking: did you follow the following instruction?

![image](https://user-images.githubusercontent.com/1673303/151653032-b40785b8-2518-419b-9962-27cc36fef179.png)

**Comment by zihaowrez** [comment]
> @zihaowrez just checking: did you follow the following instruction?
> 
> ![image](https://user-images.githubusercontent.com/1673303/151653032-b40785b8-2518-419b-9962-27cc36fef179.png)

oops.. I think I missed this :sweat:. Now my Gradle is working fine. Thank you!
