### ISSUE TITLE
Not really sure how to use the PrintStream and ByteArrayOutputStream to test for void methods

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#54]
Hey everyone,

I have an issue regarding testing for the correctness of the logo name generated from my UserInterface class. The method that generates this is a void method and I have tried to use PrintStream and ByteArrayOutputStream to try to test it, but i'm not really sure why the `assertEquals` does not work...

`public class UserInterfaceTest {`

    @Test
    @DisplayName("Logo name is correct.")
    public void UI() {
        PrintStream output = System.out;
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream temporary = new PrintStream(outputStream);
        String greeting = "\nHello! I'm YQ, your assistant\n" + "What can I do for you?\n";
        String divider = "_______________________________________________";
        String signature = " ____        _        \n"
                + "|  _ \\ _   _| | _____ \n"
                + "| | | | | | | |/ / _ \\\n"
                + "| |_| | |_| |   <  __/\n"
                + "|____/ \\__,_|_|\\_\\___|\n";
        String expected = divider + greeting + signature + divider;
        UserInterface userInterface = new UserInterface();
        userInterface.introMessage();
        System.setOut(output);
        temporary.flush();
        assertEquals(expected, outputStream.toString().trim());
    }

`}`

Appreciate it if anyone could help!

**Comment by dandaandaaaaaan** [comment]
If i'm not wrong, you can try moving the line `System.setOut(output);` to before the `userInterface.introMessage()`. This is because `System.setOut` is reassigning the output stream of the program. 

Since you are checking for the printed message, you should set the standard output stream into your created stream first, then printing the line, then it should be captured as part of the `outStream.toString()`

**Comment by sharpstorm** [comment]
I would like to add on to @dandaandaaaaaan in pointing out the fact that `PrintStream output = System.out;` is still the command line output and not your `ByteArrayOutputStream`. Doing `System.setOut(output)` is effectively doing `System.setOut(System.out);`, which achieves nothing.

You should be doing `System.setOut(temporary);` instead, in addition to moving the `System.setOut(temporary);` call to before `userInterface.introMessage()`

**Comment by yuqitanyq** [comment]
okay got it! Thanks!
