### ISSUE TITLE
Releasing new version of Duke to correct mistakes in previous JAR?

### ISSUE THREAD

**Issue by punnyhuimin** [nus-cs2103-AY2122S2/forum#55]
Hello, I picked up on an error in my code while working on the other sections of the assignment. However, I have already released my v0.1 with the JAR file. Will I be penalized for it? If yes, should I be re-releasing a new version with the updated JAR file?

**Comment by damithc** [comment]
@punnyhuimin no need to release a new version. The initial JAR file release is for you to learn about creating a JAR file. It will not be used/tested/graded.

**Comment by punnyhuimin** [comment]
@damithc Thank you for the clarification! I'll close this thread now.
