### ISSUE TITLE
Config file for checkstyle is not found.

### ISSUE THREAD

**Issue by thikhinab** [nus-cs2103-AY2122S2/forum#57]
Hi! Even though the checkstyle plugin was added to the build.gradle file, the config directory and respective files are not found. Are there any other steps apart from updating the build.gradle to set up checkstyle?
- Environment:
    - IntelliJ Idea 2021.1.1
    - Java 11.0.2
    - Windows 10

![checkstyle](https://user-images.githubusercontent.com/59680441/151667650-fa8a28e6-851d-4175-9d4f-942c1354416b.PNG)
![checkstyle 1](https://user-images.githubusercontent.com/59680441/151667654-f049533a-e33e-4f97-9ac6-6eaf81b1951b.PNG)
![image](https://user-images.githubusercontent.com/59680441/151667695-042587d5-71a9-4fd1-9867-7a2555f9286c.png)

**Comment by lzan98** [comment]
Hi, you have to place the checkstyle xml file in config/checkstyle/checkstyle.xml as follows:

<img width="238" alt="Screenshot 2022-01-30 at 00 09 39" src="https://user-images.githubusercontent.com/66457036/151668205-4e9a449d-6d84-4442-9e30-df777237f638.png">

I used the checkstyle xml provided in AB3 [here](https://github.com/se-edu/addressbook-level3/tree/master/config)

**Comment by thikhinab** [comment]
Thank you for pointing this out!
