### ISSUE TITLE
Unable to push commits to Github

### ISSUE THREAD

**Issue by AdrianOngJJ** [nus-cs2103-AY2122S2/forum#6]
I was trying out _Week 2 - Topics - W2.4b: Tools -> Git and Github -> clone: Copying a repo_

I've created a repo in my local machine but when I type `git push origin master`, it would not load and gave me this error: _This error is shown after typing in my username for Git._
<img width="274" alt="image" src="https://user-images.githubusercontent.com/32859142/149763393-55487485-0db3-473b-8693-7914e7c7edfe.png">

Here is a  screenshot of my git commands:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/32859142/149764100-b868e9c2-ffec-4899-b8c6-c724c04aa370.png">

What should I do to fix this? Thank you.

**Comment by marcuschj** [comment]
Hi @AdrianOngJJ , broken pipe is sometimes due to a slow network. Could you try using a different internet connection and see if it solves the problem?

**Comment by domlimm** [comment]
Hi Adrian! Could you please list the steps in how you brought the repo into your local machine? You mentioned you pushed but you pulled instead. A lil confused!

**Comment by kevinchua6** [comment]
If that doesn't work, you can also try using SSH which is the more convenient imo as you don't have to type in your username and password every time you push (which may be the cause of the problem?). Set your remote as `git@github.com:se-edu/AdrianOngJJ/CS2103T-Test.git`, [create a new ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), and add your public key to github so all subsequent pushes will not require your github username and password.  
I hope that'll help!

**Comment by vigneshsankariyer1234567890** [comment]
Do ensure that you have already enabled a [Personal Access Token ](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and store it in a secure location if you are using that method instead. Hopefully you can solve the problem using one of the steps above!

**Comment by limzk126** [comment]
Hi @AdrianOngJJ, if this issue is still not resolved, it would perhaps be helpful for you to take a screenshot after clicking on the **details** button as shown in your first image.

**Comment by AdrianOngJJ** [comment]
Hello everyone! Sorry for the late response :]

> Hi @AdrianOngJJ , broken pipe is sometimes due to a slow network. Could you try using a different internet connection and see if it solves the problem?

@marcuschj I was using the school wifi back then and now using my home wifi and still face the same problem.

> Hi Adrian! Could you please list the steps in how you brought the repo into your local machine? You mentioned you pushed but you pulled instead. A lil confused!

@domlimm Sorry for the confusion. The issue I had was I couldn't push nor pull. It seems like I couldn't get or put anything top the remote server.

> If that doesn't work, you can also try using SSH which is the more convenient imo as you don't have to type in your username and password every time you push (which may be the cause of the problem?). Set your remote as `git@github.com:se-edu/AdrianOngJJ/CS2103T-Test.git`, [create a new ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), and add your public key to github so all subsequent pushes will not require your github username and password. I hope that'll help!

@kevinchua6 Thanks for the reply! I did a little more digging and found out that I could either use the HTTPS method or your SSH method. I've studied the SSH method but I felt a bit too confusing (my coding command is bad). Here are some's a SS of my attempt to use the SSH method:
![image](https://user-images.githubusercontent.com/32859142/149962765-1677d699-01bf-42f2-a6fc-b2ff8bde1220.png)

However, I've found the solution by referring to [this](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git). Idk if changing the visibility of my repo from **Private** to **Public** made a difference.

But thanks to all for helping!!
