### ISSUE TITLE
NullPointerException on FXMLLoader Load

### ISSUE THREAD

**Issue by RyanCheungJF** [nus-cs2103-AY2122S2/forum#61]
Hi!

I was following the [JavaFX Part 4 Tutorial](https://se-education.org/guides/tutorials/javaFxPart4.html) and ran into the following error:

`java.lang.NullPointerException: Input stream must not be null`

I believe the error comes from the overriden `start` method in `Main.java`:

```java
    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load(); // Seems to break here
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            fxmlLoader.<MainWindow>getController().setDuke(duke);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

More specifically, it comes from the line `AnchorPane ap = fxmlLoader.load();`

Out of the 4 code snippets provided on the site, I didn't modify any of the code provided except for adding package statements and changing the path in `MainWindow.fxml`. I changed the path of `fx:controller` with respect to how my directory is structured.

Below is the specific changes I made to my fxml file:

```xml
<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0"
            prefWidth="400.0" xmlns="http://javafx.com/javafx/8.0.171" xmlns:fx="http://javafx.com/fxml/1"
            fx:controller="duke.ui.MainWindow">
```

Attached below is the structure of my directory.

![image](https://user-images.githubusercontent.com/63341400/151695401-9a6fe1cf-6af1-4f9e-8647-87ffc53f45ee.png)

If anyone may know what issue is causing that or could provide any help, that'll be greatly appreciated. Thanks in advance!

**Comment by limzk126** [comment]
Hi I am from the previous batches of CS2103T (Dropping by this forum to help you guys with technical difficulties).

Based on the information you provided, all I can guess is that the fxml files are not saved. Maybe you could try saving them manually and see if it solves the problem?

**Comment by RyanCheungJF** [comment]
Hi @limzk126. Unfortunately, I tried saving and restarting IntelliJ to no avail. Thanks for the suggestion and taking the time to help though.

**Comment by limzk126** [comment]
I think i have found your issue.

![image](https://user-images.githubusercontent.com/88614036/151705087-80705357-ab5b-4760-84bf-3bedf5a1a3f4.png)

I think the `Image()` constructor is causing the exception. To remedy this, simply add the relevant images and use the correct relative paths in the `Image()` constructors.
![image](https://user-images.githubusercontent.com/88614036/151705176-7dcf5699-9adb-4396-ac95-25251d8dce71.png)

**Comment by RyanCheungJF** [comment]
Thanks @limzk126, I made a mistake of uploading a .png instead of a .jpg within my `images` folder. but used .jpg imports for both images. Really appreciate the time you took to help me. Will be closing the issue now!
