### ISSUE TITLE
JavaFx Unable to Locate File Using getResourceAsStream()

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#62]
Hi,

I followed the JavaFX tutorial until [this line](https://se-education.org/guides/tutorials/javaFxPart3.html#:~:text=private%20Image%20user%20%3D%20new%20Image(this.getClass().getResourceAsStream(%22/images/DaUser.png%22))%3B), then I encountered the error
```java
java.lang.NullPointerException: Input stream must not be null
```
when I add
```java
private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
```
into my code.

Here are the paths of my java file and my image:
`...\src\main\java\com\example\demo\HelloApplication.java`
`...\src\main\resources\images\DaUser.png`

Has anyone experienced the same issue?

Thanks!

**Comment by vimuthm** [comment]
Hi @zihaowrez , I'm from the previous batch (dropping by in this forum to see if I can help you guys with tech problems).

Can you push this version to a separate branch temporarily, for me and others here to take a better look at? I can't seem to find an issue from the given details...

**Comment by zihaowrez** [comment]
Hi @VimuthM, 

I've closed Intellij when you commented, and the error is gone after I reopen my project! :joy: Thanks for helping though!
