### ISSUE TITLE
Potential Typo in Week 4 Project Tasks

### ISSUE THREAD

**Issue by sharpstorm** [nus-cs2103-AY2122S2/forum#63]
# Summary
It seems like there is a typo in the `Level-10` task description.

## Current Version
![week4-project](https://user-images.githubusercontent.com/13163634/151704772-b191432b-a565-4ea5-b1e2-7b790b8c968d.png)

## Suggested Change
1. ~earning~ **learning** JavaFX basics

**Comment by damithc** [comment]
Thanks for reporting the bug @sharpstorm. Fixed.
