### ISSUE TITLE
how to configure intellij reformat to force method body to next line?

### ISSUE THREAD

**Issue by B1LLP4RK** [nus-cs2103-AY2122S2/forum#64]
Hi all, I was trying to configure my intellij setting and all went well except for the following situation.
I need intellij to reformat the following 
```java
public String function(String string) { return string; }
```
to this style.
```java
public void someMethod() throws SomeException {
    ...
}
```

However, I couldn't find such an option to enforce it. Would appreciate any answer, including "it is not possible!", then I can happily decide to manually format every such method in each file.

**Comment by Spyobird** [comment]
File -> Settings -> Editor -> Code Style -> Java.

Sometimes IntelliJ collapses the code so it looks like it is on one line but u can expand it on the sidebar.

**Comment by AAlghrairy** [comment]
To add to what @Spyobird said, it's a design choice by IntelliJ. It won't show this effect when you push the commit, so there's no need to manually format each method.

**Comment by B1LLP4RK** [comment]
Thank you both so much! @Spyobird @AAlghrairy! Seems like I just misunderstood haha. Just another confusion after moving from vim.
