### ISSUE TITLE
Branch Naming Conventions for Week 4 Task

### ISSUE THREAD

**Issue by tiewweijian** [nus-cs2103-AY2122S2/forum#65]
Hello, would like to clarify if there is any specifications (as it was not explicitly stated in the task) on naming the branches for Week 4's iP tasks such as `A-Gradle` and `A-CheckStyle` ? 

Do I create the branches similar to week 3's tasks like `branch-A-Gradle` ? Thanks in advance!

**Comment by damithc** [comment]
> Do I create the branches similar to week 3's tasks like `branch-A-Gradle` ? Thanks in advance!

Yes, that should be fine @tiewweijian

**Comment by tiewweijian** [comment]
Ok, thanks prof !!
