### ISSUE TITLE
JavaFX SDK for M1 Mac

### ISSUE THREAD

**Issue by jaegarpoon** [nus-cs2103-AY2122S2/forum#66]
Hi all, when looking up the SDK for JavaFX 11 I realised that support for aarch64 architecture is only provided for JavaFX 17. May I check if anyone found alternatives to this? Else how do I move ahead with this? Thanks in advance!

**Comment by kouyk** [comment]
Hi @jaegarpoon, I'm your senior from a previous batch, have you checked out the advisory on https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html?

**Comment by jaegarpoon** [comment]
Hi @kouyk, thanks for the help! Posted this question because I assumed the JavaFX SDK was a standalone, did not realise that JDK should already contain it. Will be closing the issue!
