### ISSUE TITLE
Cannot Import JavaFX Elements

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#67]
Hi,

My Intellij has trouble importing JavaFX Elements:

<img width="239" alt="Screenshot 2022-01-31 113349" src="https://user-images.githubusercontent.com/67496158/151735433-8b3e9b3b-dcbf-44a7-8aac-6644bc4667f9.png">

I'm using Gradle, and here is my dependencies in `build.gradle`:

```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```

Anyone knows how to solve this? Thank you!

**Comment by ddx-510** [comment]
There does not seem to have an issue with your `build.gradle` file. But it seems like the **Gradle dependencies** have not been updated automatically after your modification. 

You may open the gradle tab, right click the project name (in my case `ip`) and choose **Refresh Gradle Dependencies**
<img width="469" alt="Screenshot 2022-01-31 at 1 30 24 PM" src="https://user-images.githubusercontent.com/20592322/151743821-451f2477-5de1-49d3-af07-0d92b9873ea8.png">

If this still cannot work, you can close your project and reopen it to force refresh the dependencies.

**Comment by zihaowrez** [comment]
Hi @ddx-510 , thanks for helping. I reopened Intellij, but the problem persists.

**Comment by ddx-510** [comment]
Hi @zihaowrez, could you try adding this line of code into your `build.gradle` dependency section and try again.
`String javaFxVersion = '11'`
From the [javaFX Tutorial ](https://se-education.org/guides/tutorials/javaFxPart1.html), you might miss this line of code so that the `implementation` below would have an unknown reference to `javaFxVersion`

**Comment by zihaowrez** [comment]
Hi @ddx-510 , that solves the problem.. :joy: Thanks!
