### ISSUE TITLE
Error when compiling Gradle

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#68]
I did not create iP project as a Gradle project at the start and just follow instructions to create the build.gradle & setting.gradle files 

**build.gradle**
```Gradle
plugins {
    id 'java'
}

application {
    mainClassName = "duke.Duke"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation 'junit:junit:4.12'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
}
```

**settings.gradle**
```Gradle
rootProject.name = 'iP'
```

But when I try to compile Gradle, I get this error message which I am not sure how to fix. I have made sure to change the "mainClassName" but to no avail.
![image](https://user-images.githubusercontent.com/56862300/151740674-752e0ef1-03a1-43f5-90d2-ea0032407857.png)

**Comment by ddx-510** [comment]
I do not think we need to manually create the `build.gradle`. 
In the [task description ](https://nus-cs2103-ay2122s2.github.io/website/schedule/week4/project.html)

> Gradle support is provided as a separate branch (named `add-gradle-support`) in the Duke repo. Therefore, you can follow scenario 2 in the guide below.

We can just merge this branch to the current working branch, and gradle support will be available with a few more steps of setup. You can check the [2103 official guide on gradle](https://se-education.org/guides/tutorials/gradle.html) and follow the instructions on scenario 2 to get a clearer explaination.

**Comment by glennljw** [comment]
As mentioned by @ddx-510, you can first merge the ***add-gradle-support*** branch, then continue with the second scenario for setting up Gradle. 

You would probably need a ***config*** folder for your checkstyle plugin to work. You can get it from [AB3](https://github.com/se-edu/addressbook-level3).

**Comment by hsiaojietng** [comment]
Hi guys, thanks for the help! I did the merging, deletion of .idea folder and opened the project again, but I don't seem to get the correct output as shown below:

Correct: 
![image](https://user-images.githubusercontent.com/56862300/151924607-a69674f9-3575-41e1-84f5-8c2fb0157446.png)

Mine:
![image](https://user-images.githubusercontent.com/56862300/151924658-d4104af7-854d-4a09-a04d-53935aa3d60e.png)

Anyone knows why?

**Comment by Punpun1643** [comment]
I think the first pic is the Gradle Toolbar while the second pic is the Project Tool Window? If you click on the Gradle tab on the right side of your screen I think you should be able to see the first pic.

**Comment by hsiaojietng** [comment]
oh sheessh alright thanks so much
