### ISSUE TITLE
Exception "JavaFX runtime components are missing" After Including JavaFX SDK and VM Options

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#69]
Hi,

I encounter this error when trying to run the Duke GUI using Gradle:
```
JavaFX runtime components are missing, and are required to run this application
```
I've tried the solutions on Google: I've included the JavaFX `lib` folder in `File` -> `Project Structure` -> `Modules` -> `Dependencies`, as shown in the figure below.

<img width="515" alt="Screenshot 2022-01-31 145458" src="https://user-images.githubusercontent.com/67496158/151751037-d84d3c6a-0f0d-4bf3-b879-2ebaf6c89b78.png">

I've also included the JavaFX files the VM options:

<img width="514" alt="Screenshot 2022-01-31 144919" src="https://user-images.githubusercontent.com/67496158/151750738-6d381cb9-e5f1-4d4a-9a1f-e165c5386619.png">

However, the error persists. Any ideas?

Thanks for helping!

**Comment by AllardQuek** [comment]
Hi @zihaowrez! I'm a CS2103 senior just dropping by to see if I can offer some help. Could I check if you have followed the steps from the [JavaFX tutorial](https://se-education.org/guides/tutorials/javaFxPart1.html) correctly?

I also tried replicating your issue on my machine but wasn't able to do so. If you'd like others to try out your code and configurations, could you push the latest changes (if any) and provide a link to your repository/branch in your issue as well?

**Comment by channne** [comment]
I encountered the same error but it was resolved after creating the `Launcher` class as described in the link @AllardQuek posted!

**Comment by zihaowrez** [comment]
Hi @AllardQuek @channne ! Yes, the problem is resolved after creating the `Launcher` class. Thank you so much!
