### ISSUE TITLE
Must our forks be named the same as the original repo?

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#7]
Are you allowed to rename it? To let's say CS2103_IP, or is there some automated grading system that requires us to use the exact same name?

**Comment by damithc** [comment]
@TypeDefinition the fork should keep the original name `ip` (but you can rename files/packages).

**Comment by TypeDefinition** [comment]
> @TypeDefinition the fork should keep the original name `ip` (but you can rename files/packages).

Thanks prof.
