### ISSUE TITLE
Not sure why Gradle is printing an excess string for this test

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#70]
After setting up Gradle, I tried running Gradle on the test folder, but somehow there's an unintended String being printed out:

This is the particular test:

``` java

    @Test
    @DisplayName("String representation of Task is fine.")
    public void checkString() {
        Task exampleTask = new Todo("study hard");
        String expected = "[T][ ] study hard";
        String actual = exampleTask.toString();
        assertEquals(expected, actual);
    }

```

The result from Gradle is that:
TaskTest > String representation of Task is fine. PASSED
Got it. I've added this task:
  [T][ ] 
  
I am not sure why the "Got it. I've added this task: [T][ ] is being printed...

Screenshot:
![image](https://user-images.githubusercontent.com/83687861/151765458-ef444f61-5092-4485-8838-d8909aa8d2e1.png)

Link to my branch: [Link](https://github.com/yuqitanyq/ip/blob/master/src/test/java/duke/tasks/TaskTest.java)

**Comment by vimuthm** [comment]
Hi @yuqitanyq ,

It seems to be a result of [this](https://github.com/yuqitanyq/ip/blob/d1f5dd6686c0f8d784e247576e8b0ea3fa68be93/src/test/java/duke/functionality/ParserTest.java#L32) line of code, in the `indexOutOfBounds` testcase, which calls `parse()` which in turn calls `addToDoTask()` where there's a print stmt.

**Comment by albertsutz** [comment]
@VimuthM basically answered it, but I would like to add something.

I personally would recommend not printing directly and letting the UI class handles all the printing. In this way, you will not face extra printing when doing the unit testing. This way, you control what the app outputs to the screen better.

**Comment by yuqitanyq** [comment]
okay got it! Thanks @VimuthM and @albertsutz !
