### ISSUE TITLE
JavaDocs for overriden methods

### ISSUE THREAD

**Issue by takufunkai** [nus-cs2103-AY2122S2/forum#71]
I understand we are told to refer to the Google Java style guide for things that were not covered in the Java coding standard file. For this [specific point made in the Google Java style guide](https://google.github.io/styleguide/javaguide.html#s7.3.2-javadoc-exception-overrides), can I confirm that we can abide by it?
> Javadoc is not always present on a method that overrides a supertype method.

Especially for methods which JavaDocs are the same as its class' supertype's method.

**Comment by damithc** [comment]
@takufunkai The following rule in our coding standard applies to overridden method as well (not mentioned means no special treatment)

>You MUST write header comments for all classes, public methods except for getters/setters.

Rather than duplicating the same comment, you can use a `@inheritDoc` tag to show that you are explicitly inheriting the javadoc from the parent.

**Comment by takufunkai** [comment]
Thank you Prof, closing the issue now.
