### ISSUE TITLE
Problem When Including Controller for Duke GUI

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2103-AY2122S2/forum#72]
I followed up to part 3 of the [JavaFX Tutorial](https://se-education.org/guides/tutorials/javaFx.html). However, when I followed part 4 I encountered this error:

```
Caused by: java.lang.ClassNotFoundException: MainWindow
```

[Here](https://github.com/zihaowrez/CS2103_iP/tree/branch-A-Gradle) is my branch with the issue ("Problematic implementation of GUI with controller").

I've copied entirely `MainWindow.fxml`, `DialogBox.fxml`, `MainWindow.java`, `Main.java`, `DialogBox.java` and `Launcher.java` from the tutorial and changed only the file name of the images.

Thanks for helping!

**Comment by domlimm** [comment]
Hi @zihaowrez ! Did you remember to update your `Launcher` file?

**Comment by zihaowrez** [comment]
Hi @domlimm ! I think I've done so:

<img width="275" alt="Screenshot 2022-02-01 124204" src="https://user-images.githubusercontent.com/67496158/151913919-832e80d1-f71d-46a9-80ed-a74a9e444741.png">

**Comment by domlimm** [comment]
That's really odd... Try `File -> Invalidate Caches -> Restart`!

**Comment by vimuthm** [comment]
Also make sure that you updated your `fx::controller` property in the `AnchorPane` element of `MainWindow.fxml` to include the path starting from your package.
So in your case it should be `duke.MainWindow`

**Comment by zihaowrez** [comment]
@VimuthM Wow that helps! Thanks a lot!
