### ISSUE TITLE
Branch merging fails with "pathspec branch-Name did not match any file(s) known to git"

### ISSUE THREAD

**Issue by ovidharshini** [nus-cs2103-AY2122S2/forum#75]
Hi, I am attempting to merge branch-A-JavaDoc with master, and get ```merge: branch-A-JavaDoc - not something we can merge```. 
```git checkout branch-A-JavaDoc``` results in ```error: pathspec 'branch-A-JavaDoc' did not match any file(s) known to git```. 

I completed branch-A-JavaDoc, switched over to master, and completed branch-Level-9 and branch-A-CodingStandard in parallel. The specific commands I used for branch-A-JavaDoc are as follows:
```
git checkout -b branch-A-JavaDoc -> Switched to a new branch 'branch-A-JavaDoc'
git add *.java //and other java files
git status -> On branch branch-A-JavaDoc
                     Changes to be committed:
                      (use "git restore --staged <file>..." to unstage)
                      modified:   Duke.java
                      modified:   Parser.java
                      ... (more *.java files)
git commit -m "Add JavaDoc comments" ->[branch-A-JavaDoc 073b5a4] Add JavaDoc comments
                                                                  10 files changed, 387 insertions(+), 101 deletions(-)
                                                                  rewrite src/main/java/duke/Storage.java (76%)
git tag -a A-JavaDoc 073b5
git push* ->fatal: The current branch branch-A-JavaDoc has no upstream branch.
            To push the current branch and set the remote as upstream, use
                 git push --set-upstream origin branch-A-JavaDoc
git checkout master -> Switched to branch 'master'
                       Your branch is up to date with 'origin/master'
```
*This accidental ```git push``` is the only difference from the protocol I followed for the other parallel branches; I am able to successfully merge the other two branches with master. I am uncertain if this is the cause of the error, and if there is any way to recover branch-A-Javadoc.  Has anyone encountered this issue? 

I do see the commit under https://github.com/<my_username>/ip/releases/tag/A-JavaDoc, and manually copy pasting relevant code to a previous version of master before attempting another merge might possibly work, but is a rather cumbersome approach.

**Comment by Jiaaa-yang** [comment]
Hi! I checked your tagged commits and found this warning message for the commit tagged with **A-JavaDoc**
<img width="1251" alt="Screenshot 2022-02-01 at 5 42 32 PM" src="https://user-images.githubusercontent.com/62281268/151945849-2c4001a7-0a6a-4057-a47c-f34bbdcb6e4d.png">

As explained [here](https://pakstech.com/blog/move-git-tag/), this is because you pushed the tags before pushing the actual branch itself. While I am not sure why this affects your ability to merge it locally, you may want to try pushing the branch **branch-A-JavaDoc** to the remote with 
`git push origin branch-A-JavaDoc` first, then try again.

**Comment by domlimm** [comment]
Remember to add the `-u` flag -> `git push -u origin branch-A-JavaDoc` so that you can create an upstream reference of the local and remote branch and pull with ease i.e. `git pull` instead of `git pull origin branch-A-JavaDoc`.

**Comment by ovidharshini** [comment]
Thanks for the comments! I was unable to push the branch to the remote with ```git push origin branch-A-JavaDoc``` - the branch did not seem to exist locally. I ended up creating a new branch-A-JavaDoc branch, discarding newer commits with ```git reset --hard```, then copy-pasting my previous changes to the file manually before updating the tag with ```--force```. 

Since it is now resolved, I will be closing this issue. If anyone has a better solution to this issue or comments to add, feel free to re-open this again.
