### ISSUE TITLE
git checkout to another branch when the changes in the current branch is not committed yet

### ISSUE THREAD

**Issue by jbkim1999** [nus-cs2103-AY2122S2/forum#78]
Hi everyone,

For week 3's ip task, I made a mistake, which was:

1. I made a new branch (A-JavaDoc) and added JavaDoc comments.
2. Then <strong>without git add . and git commit </strong>, I checked out to the master branch.
3. Then I made a new branch (A-CodingStandard), and did a little fix based on the standards.
4. Again, <strong>without git add . and git commit </strong>, I checked out to the master branch.
5. Then I made a new branch (Level-9) and added a new file for the new type of Command.
6. Again, <strong>without git add . and git commit </strong>, I checked out to the master branch.

As a result, what I did was just to create three branches, but all the work I was doing was reflected on the master branch.

My question is, how is checking out to other branch possible when I have not committed any changes? Shouldn't git throw an error (such as that I need to commit or stash the changes)?

**Comment by domlimm** [comment]
Hello @jbkim1999 ! As long as you have not staged your changes i.e. `git add .`, you'll be able to check out to other branches. [This](https://stackoverflow.com/questions/1304626/git-switch-branch-and-ignore-any-changes-without-committing#:~:text=git%20checkout%20works%20just%20fine,git%20add%20or%20the%20like.) might be helpful!

I have tried it on my own too and it works as the above mentioned!

**Comment by jbkim1999** [comment]
Thanks, @domlimm for your response.

I found a useful comment from the above post, so let me share this comment then close the issue.

"when you switch to a branch without committing changes in the old branch, git tries to merge the changes to the files in the new branch. If merging is done without any conflict, swithing branches will be successful and you can see the changes in the new branch. But if a conflict occur, you will get error: You have local changes to '<filename>'; cannot switch branches. and branch will not change. you can do git checkout -m <branch-name> to merge conflicts and checkout to the branch and resolve conflicts yourself, or git checkout -f <branch-name> to ignore changes."
