### ISSUE TITLE
Renaming package from Capitalised to lowercase causing program to not run

### ISSUE THREAD

**Issue by zzhikai** [nus-cs2103-AY2122S2/forum#79]
Anyone has experience renaming their package folder? After renaming my package folder to adhere to the coding standard, my duke program cannot seem to run at all. Hence I had to revert back to the previous version instead.

I had the following errors below.

```java
Exception in thread "main" java.lang.NoClassDefFoundError: duke/task/Todo (wrong name: Duke/Task/Todo)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Duke.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

```

**Comment by domlimm** [comment]
Hi @zzhikai ! Not sure if you've done this. When you rename a file, directory or package, at least in IntelliJ, it is best to `Right Click on your target -> Refactor -> Rename`, so that IntelliJ takes care of all the extra renaming you've to do if other files/directories/packages depend on your target.

![image](https://user-images.githubusercontent.com/46486515/152083132-99a50701-ef36-41d8-9c91-d520df280823.png)

**Comment by damithc** [comment]
@zzhikai In case it is caused by stale class files, you can delete the `out` folder and run the project again. Also do a project-wide case sensitive search to find if you have `Duke` somewhere in the code where it's supposed to be `duke`.

**Comment by zzhikai** [comment]
> @zzhikai In case it is caused by stale class files, you can delete the `out` folder and run the project again. Also do a project-wide case sensitive search to find if you have `Duke` somewhere in the code where it's supposed to be `duke`.

Thank you prof, this worked. Also realised that I was parsing in a .ser file which has the task identifier as Duke.Task.Event as an example,  hence causing problem to not being able to run beyond reading in the file as well.

**Comment by zzhikai** [comment]
> Hi @zzhikai ! Not sure if you've done this. When you rename a file, directory or package, at least in IntelliJ, it is best to `Right Click on your target -> Refactor -> Rename`, so that IntelliJ takes care of all the extra renaming you've to do if other files/directories/packages depend on your target.
> 
> ![image](https://user-images.githubusercontent.com/46486515/152083132-99a50701-ef36-41d8-9c91-d520df280823.png)

Thanks for sharing this tip!
