### ISSUE TITLE
Level-10 : JavaFX version difference error

### ISSUE THREAD

**Issue by Rdac0** [nus-cs2103-AY2122S2/forum#84]
I've followed the instructions given for the [JavaFX introduction](https://se-education.org/guides/tutorials/javaFx.html) as exactly as possible.

After trying to run it and fix it slightly (because following the instructions exactly leaves compile errors for some reason), the GUI finally runs. However, every time I press the 'send' button, the console outputs these lines:

```
Feb 02, 2022 10:17:30 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 17 by JavaFX runtime of version 11
Feb 02, 2022 10:17:30 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 17 by JavaFX runtime of version 11
```

I've been trying to find where the version refence for these two are. However, apart from this, I want to report how incomplete the JavaFX introduction is.

Anyone else had this issue or has solved it?

(minor point here but I find it silly that the tutorial pages have a forward button but not a back button. Like if I'm in [part 4](https://se-education.org/guides/tutorials/javaFxPart4.html) it takes me at least 2 clicks to get to part 3. Silly)

**Comment by glennljw** [comment]
This probably happened as SceneBuilder overwrites the JavaFX version of your _.fxml_ file on save. 

You can check this [link](https://stackoverflow.com/questions/65987397/how-to-set-preferred-version-in-scene-builder) out to overwrite the version number. Alternatively, look out for the line of code below in your _.fxml_ file, and replace **<version_number>** with the same version number as the [JavaFX guide](https://se-education.org/guides/tutorials/javaFxPart4.html) under 'Rebuilding the Scene using FXML'. 
```
xmlns="http://javafx.com/javafx/<version_number>"
```
This is a temporary fix as you would have to manually change each time you make any changes to the _.fxml_ file with SceneBuilder. Hope it helps!

**Comment by Rdac0** [comment]
> This probably happened as SceneBuilder overwrites the JavaFX version of your _.fxml_ file on save.
> 
> You can check this [link](https://stackoverflow.com/questions/65987397/how-to-set-preferred-version-in-scene-builder) out to overwrite the version number. Alternatively, look out for the line of code below in your _.fxml_ file, and replace **<version_number>** with the same version number as the [JavaFX guide](https://se-education.org/guides/tutorials/javaFxPart4.html) under 'Rebuilding the Scene using FXML'.
> 
> ```
> xmlns="http://javafx.com/javafx/<version_number>"
> ```
> 
> This is a temporary fix as you would have to manually change each time you make any changes to the _.fxml_ file with SceneBuilder. Hope it helps!

Thanks! However, now there seems to be other, unrelated problems bugging me, such as the gui window not having a title. I don't think even god knows what I'm doing anymore.

**Comment by glennljw** [comment]
You can try adding this line of code in the ***start method*** of the ***Main*** class.
```java
public void start(Stage stage) {
    // rest of code here
    stage.setTitle("title")
}
```

**Comment by bingsen0806** [comment]
Thank you @glennljw I was having this issue too and just dropping a comment here so that I can keep track of my issues resolved.
