### ISSUE TITLE
Part 4 of JavaFX tutorial: Unable to launch GUI

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#86]
Hi all, I followed the JavaFX tutorial up until Part 4 & am experiencing some issues at the final step. When I run `Application.launch(Main.class, args);`, I get the error `Caused by: java.lang.ClassNotFoundException: MainWindow` thrown. This is the second time I redid Part 4, but still face the same issue.

Anyone might know of a possible fix?

**Comment by takufunkai** [comment]
Can you push your Level-10 branch? To make it easier to help you troubleshoot.

**Comment by AAlghrairy** [comment]
Modify line 9 of MainWindow.fxml

Specifically, on fx:controller="MainWindow", make sure you include the package name as well.

So if MainWindow class is in a package titled "launchers", change the fxcontroller to:

fx:controller="launchers.MainWindow"

**Comment by waffledood** [comment]
> Can you push your Level-10 branch? To make it easier to help you troubleshoot.

Thanks Ezekiel! I've managed to resolve for now with @AAlghrairy's advice 

> Modify line 9 of MainWindow.fxml
> 
> Specifically, on fx:controller="MainWindow", make sure you include the package name as well.
> 
> So if MainWindow class is in a package titled "launchers", change the fxcontroller to:
> 
> fx:controller="launchers.MainWindow"

Hey man, thanks for your help, that did the trick!

Just to check with the both of you, is this what the GUI looks & performs like? Seems odd that its behavior is different from the one covered in Parts 1 - 3 of the tutorial, in the sense this GUI doesn't show the scroll bar on launch, can be resized easily while the earlier mockup didn't 

[Duke FXML GUI](https://imgur.com/a/wRGfdzK)

**Comment by AAlghrairy** [comment]
Glad it helped 👍 

The purpose of changing it to FXML is to make it so you can modify the design and style using SceneBuilder. 

(Make sure you follow the instructions in #84 to prevent version difference compile errors after saving and exiting SceneBuilder)

As for the startup, make sure you delete the start() method from duke as it is redundant, only the start() method from "Main" 
class should be used. From there, make any modifications to the style and behavior using Scenebuilder or through the start() method in the "Main" class (Also through the handleUserInput() method from MainWindow.java if you need any changes in behavior to the Window corresponding to a specific input)

**Comment by waffledood** [comment]
thanks man :) by the way wanted to check with you if this was what the GUI looked like when using the FXML implementation from the tutorial? 
[Duke FXML GUI](https://imgur.com/a/wRGfdzK)

**Comment by AAlghrairy** [comment]
Yea, that's what it should look like after implementing the example implementation from the tutorial.
