### ISSUE TITLE
Set up runtest.bat file

### ISSUE THREAD

**Issue by AdrianOngJJ** [nus-cs2103-AY2122S2/forum#87]
Hello,

I don't quite understand what I need to change for the runtest.bat file. Here's what I've changed:
```
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp C:\Users\adria\Desktop\iP\src\main\java -Xlint:none -d ..\bin C:\Users\adria\Desktop\iP\src\main\java\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ../bin C:\Users\adria\Desktop\iP\src\main\java\Duke.java < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT
```

I ran it and it gave me this error: 
`Error: Could not find or load main class C:\Users\adria\Desktop\iP\src\main\java\Duke.java`

**Comment by lkldev** [comment]
For the line `java -classpath ../bin C:\Users\adria\Desktop\iP\src\main\java\Duke.java < input.txt > ACTUAL.TXT`, it should remain as `java -classpath ../bin Duke < input.txt > ACTUAL.TXT`. Hope this helps :)

**Comment by AdrianOngJJ** [comment]
@lkldev thank you for the fix! However, I ran into the following error:
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Duke has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`
I've tried to Google the error and found [this](https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips).

But, I do not know how to change the setting for it. Thanks for helping me.

**Comment by lkldev** [comment]
In your terminal, can you run the following commands and send a screenshot of the output?
```bat
java -version
javac -version
where java
where javac
```

**Comment by AdrianOngJJ** [comment]
@lkldev Ok here it is.

In Ubuntu:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/32859142/152316192-0908454d-0f71-40da-82de-40b5a1359c3b.png">

In PowerShell:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/32859142/152316244-52cb95a6-8185-45dc-adc0-287766783dcd.png">

**Comment by lkldev** [comment]
Oops my bad, didn't specify to run them on cmd instead. No worries, in powershell, can you run these two commands?
```
Get-Command java | Select-Object -ExpandProperty Definition
Get-Command javac | Select-Object -ExpandProperty Definition
```

**Comment by AdrianOngJJ** [comment]
Here it is:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/32859142/152317481-ff3c0242-0519-4e3f-b807-6a7e42a6089e.png">

**Comment by lkldev** [comment]
Ah that is the issue, you are using different `java` and `javac` versions... your `java.exe` is running an older version of java. You can either uninstall the java oracle, or you can run your text-ui-test on ubuntu, changing the path found in runtest.sh instead of runtest.bat.

**Comment by AdrianOngJJ** [comment]
@lkldev Oh yes it works!!! I uninstalled the java oracle. Thank you very muchh
