### ISSUE TITLE
Unable to create data\duke.txt

### ISSUE THREAD

**Issue by AdrianOngJJ** [nus-cs2103-AY2122S2/forum#89]
Hello,

I've tried to do the `Level 7: Save` task and I've did the following just to test it out first:
```
        String home =  System.getProperty("user.home"); // base directory
        // following code should give me [HOME_DIRECTORY]/Desktop/iP/data
        java.nio.file.Path path = java.nio.file.Paths.get(home,"Desktop", "iP", "data");
        boolean directoryExists = java.nio.file.Files.exists(path);
        System.out.println(directoryExists);
        // if path doesn't exist, make new directory and file
        if (!directoryExists) {
            File dataDirectory = new File(path.toString());
            File dukeStore = new File(path + "\\duke.txt");
            System.out.println("I tried creating a new directory " + dataDirectory);
            System.out.println("I tried creating a new file " + dukeStore);

        }
        System.out.println("Does this directory " + path + " exist? " + directoryExists);
        System.exit(0);
```

I referred to [this](https://www.sghill.net/how-do-i-make-cross-platform-file-paths-in-java.html) and this is the result that I've got:
```
C:\Users\adria\.jdks\corretto-11.0.14\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1\lib\idea_rt.jar=59796:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\adria\Desktop\iP\out\production\iP Duke
false
I tried creating a new directory C:\Users\adria\Desktop\iP\data
I tried creating a new file C:\Users\adria\Desktop\iP\data\duke.txt
Does this directory C:\Users\adria\Desktop\iP\data exist? false

Process finished with exit code 0
```

**Comment by domlimm** [comment]
Hello @AdrianOngJJ ! Could you try doing this:

```java
File dukeStore = new File(path + "\\duke.txt");

// This instead. I remembered searching on the path and it should be dynamic (working for all OSes)
File dukeStore = new File(path + "/duke.txt");
```

I believe that at the end, your path should be just `data/store.txt` because in the later stages, you'd have to generate a JAR file and wherever the user downloads it locally, your program would have to make use of the current directory and create the `store.txt` file at the same place.

Alternatively, you could [refer](https://github.com/domlimm/ip/blob/548a07aaf81c7906d5444cbbf8db7634889e8541/src/main/java/Duke.java#L230) to how I handled the file (should work on any system i.e. OS). It's encouraged for us to learn from one another!

**Comment by onefangg** [comment]
Hi @AdrianOngJJ , you should add `directoryExists = java.nio.file.Files.exists(path);` again after the if block as the code only checks if the directory exists before the creation of the directory (assuming the directory didn't exist prior to this code run)

**Comment by AdrianOngJJ** [comment]
@domlimm it works! Why do I need to add this line `dataDirectory.mkdir();` for the directory to appear? However, I managed to create the `data` directory but not the `duke.txt` file

@onefangg yeap it make sense! thank youu

**Comment by domlimm** [comment]
> @domlimm it works! Why do I need to add this line `dataDirectory.mkdir();` for the directory to appear? However, I managed to create the `data` directory but not the `duke.txt` file

Nice! `mkdir()` creates a directory, or makes a new directory. You could read up a lil more [here](https://www.geeksforgeeks.org/file-mkdir-method-in-java-with-examples/)! If you've the time 👍🏻 

<hr>

I believe we need to first create the directory/folder i.e. `data` before creating the file. If the file/directory does not exist.

A directory is actually a `File` too. So, we need to first check if the directory exists i.e. `/data`. If not, we need to create the directory:
```java
File directory = new File(FILE_PATH);

if (!directory.exists()) {
    directory.mkdir();
}
```

Following that, we'll just do the same by specifying the `FILE_PATH + FILE_NAME` when creating a new `File` object.

And if i'm not mistaken, Java nicely handles the file path for you i.e. Dynamically handling the format for different OSes.

Just specify:
```java
File file = new File("data/duke.txt");
```

It is better to read up, I might not have explained properly. Or above were the steps I took. I remembered searching for
1. Checking if directory exists using File object Java
2. Creating a file in Java
3. Or some other related tutorial, that handles both directory and file (when it's present, if not create)

**Comment by ryantanlien** [comment]
@AdrianOngJJ Should probably close the issue if it now works!
