### ISSUE TITLE
suppressions.xml doesn't seem to be working

### ISSUE THREAD

**Issue by limweiliang** [nus-cs2103-AY2122S2/forum#90]
I have followed the instructions given and copied over the checkstyle.xml and suppressions.xml files from the AddressBook project so as to enable Checkstyle. However,  it seems like the following suppression in my suppressions.xml file doesn't seem to be working:
```xml
<suppressions>
    <suppress checks="JavadocType" files=".*Test\.java"/>
    <suppress checks="MissingJavadocMethodCheck" files=".*Test\.java"/>
</suppressions>
```
When I run the checkstyle,it is still complaining about missing Javadoc methods, as given below:
`Missing a Javadoc comment. (11:5) [MissingJavadocMethod]`

Is there a need to specifically tell Checkstyle to make us of the suppressions.xml file? I'm using IntelliJ on Windows 10.

**Comment by damithc** [comment]
> When I run the checkstyle,it is still complaining about missing Javadoc methods, as given below:
> `Missing a Javadoc comment. (11:5) [MissingJavadocMethod]`

@limweiliang what's the name of the file for which the above error is reported?

**Comment by limweiliang** [comment]
This occurs for all my .java files - here's the directory structure of my project:

![image](https://user-images.githubusercontent.com/68314786/152339495-f3145e33-faf5-4868-9151-0b946d4534ae.png)

and this is where I'm keeping the config files:
![image](https://user-images.githubusercontent.com/68314786/152339589-bb2f895c-ef50-4e4d-a9ce-88fdc67acdee.png)

**Comment by damithc** [comment]
@limweiliang That rule is not meant to cover _all_ java files. If you look at the rule definition, you'll see that it is targeting certain file name patterns only.

**Comment by limweiliang** [comment]
Oh! Thank you so much! I didn't realize it was only targeting Test classes
