### ISSUE TITLE
Error "Unable to instantiate 'FileContentsHolder' class" when trying to run checkstyleMain with Gradle

### ISSUE THREAD

**Issue by charmainehly** [nus-cs2103-AY2122S2/forum#92]
I have imported the config file from the AddressBook3 repository so that I can run Checkstyle using Gradle. However, when I try to run checkstyleMain with the Gradle toolbar, I'm met with the following error. 

```java
Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as .FileContentsHolder, FileContentsHolderCheck, .FileContentsHolderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
```

From my understanding, I don't think there is a need to edit the Checkstyle.xml file, but am unsure of how to trace and resolve such an error?

**Comment by damithc** [comment]
@charmainehly this is the first time someone mentioned this error. Perhaps describe exactly what steps you took to add checkstyle support to your project, in case your steps differed from others?

You can also try `File -> Invalidate Cache` and restarting the IDE.

**Comment by charmainehly** [comment]
Hi prof, thanks for the reply! I missed out on a previous post on the same error --> linking it [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/70) for others' reference!
