### ISSUE TITLE
Left Multiple Comments for iP Review

### ISSUE THREAD

**Issue by FYimu** [nus-cs2103-AY2122S2/forum#93]
Hiii I did not know we were supposed to leave all comments in one review for my first code review, so I added about 11 single comments for a peer for whom I was supposed to review... 😭 

Can I ask if this would affect the auto-grading on the PR review, or is there any way I can remedy this?

**Comment by damithc** [comment]
@FYimu It's OK. You can do another review (in the correct format) of the same PR and add 1-2 more comments.

**Comment by FYimu** [comment]
> @FYimu It's OK. You can do another review (in the correct format) of the same PR and add 1-2 more comments.

Thank you prof!
