### ISSUE TITLE
URL is not registered for checkstype file

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#94]
Hi,

I copied the checkstyle file from the ab3 folder but I encountered this problem.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/77788377/152330210-42a2fc12-d770-4e8f-891a-ccdb19d9b5b6.png">

**Comment by onefangg** [comment]
Hi @e0543517, have you tried running `gradlew checkstyleMain` under the gradle toolbar?

If gradle is set up correctly, you see the gradle toolbar under View > Tool Windows > Gradle. From there, click the elephant icon highlighted below and then run the command `gradlew checkstyleMain` 

![image](https://user-images.githubusercontent.com/46132040/152332757-c35eeae0-e386-4fcb-9149-cef6f5d44a2f.png)

Let us know if you face further issues from there

**Comment by bingsen0806** [comment]
Hi, I actually managed to run the gradle `checkstyleMain` task, but on the XML file there's still this error. It doesn't affect much but may I know how should I correct it if I really want to?

**Comment by onefangg** [comment]
If you wish to disable the error `URI is not registered...` you can `alt + enter` over the http link in the checkstyle.xml and choose `Fetch external resource`. If you go into the `File > Settings > Languages & Frameworks > Schemas and DTDS`, you'll see the same link added as such: 

![image](https://user-images.githubusercontent.com/46132040/152360206-2de81eca-d7d8-4ffc-82b7-edd14925b927.png)

As for the typos, I'm not really certain on how to disable those, so I'm not much help on that

**Comment by takufunkai** [comment]
For the typos, either change them to something that is acceptable by the checkstyler, or add them to the list of acceptable words: hover over the word, and intellij should give you a prompt with the option to add them to the list.
