### ISSUE TITLE
Checkstyle using Gradle

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#95]
Anyone else having this issue when using Gradle checkstyleMain task?

<img width="943" alt="image" src="https://user-images.githubusercontent.com/77788377/152331067-1dd9c7da-11cf-4bf0-8429-34cafad4a504.png">

**Comment by domlimm** [comment]
Hi @e0543517 ! You can get the `checkstyle` and `suppression` files from [here](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle) to add it into your project `config/checkstyle`.

**Comment by declanleeler** [comment]
Hi @e0543517. Like @domlimm said, create the necessary folders with this structure:
<img width="299" alt="Screenshot 2022-02-03 at 11 14 04 PM" src="https://user-images.githubusercontent.com/50820543/152370795-264a8dac-d69a-40da-9878-012b18a1cec1.png">

Inside the folder, create 2 new .xml with the same names and content as the link @domlimm provided. 
Hope this helps!
