### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by tzhan98** [nus-cs2103-AY2122S2/forum#96]
Hi all, I am receiving the above error when I attempt to run my Launcher class.
I am currently running gradle by updating build.gradle to include the following files:
```
repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```
However, I get this error when I run I get the following error
![image](https://user-images.githubusercontent.com/77192480/152356898-78da8c7a-32df-4ac3-b606-c57d696577db.png)
I searched the [web](https://github.com/javafxports/openjdk-jfx/issues/423) and it seems that I have to add javafx librairies from the javafx-sdk directory
>Ok, finally, I found your problem: You separated javafx librairies from the sdk directory.
When you extract the javafx-sdk archive, you must not move librairies (from javafx-sdk-12/lib directory) because JavaFX need included binaries for execution.
So, inside Intellij, add javafx librairies from the javafx-sdk directory (javafx-sdk-12/lib) to your project and it works.

I have tried 
![image](https://user-images.githubusercontent.com/77192480/152360435-a4f4a83e-b3d4-4784-95ce-10be057bbed2.png)
to add files to library.

but it gives me the following error when i add it to CS2103T.ip

![image](https://user-images.githubusercontent.com/77192480/152360380-68758b7b-380c-4e8a-9d68-4b6d7f152b2e.png)

My project structure
![image](https://user-images.githubusercontent.com/77192480/152361214-4c0b18ef-88b1-4897-bb05-160d4992dc83.png)

**Comment by damithc** [comment]
@tzhan98 This issue came up in previous semesters too. See if [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/173) (from a previous sem) helps.

**Comment by tzhan98** [comment]
I believe that I am doing as what Weiliang suggested in pulling the repo individually. Is it possible that it is my main project structure that is causing me problems? ( Seeing that there is 2 main and test)

**Comment by damithc** [comment]
> I believe that I am doing as what Weiliang suggested in pulling the repo individually. Is it possible that it is my main project structure that is causing me problems? ( Seeing that there is 2 main and test)

@tzhan98 Hmm... that doesn't look right. When adding gradle support, did you follow scenario 2 given in https://se-education.org/guides/tutorials/gradle.html#adding-gradle-to-the-project ?

**Comment by tzhan98** [comment]
I did follow the scenario 2 given. (Maybe it was because I also tried to add a new gradle on my own prior)
Found out that my problem was my project structure. Had to delete the extra modules seen above. `ip, main and test`.  After that, I was able to run Launcher without any issues.

Also, was able to run Launcher just by creating a new project and copying the files over.
