### ISSUE TITLE
Level-10 - FindException: Module javafx.controls not found

### ISSUE THREAD

**Issue by isabelteo** [nus-cs2103-AY2122S2/forum#98]
I am using IntelliJ community 2021.1.2 , Windows and JDK 16.0.1.  (will change to Java 11 soon) and I am using JavaFx Version 11

Here is the error message I faced
```java
> Task :Launcher.main() FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
```
I had a similar issue with importing java fxml but I fixed it based on a previous issue #67 

After changing my code to fix java fxml, I was no longer able to launch the launcher so the problem is likely to be in built.gradle

Here is the link to the branch I am working on for  Level-10: https://github.com/isabelteo/ip/tree/branch-Level-10

 I've been trying for quite a while but I don't really know what went wrong ;  I also can't seem to find a similar issue so I am posting; Thank you so much for helping!

**Comment by putaojuice** [comment]
This is from your Launcher class:

``` java
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}
```

If you are working on GUI for Duke, maybe you can try launch with Duke.class instead of Main.class?

**Comment by isabelteo** [comment]
@putaojuice Thank you for helping out! I have adjusted my code to launch from Duke and I edited Launcher to use` Duke.class` as you suggested but there is still the same FindException D:

I have pushed my edits into the branch: https://github.com/isabelteo/ip/tree/branch-Level-10

Launcher.java is in the directory gui 
Duke.java is in the directory main

**Comment by domlimm** [comment]
Hello @isabelteo ! I encountered something similar to what you're facing. It was because I wanted to have `start()` in `Duke`. I ended up just following the tutorial with the `Main` class (Issue #73). Let us know how it goes!

**Comment by damithc** [comment]
@isabelteo Is https://github.com/isabelteo/ip/blob/branch-Level-10/build.gradle#L45 correct? It says `duke.duke.Duke`

**Comment by TypeDefinition** [comment]
I've faced this problem as well, and the issue I found was that this happens if your `public static void main` is also in your `Application` class. Since our `public static void main` is really short, we might be tempted to combine it with the `Application`, but JavaFX does not like that.

**Comment by isabelteo** [comment]
@domlimm Hi, I've changed it back to using Main Class and @damithc I've edited that mistake (it became duke.duke because I was trying to reference other successful gui builds to check my errors) but it still has the same FindException being thrown 

I tried the alternative way of setting up built.gradle in the tutorial but still doesn't seem to work

My JDK is now 11 already too

**Comment by isabelteo** [comment]
@TypeDefinition ohh so the class with` public static void main` cannot extend Application class? I think my Launcher class, which does has the `public static void main`, doesn't extend Application already though

**Comment by limzk126** [comment]
Hi @isabelteo i am a senior from the previous batches of CS2103T (Stopping by to see if i can help you guys with technical problems!)

Maybe you can try updating your `SDK (Software Development Kit)` to `OpenJDK 11` under Files --> Project Structure ?
I tried it with your code and it seemed to be able to run `Launcher.main()` successfully on my end.

![image](https://user-images.githubusercontent.com/88614036/152475928-b7429b5d-25e5-47a6-aa97-3aa953e6d4d7.png)

![image](https://user-images.githubusercontent.com/88614036/152475976-ffbe4aea-41cc-400c-8d7b-6eed7b34f5f1.png)

**Comment by limzk126** [comment]
Hi @isabelteo I am a Senior from the previous batches of CS2103T (Dropping by to see if i can help you guys with technical problems!)

Just want to check did you update the correct SDK settings under File --> Project Structure?
I think i encountered a similar problem as you when i left it as `<No SDK>` but once i updated it to the correct OpenJDK version i was able to run `Launcher.main()` on my end.

Edit: I tested it out on the branch you linked us.

![image](https://user-images.githubusercontent.com/88614036/152476965-4ae32cca-92f9-4864-9ad8-484d2b8dd854.png)

![image](https://user-images.githubusercontent.com/88614036/152477287-445d25b4-761c-4a7c-855e-afb6680d9740.png)

**Comment by domlimm** [comment]
Hey @isabelteo, similar to @limzk126, I cloned your repo and checked out to `branch-Level-10` and just did what @limzk126 did and I could run your program! Really cute display pictures btw! 😃 

![image](https://user-images.githubusercontent.com/46486515/152479383-7e3b1133-5459-411a-8849-3b287b8012d2.png)

Maybe you could remove your local directory, and clone your repo again. The setup should be as how @limzk126 did.

**Comment by isabelteo** [comment]
@limzk126  @domlimm  thank you so much! 💯  

I have been trying with JDK 11.0.5 from https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html but it doesn't seem to work, is it possible for you to link to me where you downloaded your JDK? I can't seem to find it T.T so sorry

**Comment by domlimm** [comment]
@isabelteo I'm using this version:
![image](https://user-images.githubusercontent.com/46486515/152490555-8b1621e4-8bdd-44c0-a388-2dd8e2cc41e3.png)

Let me go figure how I installed it. I can't remember 😭 

Try downloading `JDK 11.0.13` from the link you added! If not, you could just donwload `JDK 11.0.11` :')

Oops found it! [Here](https://adoptopenjdk.net/archive.html). Not sure if you've to remove your current JDK... Try it out!

**Comment by limzk126** [comment]
@isabelteo 

You can try using @domlimm 's link to download the JDK as it seemed to be a more updated version compared to mine.

As for how you configure it to work on Intellij, i don't think there's a need to remove your previously downloaded JDKs. Simply click the `Add SDK` --> `JDK...` option in the `SDK` dropdown and choose the correct path where your downloaded JDK is located.

For my case I had it downloaded under `C:\Program Files\Java\jdk-11.0.5`.

In the worst case where @domlimm 's version/link does not work, simply drop down your email and i will send you my zipped JDK files through google link.

Edit: The link where you downloaded seem to be the same JDK version as mine, are you sure you have correctly configured the path in `Project Structure`?
![image](https://user-images.githubusercontent.com/88614036/152493364-46470790-c89b-4e6e-860a-9e776d56d617.png)

![image](https://user-images.githubusercontent.com/88614036/152493424-9c6b1939-abc1-40e9-9043-7fa8ab4c8f9d.png)

**Comment by isabelteo** [comment]
@domlimm thank you for finding that link for me - really appreciate it - it finally ran :grin: Thank you @limzk126 and all for the advice as well :smiling_face_with_three_hearts:

**Comment by damithc** [comment]
Thanks everyone who pitched in 💯
