### ISSUE TITLE
JavaFx: error when running launcher

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#99]
I'm not sure why I'm having this error when I tried to run the launcher. I have followed the steps in [the](https://se-education.org/guides/tutorials/javaFxPart1.html)

<img width="938" alt="image" src="https://user-images.githubusercontent.com/77788377/152381708-ac346422-fcec-4b97-a383-67dc60c51de2.png">

**Comment by damithc** [comment]
@e0543517 See if this helps https://github.com/nus-cs2103-AY2122S2/forum/issues/73

**Comment by paing-oo** [comment]
@damithc Thank you!
